# Generated by Django 5.2.16 on 2026-07-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedConfigSnapshot',
            fields=[
                ('artifact', models.TextField(primary_key=True, serialize=False)),
                ('content_hash', models.TextField()),
                ('written_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '_applied_config_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('nickname', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('accent_color', models.TextField(blank=True, null=True)),
                ('is_sentinel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name_en', models.TextField(blank=True, null=True)),
                ('display_name_zh_cn', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nickname', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('hq_country', models.TextField(blank=True, null=True)),
                ('accent_color', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name_en', models.TextField(blank=True, null=True)),
                ('display_name_zh_cn', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='DiscourseKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discourse_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NationalismKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nationalism_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('tweet_id', models.TextField(primary_key=True, serialize=False)),
                ('author_handle', models.CharField(blank=True, db_collation='case_insensitive', max_length=64, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(blank=True, null=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('quote_count', models.IntegerField(blank=True, null=True)),
                ('in_reply_to_user_id', models.TextField(blank=True, null=True)),
                ('quoted_status_id', models.TextField(blank=True, null=True)),
                ('conversation_id', models.TextField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, null=True)),
                ('source_query_id', models.TextField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('headline_source', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_zh_cn', models.TextField(blank=True, null=True)),
                ('lang_detected', models.TextField(blank=True, null=True)),
                ('quoted_text', models.TextField(blank=True, null=True)),
                ('last_quote_count_seen', models.IntegerField(blank=True, null=True)),
                ('last_quote_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_epoch', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTypeKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_type_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SentimentKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UnsanctionedFlagKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unsanctioned_flag_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('author_id', models.TextField(primary_key=True, serialize=False)),
                ('handle', models.CharField(blank=True, db_collation='case_insensitive', max_length=64, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('bio_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('bio_contains_brand', models.BooleanField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('source_query_ids', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_zh_cn', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('following_count', models.IntegerField(blank=True, null=True)),
                ('favourites_count', models.IntegerField(blank=True, null=True)),
                ('statuses_count', models.IntegerField(blank=True, null=True)),
                ('media_count', models.IntegerField(blank=True, null=True)),
                ('fast_followers_count', models.IntegerField(blank=True, null=True)),
                ('is_blue_verified', models.BooleanField(blank=True, null=True)),
                ('verified_type', models.TextField(blank=True, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_bio_text', models.TextField(blank=True, null=True)),
                ('followers_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['handle'],
                'indexes': [models.Index(fields=['handle'], name='idx_accounts_handle'), models.Index(fields=['last_seen_at'], name='idx_accounts_last_seen_at')],
            },
        ),
        migrations.CreateModel(
            name='BrandSearchTerm',
            fields=[
                ('pk', models.CompositePrimaryKey('brand', 'term', blank=True, editable=False, primary_key=True, serialize=False)),
                ('term', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='core.brand')),
            ],
            options={
                'db_table': 'brand_search_terms',
            },
        ),
        migrations.CreateModel(
            name='CallState',
            fields=[
                ('pk', models.CompositePrimaryKey('brand_id', 'call_id', 'call_kind', 'bucket', 'query_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('brand_id', models.TextField()),
                ('call_id', models.TextField()),
                ('call_kind', models.TextField()),
                ('bucket', models.TextField(blank=True, default='')),
                ('query_id', models.TextField()),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_state',
                'indexes': [models.Index(fields=['last_completed_at'], name='idx_call_state_completed_at')],
            },
        ),
        migrations.CreateModel(
            name='BrandCompany',
            fields=[
                ('pk', models.CompositePrimaryKey('brand', 'company', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ownership_pct', models.FloatField(default=1.0)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.brand')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.company')),
            ],
            options={
                'db_table': 'brands_companies',
            },
        ),
        migrations.CreateModel(
            name='DiscourseLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('discourse', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.TextField()),
                ('label', models.TextField()),
                ('discourse', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.discoursekey')),
            ],
            options={
                'db_table': 'discourse_labels',
            },
        ),
        migrations.CreateModel(
            name='HFOrg',
            fields=[
                ('namespace', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('discovered_via', models.TextField(default='curated')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='hf_orgs', to='core.company')),
            ],
            options={
                'db_table': 'hf_orgs',
                'ordering': ['namespace'],
            },
        ),
        migrations.CreateModel(
            name='NationalismLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('nationalism', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.TextField()),
                ('label', models.TextField()),
                ('nationalism', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.nationalismkey')),
            ],
            options={
                'db_table': 'nationalism_labels',
            },
        ),
        migrations.CreateModel(
            name='PostUnsanctionedFlag',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='unsanctioned_flags', serialize=False, to='core.post')),
                ('flags', models.TextField()),
                ('flag_set', models.JSONField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts_unsanctioned_flags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.account'),
        ),
        migrations.CreateModel(
            name='AccountPostAppearance',
            fields=[
                ('pk', models.CompositePrimaryKey('account', 'post', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role_at_time', models.TextField(blank=True, null=True)),
                ('source_query_ids', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='core.account')),
                ('post', models.ForeignKey(db_column='tweet_id', on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='core.post')),
            ],
            options={
                'db_table': 'account_post_appearances',
            },
        ),
        migrations.CreateModel(
            name='PostBrand',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', blank=True, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=1.0)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.brand')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.post')),
            ],
            options={
                'db_table': 'posts_brands',
            },
        ),
        migrations.CreateModel(
            name='PostBrandDiscourse',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', 'discourse', 'act_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('act_id', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand')),
                ('china_nationalism', models.ForeignKey(blank=True, db_column='china_nationalism', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.nationalismkey')),
                ('discourse', models.ForeignKey(db_column='discourse_key', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.discoursekey')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='discourse_signals', to='core.post')),
                ('us_nationalism', models.ForeignKey(blank=True, db_column='us_nationalism', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.nationalismkey')),
            ],
            options={
                'db_table': 'posts_brands_discourse',
            },
        ),
        migrations.CreateModel(
            name='PostBrandMention',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', 'source', blank=True, editable=False, primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('raw_token', models.TextField(blank=True, null=True)),
                ('mentioned_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.post')),
            ],
            options={
                'db_table': 'posts_brands_mentions',
            },
        ),
        migrations.CreateModel(
            name='PostTypeLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('post_type', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.TextField()),
                ('label', models.TextField()),
                ('post_type', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.posttypekey')),
            ],
            options={
                'db_table': 'post_type_labels',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repo_id', models.CharField(db_collation='case_insensitive', max_length=256, unique=True)),
                ('hf_type', models.TextField(default='model')),
                ('display_name', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('sha', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(blank=True, null=True)),
                ('gated', models.TextField(blank=True, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('pipeline_tag', models.TextField(blank=True, null=True)),
                ('library_name', models.TextField(blank=True, null=True)),
                ('downloads', models.IntegerField(blank=True, null=True)),
                ('downloads_all_time', models.IntegerField(blank=True, null=True)),
                ('download_velocity', models.FloatField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('trending_score', models.FloatField(blank=True, null=True)),
                ('paperswithcode_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, db_column='tags_json', null=True)),
                ('siblings', models.JSONField(blank=True, db_column='siblings_json', null=True)),
                ('card_data', models.JSONField(blank=True, db_column='card_data_json', null=True)),
                ('config', models.JSONField(blank=True, db_column='config_json', null=True)),
                ('spaces', models.JSONField(blank=True, db_column='spaces_json', null=True)),
                ('raw', models.JSONField(blank=True, db_column='raw_json', null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand')),
                ('hf_org', models.ForeignKey(blank=True, db_column='hf_org_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.hforg')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['repo_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('pk', models.CompositePrimaryKey('company', 'account', blank=True, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.account')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.company')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.role')),
            ],
            options={
                'db_table': 'companies_accounts',
            },
        ),
        migrations.CreateModel(
            name='BrandAccount',
            fields=[
                ('pk', models.CompositePrimaryKey('brand', 'account', blank=True, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='accounts_id', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.account')),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.brand')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.role')),
            ],
            options={
                'db_table': 'brands_accounts',
            },
        ),
        migrations.CreateModel(
            name='RoleLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('role', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.TextField()),
                ('label', models.TextField()),
                ('role', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.role')),
            ],
            options={
                'db_table': 'role_labels',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_id', models.TextField(unique=True)),
                ('keywords', models.JSONField(blank=True, db_column='keywords_json', null=True)),
                ('plan_calls_run_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.brand')),
            ],
            options={
                'db_table': 'search_queries',
            },
        ),
        migrations.CreateModel(
            name='PostBrandSignal',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', 'post_type', blank=True, editable=False, primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.post')),
                ('post_type', models.ForeignKey(db_column='post_type_key', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.posttypekey')),
                ('sentiment', models.ForeignKey(db_column='sentiment', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sentimentkey')),
            ],
            options={
                'db_table': 'posts_brands_signals',
            },
        ),
        migrations.CreateModel(
            name='SentimentLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('sentiment', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.TextField()),
                ('label', models.TextField()),
                ('sentiment', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.sentimentkey')),
            ],
            options={
                'db_table': 'sentiment_labels',
            },
        ),
        migrations.CreateModel(
            name='BrandHashtag',
            fields=[
                ('pk', models.CompositePrimaryKey('brand', 'hashtag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('hashtag', models.TextField(db_column='tag')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='core.brand')),
            ],
            options={
                'db_table': 'brand_hashtags',
                'indexes': [models.Index(fields=['brand'], name='idx_brand_hashtags_brand_id')],
            },
        ),
        migrations.CreateModel(
            name='BrandKeyword',
            fields=[
                ('pk', models.CompositePrimaryKey('brand', 'pattern', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.TextField()),
                ('is_regex', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.brand')),
            ],
            options={
                'db_table': 'brand_keywords',
                'indexes': [models.Index(fields=['brand'], name='idx_brand_keywords_brand_id')],
            },
        ),
        migrations.AddIndex(
            model_name='hforg',
            index=models.Index(fields=['company'], name='idx_hf_orgs_company'),
        ),
        migrations.AddIndex(
            model_name='postunsanctionedflag',
            index=models.Index(fields=['flag_set'], name='idx_unsanctioned_flag_set'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='idx_posts_author_id'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='idx_posts_created_at'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['lang'], name='idx_posts_lang'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['lang_detected'], name='idx_posts_lang_detected'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source_query_id'], name='idx_posts_source_query_id'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at_epoch'], name='idx_posts_created_at_epoch'),
        ),
        migrations.AddIndex(
            model_name='accountpostappearance',
            index=models.Index(fields=['post'], name='idx_acct_post_app_post_id'),
        ),
        migrations.AddIndex(
            model_name='postbrand',
            index=models.Index(fields=['brand'], name='idx_posts_brands_brand_id'),
        ),
        migrations.AddIndex(
            model_name='postbranddiscourse',
            index=models.Index(fields=['brand', 'discourse'], name='idx_post_brand_dis_b_dr'),
        ),
        migrations.AddIndex(
            model_name='postbranddiscourse',
            index=models.Index(fields=['brand', 'china_nationalism'], name='idx_post_brand_dis_b_cn_nat'),
        ),
        migrations.AddIndex(
            model_name='postbranddiscourse',
            index=models.Index(fields=['brand', 'us_nationalism'], name='idx_post_brand_dis_b_us_nat'),
        ),
        migrations.AddIndex(
            model_name='postbrandmention',
            index=models.Index(fields=['brand'], name='idx_post_brand_mention_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='idx_products_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hf_org'], name='idx_products_hf_org_id'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['collected_at'], name='idx_products_collected_at'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['role'], name='idx_companies_accounts_role_id'),
        ),
        migrations.AddIndex(
            model_name='brandaccount',
            index=models.Index(fields=['role'], name='idx_brands_accounts_role_id'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['brand'], name='idx_search_queries_brand_id'),
        ),
        migrations.AddIndex(
            model_name='postbrandsignal',
            index=models.Index(fields=['brand', 'post_type'], name='idx_pb_sig_b_p_type'),
        ),
        migrations.AddIndex(
            model_name='postbrandsignal',
            index=models.Index(fields=['brand', 'sentiment'], name='idx_pb_sig_b_sent'),
        ),
    ]
