# Generated by Django 5.2.16 on 2026-07-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_post_twitterapi_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='raw',
        ),
    ]
