# Generated by Claude on 2026-07-28 — surgical FK ON DELETE fix.
#
# The posts.author (→ accounts) and posts.quoted_status_id (→ posts)
# FKs were created without ON DELETE SET NULL despite the model
# declaring on_delete=SET_NULL. The 0001_initial CreateModel +
# 0002 quoted_status_id AlterField operations produce NO ACTION
# FKs in production (verified against the staging DB restored from
# a fresh prod dump: both pg_constraint.confdeltype = 'a').
#
# This migration drops and recreates both FKs with
# `ON DELETE SET NULL` so:
#   1. The schema matches what the model says
#   2. Deleting an Account / parent Post cannot fail due to orphaned
#      references (with NO ACTION, those deletes would be blocked)
#   3. The U5 regression net's test_self_fk_on_quoted_status_id
#      assertion passes (confdeltype == 'n')
#
# Both FKs are recreated DEFERRABLE INITIALLY DEFERRED to match the
# existing quoted_status_id constraint and to match what 0002
# documented in its operations.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drop_post_raw"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE posts "
                "DROP CONSTRAINT posts_author_id_099b8aca_fk_accounts_author_id, "
                "ADD CONSTRAINT posts_author_id_099b8aca_fk_accounts_author_id "
                "FOREIGN KEY (author_id) REFERENCES accounts(author_id) "
                "ON DELETE SET NULL "
                "DEFERRABLE INITIALLY DEFERRED"
            ),
            reverse_sql=(
                "ALTER TABLE posts "
                "DROP CONSTRAINT posts_author_id_099b8aca_fk_accounts_author_id, "
                "ADD CONSTRAINT posts_author_id_099b8aca_fk_accounts_author_id "
                "FOREIGN KEY (author_id) REFERENCES accounts(author_id) "
                "DEFERRABLE INITIALLY DEFERRED"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE posts "
                "DROP CONSTRAINT posts_quoted_status_id_eccff4ad_fk_posts_tweet_id, "
                "ADD CONSTRAINT posts_quoted_status_id_eccff4ad_fk_posts_tweet_id "
                "FOREIGN KEY (quoted_status_id) REFERENCES posts(tweet_id) "
                "ON DELETE SET NULL "
                "DEFERRABLE INITIALLY DEFERRED"
            ),
            reverse_sql=(
                "ALTER TABLE posts "
                "DROP CONSTRAINT posts_quoted_status_id_eccff4ad_fk_posts_tweet_id, "
                "ADD CONSTRAINT posts_quoted_status_id_eccff4ad_fk_posts_tweet_id "
                "FOREIGN KEY (quoted_status_id) REFERENCES posts(tweet_id) "
                "DEFERRABLE INITIALLY DEFERRED"
            ),
        ),
    ]