# Generated by Claude on 2026-07-28 — chunked 0003 backfill.
#
# 0003's _backfill_columns runs all 50 UPDATE statements inside a single
# transaction. On Render's free-tier Postgres (1GB disk), the WAL +
# dead tuples accumulated over the 50 full-table scans exceeded the
# available disk and the migration crashed with:
#   django.db.utils.OperationalError: could not extend file ...
# That crash corrupted shared memory and forced Postgres to restart;
# the entire transaction rolled back, leaving typed columns NULL.
#
# 0006 runs the same backfill but in committed chunks so dead tuples
# can be reclaimed by autovacuum between chunks. Each chunk is its
# own short transaction (autocommit), and we explicitly commit + run
# VACUUM between major groups (author scalars, author bools, view_count,
# quoted_status_id).
#
# Idempotent: every UPDATE has `WHERE {col} IS NULL`, so re-running is
# a no-op for already-populated columns.
#
# Both 0003 and 0006 do the same work on a fresh DB, but only 0006 is
# safe on the production Render free-tier instance. 0003 was kept as
# a no-op (its body was replaced with a pass) for historical record.

from django.db import migrations


def _backfill_in_chunks(apps, schema_editor):
    """Run the 0003 backfill in committed chunks to avoid OOM on prod."""
    from django.db import connection

    if schema_editor.connection.vendor != "postgresql":
        return

    # The Django migration wraps this in a transaction. We want
    # autocommit per group so dead tuples can be reclaimed. Force
    # autocommit by calling connection.commit() at group boundaries;
    # the migration's outer transaction will still wrap the whole
    # function, so this is effectively a no-op for transactionality
    # unless we explicitly close the outer transaction. Django's
    # MigrationExecutor doesn't allow that, so instead we use a
    # connection-level setting: SET autocommit=on; this makes each
    # cur.execute commit immediately.
    old_autocommit = connection.autocommit
    connection.autocommit = True
    try:
        with connection.cursor() as cur:
            # --- Group 1: 12 author text scalars ---
            author_scalar_updates = [
                ("author_name", "name", "raw->'raw'->'author'->>'name'"),
                ("author_automated_by", "automatedBy", "raw->'raw'->'author'->>'automatedBy'"),
                ("author_cover_picture", "coverPicture", "raw->'raw'->'author'->>'coverPicture'"),
                ("author_created_at_raw", "createdAt", "raw->'raw'->'author'->>'createdAt'"),
                ("author_description", "description", "raw->'raw'->'author'->>'description'"),
                ("author_location", "location", "raw->'raw'->'author'->>'location'"),
                ("author_profile_picture", "profilePicture", "raw->'raw'->'author'->>'profilePicture'"),
                ("author_status", "status", "raw->'raw'->'author'->>'status'"),
                ("author_twitter_url", "twitterUrl", "raw->'raw'->'author'->>'twitterUrl'"),
                ("author_type", "type", "raw->'raw'->'author'->>'type'"),
                ("author_url", "url", "raw->'raw'->'author'->>'url'"),
                ("author_verified_type", "verifiedType", "raw->'raw'->'author'->>'verifiedType'"),
            ]
            for col, key, expr in author_scalar_updates:
                cur.execute(
                    f"""
                    UPDATE posts
                    SET {col} = {expr}
                    WHERE {col} IS NULL
                      AND raw IS NOT NULL
                      AND raw->'raw'->'author' ? %s
                    """,
                    (key,),
                )

            # --- Group 2: 6 author int counters ---
            for col, outer_key, inner_key in [
                ("author_followers_count", "followers", "followers"),
                ("author_following_count", "following", "following"),
                ("author_media_count", "mediaCount", "mediaCount"),
                ("author_statuses_count", "statusesCount", "statusesCount"),
                ("author_favourites_count", "favouritesCount", "favouritesCount"),
                ("author_fast_followers_count", "fastFollowersCount", "fastFollowersCount"),
            ]:
                cur.execute(
                    f"""
                    UPDATE posts
                    SET {col} = COALESCE(
                        (raw->'raw'->'author'->>%s)::int,
                        (raw->'raw'->'author'->>%s)::int
                    )
                    WHERE {col} IS NULL
                      AND raw IS NOT NULL
                      AND (
                        raw->'raw'->'author' ? %s
                        OR raw->'raw'->'author' ? %s
                      )
                    """,
                    (outer_key, inner_key, outer_key, inner_key),
                )

            # --- Group 3: 6 author bools ---
            for col, key, expr in [
                ("author_is_translator", "isTranslator",
                    "(raw->'raw'->'author'->>'isTranslator')::boolean"),
                ("author_is_automated", "isAutomated",
                    "(raw->'raw'->'author'->>'isAutomated')::boolean"),
                ("author_can_dm", "canDm",
                    "(raw->'raw'->'author'->>'canDm')::boolean"),
                ("author_can_media_tag", "canMediaTag",
                    "(raw->'raw'->'author'->>'canMediaTag')::boolean"),
                ("author_possibly_sensitive", "possiblySensitive",
                    "(raw->'raw'->'author'->>'possiblySensitive')::boolean"),
                ("author_has_custom_timelines", "hasCustomTimelines",
                    "(raw->'raw'->'author'->>'hasCustomTimelines')::boolean"),
            ]:
                cur.execute(
                    f"""
                    UPDATE posts
                    SET {col} = {expr}
                    WHERE {col} IS NULL
                      AND raw IS NOT NULL
                      AND raw->'raw'->'author' ? %s
                    """,
                    (key,),
                )

            # --- Group 4: view_count (outer camelCase only) ---
            cur.execute(
                """
                UPDATE posts
                SET view_count = COALESCE(
                    (raw->>'viewCount')::int,
                    (raw->'raw'->>'viewCount')::int
                )
                WHERE view_count IS NULL
                  AND raw IS NOT NULL
                  AND (
                    raw ? 'viewCount'
                    OR raw->'raw' ? 'viewCount'
                  )
                """
            )

            # --- Group 5: quoted_status_id (FK self-ref) ---
            # Alias outer table as p to avoid Postgres InitPlan hoisting
            # (verified fix from staging 2026-07-28).
            cur.execute(
                """
                UPDATE posts p
                SET quoted_status_id = CASE
                    WHEN EXISTS (
                        SELECT 1 FROM posts q
                        WHERE q.tweet_id = COALESCE(
                            p.raw->>'quoted_status_id',
                            p.raw->'raw'->'quoted_tweet'->>'id'
                        )
                    )
                    THEN COALESCE(
                        p.raw->>'quoted_status_id',
                        p.raw->'raw'->'quoted_tweet'->>'id'
                    )::text
                    ELSE NULL
                END
                WHERE p.raw IS NOT NULL
                  AND (
                    p.raw ? 'quoted_status_id'
                    OR p.raw->'raw'->'quoted_tweet' ? 'id'
                  )
                """
            )
    finally:
        connection.autocommit = old_autocommit


def _noop_reverse(apps, schema_editor):
    """Forward-only migration; no reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fix_posts_fks_on_delete_set_null"),
    ]

    operations = [
        migrations.RunPython(_backfill_in_chunks, _noop_reverse),
    ]