# Generated by Django 5.2.16 on 2026-07-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_posts_fks_on_delete_set_null'),
        ('core', '0007_brand_keyword_primary_purity'),
    ]

    operations = [
    ]
