# Generated by Django 5.2.16 on 2026-08-11 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

FLAG_KEYS = ("marketing_spam", "scam", "crypto", "unauthorized")


def seed_classifier_flag_keys(apps, schema_editor):
    flag_model = apps.get_model("core", "UnsanctionedFlagKey")
    for key in FLAG_KEYS:
        flag_model.objects.get_or_create(key=key)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_metrics_refreshed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestBacklogWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.TextField()),
                ('call_id', models.TextField()),
                ('call_kind', models.TextField()),
                ('bucket', models.TextField(blank=True, default='')),
                ('query_id', models.TextField()),
                ('original_since', models.DateTimeField()),
                ('original_until', models.DateTimeField()),
                ('remaining_since', models.DateTimeField()),
                ('remaining_until', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('quarantined', 'Quarantined'), ('waived', 'Waived')], default='pending', max_length=16)),
                ('reason_code', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('claim_owner', models.CharField(blank=True, default='', max_length=128)),
                ('claim_run_id', models.CharField(blank=True, default='', max_length=128)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_reason', models.CharField(blank=True, default='', max_length=128)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.CharField(blank=True, default='', max_length=128)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'harvest_backlog_windows',
                'indexes': [models.Index(fields=['brand_id', 'call_id', 'call_kind', 'bucket', 'query_id', 'state', 'remaining_since'], name='idx_hbw_call_state_since'), models.Index(fields=['state', 'next_attempt_at'], name='idx_hbw_state_due'), models.Index(fields=['claim_expires_at'], name='idx_hbw_claim_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_since__lt', models.F('original_until'))), name='ck_hbw_original_interval'), models.CheckConstraint(condition=models.Q(('remaining_since__lt', models.F('remaining_until'))), name='ck_hbw_remaining_interval'), models.CheckConstraint(condition=models.Q(('remaining_since__gte', models.F('original_since'))), name='ck_hbw_remaining_start'), models.CheckConstraint(condition=models.Q(('remaining_until__lte', models.F('original_until'))), name='ck_hbw_remaining_end'), models.UniqueConstraint(fields=('brand_id', 'call_id', 'call_kind', 'bucket', 'query_id', 'remaining_since', 'remaining_until'), name='uq_hbw_call_remaining')],
            },
        ),
        migrations.CreateModel(
            name='PostEnrichmentState',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enrichment_state', serialize=False, to='core.post')),
                ('translation_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('translation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('translation_first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('translation_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('translation_next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('translation_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('classification_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('classification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('classification_first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('classification_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('classification_next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('classification_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('claim_owner', models.CharField(blank=True, default='', max_length=128)),
                ('claim_run_id', models.CharField(blank=True, default='', max_length=128)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_enrichment_states',
                'indexes': [models.Index(fields=['translation_status', 'translation_next_attempt_at'], name='idx_pes_translation_due'), models.Index(fields=['classification_status', 'classification_next_attempt_at'], name='idx_pes_classify_due'), models.Index(fields=['claim_expires_at'], name='idx_pes_claim_expiry')],
            },
        ),
        migrations.CreateModel(
            name='TwitterListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_complete_reconciliation_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=32)),
                ('source_run_id', models.CharField(blank=True, default='', max_length=128)),
                ('account', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='twitter_list_memberships', to='core.account')),
            ],
            options={
                'db_table': 'twitter_list_memberships',
                'indexes': [models.Index(fields=['list_id', 'active'], name='idx_tlm_list_active')],
                'constraints': [models.UniqueConstraint(fields=('list_id', 'account'), name='uq_twitter_list_membership'), models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('first_seen_at'))), name='ck_tlm_seen_order'), models.CheckConstraint(condition=models.Q(('last_complete_reconciliation_at__isnull', True), ('last_complete_reconciliation_at__gte', models.F('first_seen_at')), _connector='OR'), name='ck_tlm_reconciled_order')],
            },
        ),
        migrations.RunPython(seed_classifier_flag_keys, migrations.RunPython.noop),
    ]
