# Generated by Django 5.2.16 on 2026-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_harvester_state_primitives'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterListSyncState',
            fields=[
                ('list_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('snapshot_id', models.CharField(max_length=128)),
                ('last_complete_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'twitter_list_sync_state',
            },
        ),
    ]
