# Generated by Django 5.2.16 on 2026-08-12 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_twitter_list_sync_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendNarrativeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cycle_id', models.CharField(max_length=128)),
                ('window_days', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('suppressed', 'Suppressed'), ('generating', 'Generating'), ('abandoned', 'Abandoned'), ('failed', 'Failed'), ('published', 'Published'), ('superseded', 'Superseded')], max_length=16)),
                ('semantic_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('publication_epoch', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('facts_as_of', models.DateTimeField()),
                ('generation_facts', models.JSONField(blank=True, null=True)),
                ('latest_checked_source_cycle_id', models.CharField(blank=True, default='', max_length=128)),
                ('latest_checked_as_of', models.DateTimeField(blank=True, null=True)),
                ('latest_checked_at', models.DateTimeField(blank=True, null=True)),
                ('latest_checked_facts', models.JSONField(blank=True, null=True)),
                ('narrative_type', models.CharField(blank=True, default='', max_length=32)),
                ('coverage_state', models.CharField(blank=True, default='', max_length=32)),
                ('primary_brand_key', models.CharField(blank=True, default='', max_length=64)),
                ('primary_brand_name_en', models.TextField(blank=True, default='')),
                ('primary_brand_name_zh_hans', models.TextField(blank=True, default='')),
                ('secondary_brand_key', models.CharField(blank=True, default='', max_length=64)),
                ('secondary_brand_name_en', models.TextField(blank=True, default='')),
                ('secondary_brand_name_zh_hans', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_zh_hans', models.TextField(blank=True, default='')),
                ('output_hash', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_host', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('call_slot_consumed', models.BooleanField(default=False)),
                ('claim_owner', models.CharField(blank=True, default='', max_length=128)),
                ('claim_fence', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('transport_started_at', models.DateTimeField(blank=True, null=True)),
                ('transport_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_brand', models.ForeignKey(blank=True, db_column='primary_brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.brand')),
                ('secondary_brand', models.ForeignKey(blank=True, db_column='secondary_brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.brand')),
            ],
            options={
                'db_table': 'trend_narrative_versions',
                'indexes': [models.Index(fields=['window_days', 'semantic_fingerprint'], name='idx_tnv_window_fingerprint'), models.Index(fields=['window_days', 'facts_as_of'], name='idx_tnv_window_facts'), models.Index(fields=['status', 'next_attempt_at'], name='idx_tnv_status_retry'), models.Index(fields=['window_days', '-created_at'], name='idx_tnv_window_created')],
                'constraints': [models.UniqueConstraint(fields=('source_cycle_id', 'window_days'), name='uq_tnv_source_window'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('window_days',), name='uq_tnv_current_window'), models.CheckConstraint(condition=models.Q(('window_days__in', [1, 7, 30, 365])), name='ck_tnv_window'), models.CheckConstraint(condition=models.Q(('status__in', ['checked', 'suppressed', 'generating', 'abandoned', 'failed', 'published', 'superseded'])), name='ck_tnv_status'), models.CheckConstraint(condition=models.Q(('is_current', False), ('status', 'published'), _connector='OR'), name='ck_tnv_current_published'), models.CheckConstraint(condition=models.Q(models.Q(('call_slot_consumed', False), ('status__in', ['checked', 'suppressed'])), models.Q(('call_slot_consumed', True), ('status__in', ['generating', 'abandoned', 'failed', 'published', 'superseded'])), _connector='OR'), name='ck_tnv_slot_status'), models.CheckConstraint(condition=models.Q(models.Q(('call_slot_consumed', False), ('claim_expires_at__isnull', True), ('claim_fence', 0), ('claim_owner', ''), ('claimed_at__isnull', True)), models.Q(('call_slot_consumed', True), ('claim_expires_at__isnull', False), ('claim_fence__gt', 0), ('claim_owner__gt', ''), ('claimed_at__isnull', False)), _connector='OR'), name='ck_tnv_claim_shape'), models.CheckConstraint(condition=models.Q(('claimed_at__isnull', True), ('claim_expires_at__gt', models.F('claimed_at')), _connector='OR'), name='ck_tnv_claim_order'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['failed', 'abandoned']), _negated=True), ('error_code__gt', ''), _connector='OR'), name='ck_tnv_terminal_error'), models.CheckConstraint(condition=models.Q(models.Q(('body_en__gt', ''), ('body_zh_hans__gt', ''), ('generated_at__isnull', False), ('output_hash__gt', ''), ('primary_brand_key__gt', ''), ('primary_brand_name_en__gt', ''), ('primary_brand_name_zh_hans__gt', ''), ('published_at__isnull', False), ('status__in', ['published', 'superseded'])), models.Q(('body_en', ''), ('body_zh_hans', ''), ('generated_at__isnull', True), ('output_hash', ''), ('published_at__isnull', True), ('status__in', ['checked', 'suppressed', 'generating', 'abandoned', 'failed'])), _connector='OR'), name='ck_tnv_output_shape'), models.CheckConstraint(condition=models.Q(('transport_started_at__isnull', True), models.Q(('call_slot_consumed', True), ('transport_started_at__gte', models.F('claimed_at'))), _connector='OR'), name='ck_tnv_transport_start'), models.CheckConstraint(condition=models.Q(('transport_completed_at__isnull', True), models.Q(('transport_completed_at__gte', models.F('transport_started_at')), ('transport_started_at__isnull', False)), _connector='OR'), name='ck_tnv_transport_finish'), models.CheckConstraint(condition=models.Q(('generated_at__isnull', True), models.Q(('generated_at__gte', models.F('transport_completed_at')), ('transport_completed_at__isnull', False)), _connector='OR'), name='ck_tnv_generated_order'), models.CheckConstraint(condition=models.Q(('published_at__isnull', True), ('published_at__gte', models.F('generated_at')), _connector='OR'), name='ck_tnv_published_order'), models.CheckConstraint(condition=models.Q(models.Q(('latest_checked_as_of__isnull', True), ('latest_checked_at__isnull', True), ('latest_checked_facts__isnull', True), ('latest_checked_source_cycle_id', '')), models.Q(('latest_checked_as_of__isnull', False), ('latest_checked_at__isnull', False), ('latest_checked_facts__isnull', False), ('latest_checked_source_cycle_id__gt', '')), _connector='OR'), name='ck_tnv_check_shape')],
            },
        ),
    ]
