# Generated by Django 5.2.16 on 2026-08-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_expand_trend_narrative'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('requested_since', models.DateTimeField()),
                ('requested_until', models.DateTimeField()),
                ('selection_mode', models.CharField(choices=[('explicit', 'Explicit range'), ('detected_gaps', 'Detected zero-coverage gaps')], max_length=24)),
                ('selection_params', models.JSONField(blank=True, default=dict)),
                ('selected_intervals', models.JSONField(blank=True, default=list)),
                ('brand_filter', models.JSONField(blank=True, default=list)),
                ('plan_signature', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backfill_jobs',
            },
        ),
        migrations.RemoveConstraint(
            model_name='harvestbacklogwindow',
            name='uq_hbw_call_remaining',
        ),
        migrations.AlterField(
            model_name='harvestbacklogwindow',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('quarantined', 'Quarantined'), ('waived', 'Waived'), ('completed', 'Completed')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='backfilljob',
            index=models.Index(fields=['state', 'created_at'], name='idx_bfj_state_created'),
        ),
        migrations.AddConstraint(
            model_name='backfilljob',
            constraint=models.CheckConstraint(condition=models.Q(('requested_since__lt', models.F('requested_until'))), name='ck_backfill_job_interval'),
        ),
        migrations.AddField(
            model_name='harvestbacklogwindow',
            name='backfill_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='core.backfilljob'),
        ),
        migrations.AddIndex(
            model_name='harvestbacklogwindow',
            index=models.Index(fields=['backfill_job', 'state', 'remaining_since'], name='idx_hbw_job_state_since'),
        ),
        migrations.AddConstraint(
            model_name='harvestbacklogwindow',
            constraint=models.UniqueConstraint(condition=models.Q(('backfill_job__isnull', True)), fields=('brand_id', 'call_id', 'call_kind', 'bucket', 'query_id', 'remaining_since', 'remaining_until'), name='uq_hbw_scheduled_remaining'),
        ),
        migrations.AddConstraint(
            model_name='harvestbacklogwindow',
            constraint=models.UniqueConstraint(condition=models.Q(('backfill_job__isnull', False)), fields=('backfill_job', 'brand_id', 'call_id', 'call_kind', 'bucket', 'query_id', 'remaining_since', 'remaining_until'), name='uq_hbw_job_remaining'),
        ),
    ]
