# Generated by Django 5.2.16 on 2026-08-19 06:38

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0014_expand_trend_narrative"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="post",
            index=models.Index(
                fields=["created_at"],
                include=("tweet_id", "author"),
                name="idx_posts_created_cover",
            ),
        ),
    ]
