# Generated by Django 5.2.16 on 2026-08-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_commentary_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendNarrativeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cycle_id', models.CharField(max_length=128)),
                ('window_days', models.PositiveSmallIntegerField()),
                ('facts_as_of', models.DateTimeField()),
                ('packet_schema_version', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('brand_manifest', models.JSONField(db_default=[], default=list)),
                ('batch_manifest', models.JSONField(db_default=[], default=list)),
                ('internal_order', models.JSONField(db_default=[], default=list)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('terminal', 'Terminal'), ('active', 'Active'), ('superseded', 'Superseded')], default='preparing', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trend_narrative_runs',
                'indexes': [models.Index(fields=['window_days', 'facts_as_of'], name='idx_tnr_window_facts'), models.Index(fields=['status', 'created_at'], name='idx_tnr_status_created')],
                'constraints': [models.UniqueConstraint(fields=('source_cycle_id', 'window_days'), name='uq_tnr_source_window'), models.CheckConstraint(condition=models.Q(('window_days__in', [1, 7, 30, 365])), name='ck_tnr_window'), models.CheckConstraint(condition=models.Q(('status__in', ['preparing', 'terminal', 'active', 'superseded'])), name='ck_tnr_status'), models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', False), ('status__in', ['active', 'superseded'])), models.Q(('activated_at__isnull', True), ('status__in', ['preparing', 'terminal'])), _connector='OR'), name='ck_tnr_activation_shape')],
            },
        ),
        migrations.CreateModel(
            name='TrendNarrativeProviderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('rank', 'Rank'), ('editor', 'Editor'), ('critic', 'Critic')], max_length=16)),
                ('batch_key', models.CharField(blank=True, default='', max_length=128)),
                ('request_identity', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('request_packet', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('reserved', 'Reserved'), ('sent', 'Sent'), ('completed', 'Completed'), ('ambiguous', 'Ambiguous'), ('failed', 'Failed')], default='reserved', max_length=16)),
                ('claim_owner', models.CharField(blank=True, default='', max_length=128)),
                ('claim_fence', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_calls', to='core.trendnarrativerun')),
            ],
            options={
                'db_table': 'trend_narrative_provider_calls',
                'indexes': [models.Index(fields=['state', 'claim_expires_at'], name='idx_tnpc_claim_due'), models.Index(fields=['run', 'stage'], name='idx_tnpc_run_stage')],
                'constraints': [models.UniqueConstraint(fields=('run', 'stage', 'batch_key'), name='uq_tnpc_run_stage_batch'), models.UniqueConstraint(fields=('request_identity',), name='uq_tnpc_request_identity'), models.CheckConstraint(condition=models.Q(('stage__in', ['rank', 'editor', 'critic'])), name='ck_tnpc_stage'), models.CheckConstraint(condition=models.Q(('state__in', ['reserved', 'sent', 'completed', 'ambiguous', 'failed'])), name='ck_tnpc_state'), models.CheckConstraint(condition=models.Q(models.Q(('claim_expires_at__isnull', True), ('claim_fence', 0), ('claim_owner', ''), ('claimed_at__isnull', True)), models.Q(('claim_expires_at__gt', models.F('claimed_at')), ('claim_fence__gt', 0), ('claim_owner__gt', ''), ('claimed_at__isnull', False)), _connector='OR'), name='ck_tnpc_claim_shape'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('state', 'reserved')), models.Q(('sent_at__isnull', False), ('state__in', ['sent', 'completed', 'ambiguous', 'failed'])), _connector='OR'), name='ck_tnpc_sent_shape'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('state__in', ['reserved', 'sent', 'ambiguous', 'failed'])), models.Q(('completed_at__isnull', False), ('response_hash__gt', ''), ('state', 'completed')), _connector='OR'), name='ck_tnpc_completed_shape')],
            },
        ),
        migrations.CreateModel(
            name='BrandTrendNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key_snapshot', models.CharField(max_length=64)),
                ('brand_name_en_snapshot', models.TextField()),
                ('brand_name_zh_cn_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('approved', 'Approved'), ('held', 'Held'), ('unavailable', 'Unavailable'), ('no_content', 'No content'), ('data_quality_unavailable', 'Data quality unavailable')], max_length=32)),
                ('headline_en', models.TextField(blank=True, default='')),
                ('headline_zh_cn', models.TextField(blank=True, default='')),
                ('secondary_en', models.TextField(blank=True, default='')),
                ('secondary_zh_cn', models.TextField(blank=True, default='')),
                ('critic_decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('repair', 'Repair'), ('hold', 'Hold')], default='', max_length=16)),
                ('narrative_kind', models.CharField(blank=True, choices=[('event_led', 'Event led'), ('content_shift', 'Content shift'), ('mix_shift', 'Mix shift'), ('quiet_context', 'Quiet context')], default='', max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=16)),
                ('propositions', models.JSONField(db_default=[], default=list)),
                ('events', models.JSONField(db_default=[], default=list)),
                ('cited_fact_ids', models.JSONField(db_default=[], default=list)),
                ('cited_evidence_ids', models.JSONField(db_default=[], default=list)),
                ('selected_evidence_packet', models.JSONField(blank=True, null=True)),
                ('final_critic_payload', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.brand')),
                ('last_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_successors', to='core.brandtrendnarrative')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_narratives', to='core.trendnarrativerun')),
            ],
            options={
                'db_table': 'brand_trend_narratives',
                'indexes': [models.Index(fields=['brand_key_snapshot', '-attempted_at'], name='idx_btn_brand_attempt'), models.Index(fields=['run', 'status'], name='idx_btn_run_status')],
                'constraints': [models.UniqueConstraint(fields=('run', 'brand_key_snapshot'), name='uq_btn_run_brand'), models.CheckConstraint(condition=models.Q(('status__in', ['prepared', 'approved', 'held', 'unavailable', 'no_content', 'data_quality_unavailable'])), name='ck_btn_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'prepared'), ('verified_at__isnull', True)), models.Q(('headline_en__gt', ''), ('headline_zh_cn__gt', ''), ('secondary_en__gt', ''), ('secondary_zh_cn__gt', ''), ('status', 'approved'), ('verified_at__isnull', False)), ('status__in', ['held', 'unavailable', 'no_content', 'data_quality_unavailable']), _connector='OR'), name='ck_btn_output_shape'), models.CheckConstraint(condition=models.Q(models.Q(('last_good__isnull', False), ('status', 'held')), models.Q(('status', 'held'), _negated=True), _connector='OR'), name='ck_btn_held_last_good'), models.CheckConstraint(condition=models.Q(('critic_decision__in', ['', 'approve', 'repair', 'hold'])), name='ck_btn_critic_decision'), models.CheckConstraint(condition=models.Q(('narrative_kind__in', ['', 'event_led', 'content_shift', 'mix_shift', 'quiet_context'])), name='ck_btn_narrative_kind'), models.CheckConstraint(condition=models.Q(('confidence__in', ['', 'high', 'medium', 'low'])), name='ck_btn_confidence')],
            },
        ),
        migrations.CreateModel(
            name='TrendNarrativeVisibleRun',
            fields=[
                ('window_days', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('facts_as_of', models.DateTimeField()),
                ('activated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visible_pointers', to='core.trendnarrativerun')),
            ],
            options={
                'db_table': 'trend_narrative_visible_runs',
                'constraints': [models.CheckConstraint(condition=models.Q(('window_days__in', [1, 7, 30, 365])), name='ck_tnvr_window')],
            },
        ),
    ]
