# Generated by Django 5.2.16 on 2026-08-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_per_brand_trend_narratives"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendNarrativeWorkSlot",
            fields=[
                (
                    "window_days",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "active_source_cycle_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("active_facts_as_of", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot_claim_owner",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("snapshot_claim_fence", models.PositiveIntegerField(default=0)),
                ("snapshot_claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot_claim_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "queued_source_cycle_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("queued_facts_as_of", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trend_narrative_work_slots",
            },
        ),
        migrations.RemoveConstraint(
            model_name="trendnarrativerun",
            name="ck_tnr_status",
        ),
        migrations.RemoveConstraint(
            model_name="trendnarrativerun",
            name="ck_tnr_activation_shape",
        ),
        migrations.AddField(
            model_name="trendnarrativerun",
            name="suspension_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="trendnarrativerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Preparing"),
                    ("suspended", "Suspended"),
                    ("terminal", "Terminal"),
                    ("active", "Active"),
                    ("superseded", "Superseded"),
                ],
                default="preparing",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["preparing", "suspended", "terminal", "active", "superseded"],
                    )
                ),
                name="ck_tnr_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", False),
                        ("status__in", ["active", "superseded"]),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("status__in", ["preparing", "suspended", "terminal"]),
                    ),
                    _connector="OR",
                ),
                name="ck_tnr_activation_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "suspended"), ("suspension_reason__gt", "")),
                    models.Q(("status", "suspended"), _negated=True),
                    _connector="OR",
                ),
                name="ck_tnr_suspension_reason",
            ),
        ),
        migrations.AddField(
            model_name="trendnarrativeworkslot",
            name="active_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_slots",
                to="core.trendnarrativerun",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativeworkslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_days__in", [1, 7, 30, 365])),
                name="ck_tnws_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativeworkslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active_facts_as_of__isnull", True),
                        ("active_run__isnull", True),
                        ("active_source_cycle_id", ""),
                        ("snapshot_claim_expires_at__isnull", True),
                        ("snapshot_claim_fence", 0),
                        ("snapshot_claim_owner", ""),
                        ("snapshot_claimed_at__isnull", True),
                    ),
                    models.Q(
                        ("active_facts_as_of__isnull", False),
                        ("active_source_cycle_id__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="ck_tnws_active_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativeworkslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("snapshot_claim_expires_at__isnull", True),
                        ("snapshot_claim_fence", 0),
                        ("snapshot_claim_owner", ""),
                        ("snapshot_claimed_at__isnull", True),
                    ),
                    models.Q(
                        (
                            "snapshot_claim_expires_at__gt",
                            models.F("snapshot_claimed_at"),
                        ),
                        ("snapshot_claim_fence__gt", 0),
                        ("snapshot_claim_owner__gt", ""),
                        ("snapshot_claimed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_tnws_snapshot_claim",
            ),
        ),
        migrations.AddConstraint(
            model_name="trendnarrativeworkslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("queued_facts_as_of__isnull", True),
                        ("queued_source_cycle_id", ""),
                    ),
                    models.Q(
                        ("queued_facts_as_of__isnull", False),
                        ("queued_source_cycle_id__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="ck_tnws_queued_shape",
            ),
        ),
    ]
