# Generated by Django 5.2.16 on 2026-08-29 14:20
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_guard_per_brand_narrative_reverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_based_in",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="account_based_in_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_badge_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_url_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_user_label_display_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_label_user_label_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="affiliate_username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_badge_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_url_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_user_label_display_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_user_label_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="learn_more_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="location_accurate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="protected",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="source",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="username_changes_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
