# Generated by Django 5.2.16 on 2026-08-29 21:16
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_account_account_based_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_country_accurate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="username_changes_last_changed_at_msec",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="verification_info_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="verification_info_is_identity_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
