# Generated by Django 5.2.16 on 2026-08-30
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_account_user_about_live_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="verification_info_reason_verified_since_msec",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
