# Generated by Django 5.2.16 on 2026-08-30
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_account_verification_reason_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="unavailable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="unavailable_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
