# Generated by Django 5.2.16 on 2026-08-31 01:20

# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_account_user_about_unavailable"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="identity_profile_label_long_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
