# Generated by Django 5.2.16 on 2026-08-31 04:38

# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_account_identity_profile_label_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="verification_info_reason_override_verified_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
