# Generated by Django 5.2.16 on 2026-09-01

# ruff: noqa: RUF012

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SEED_RELATIVE_PATH = Path("monitor/data/account_geography.json")
SEED_SHA256 = "af7531a0489864fad81b3510ad27d4165cb54ec533a5d579257a8f4820b4d936"


def _load_seed() -> dict:
    seed_path = Path(settings.BASE_DIR) / SEED_RELATIVE_PATH
    seed_bytes = seed_path.read_bytes()
    digest = hashlib.sha256(seed_bytes).hexdigest()
    if digest != SEED_SHA256:
        raise RuntimeError(
            f"account geography seed digest mismatch: expected {SEED_SHA256}, got {digest}"
        )
    return json.loads(seed_bytes)


def seed_account_geography(apps, schema_editor) -> None:
    payload = _load_seed()
    if payload.get("schema_version") != 1:
        raise RuntimeError("unsupported account geography seed schema")

    Region = apps.get_model("core", "Region")
    RegionLabel = apps.get_model("core", "RegionLabel")
    Country = apps.get_model("core", "Country")
    CountryLabel = apps.get_model("core", "CountryLabel")
    CountryRegion = apps.get_model("core", "CountryRegion")
    AccountBasedInMapping = apps.get_model("core", "AccountBasedInMapping")

    regions = payload["regions"]
    countries = payload["countries"]
    mappings = payload["account_based_in_mappings"]
    if len(countries) != 249:
        raise RuntimeError("account geography seed must contain 249 countries")

    Region.objects.bulk_create(
        [
            Region(
                key=item["key"],
                m49_code=item["m49_code"],
                source=item["source"],
                level=item["level"],
            )
            for item in regions
        ]
    )
    for item in regions:
        if item["parent"] is not None:
            Region.objects.filter(pk=item["key"]).update(parent_id=item["parent"])
    RegionLabel.objects.bulk_create(
        [
            RegionLabel(region_id=item["key"], lang=lang, label=label)
            for item in regions
            for lang, label in item["labels"].items()
        ]
    )

    Country.objects.bulk_create(
        [Country(code=item["code"], m49_code=item["m49_code"]) for item in countries]
    )
    for item in countries:
        if item["display_parent_country"] is not None:
            Country.objects.filter(pk=item["code"]).update(
                display_parent_country_id=item["display_parent_country"],
                display_parent_relationship_type=item[
                    "display_parent_relationship_type"
                ],
            )
    CountryLabel.objects.bulk_create(
        [
            CountryLabel(country_id=item["code"], lang=lang, label=label)
            for item in countries
            for lang, label in item["labels"].items()
        ]
    )
    CountryRegion.objects.bulk_create(
        [
            CountryRegion(
                country_id=item["code"],
                region_id=item["region_key"],
                source="owner-reviewed" if item["code"] == "TW" else "un-m49",
            )
            for item in countries
        ]
    )
    AccountBasedInMapping.objects.bulk_create(
        [
            AccountBasedInMapping(
                value=item["value"],
                country_id=item["country_code"],
                region_id=item["region_key"],
                review_note=item["review_note"],
            )
            for item in mappings
        ]
    )

    expected = {
        "regions": len(regions),
        "region_labels": len(regions) * 2,
        "countries": 249,
        "country_labels": 498,
        "country_regions": 249,
        "account_based_in_mappings": len(mappings),
    }
    actual = {
        "regions": Region.objects.count(),
        "region_labels": RegionLabel.objects.count(),
        "countries": Country.objects.count(),
        "country_labels": CountryLabel.objects.count(),
        "country_regions": CountryRegion.objects.count(),
        "account_based_in_mappings": AccountBasedInMapping.objects.count(),
    }
    if actual != expected:
        raise RuntimeError(f"account geography seed count mismatch: {actual!r}")


def unseed_account_geography(apps, schema_editor) -> None:
    apps.get_model("core", "AccountBasedInMapping").objects.all().delete()
    apps.get_model("core", "CountryRegion").objects.all().delete()
    apps.get_model("core", "CountryLabel").objects.all().delete()
    apps.get_model("core", "RegionLabel").objects.all().delete()
    Country = apps.get_model("core", "Country")
    Region = apps.get_model("core", "Region")
    Country.objects.update(
        display_parent_country_id=None,
        display_parent_relationship_type=None,
    )
    Region.objects.update(parent_id=None)
    Country.objects.all().delete()
    Region.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [("core", "0025_account_verification_override_year")]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "m49_code",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
                ("source", models.CharField(max_length=64)),
                ("level", models.CharField(max_length=32)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.region",
                    ),
                ),
            ],
            options={"db_table": "regions", "ordering": ["key"]},
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("m49_code", models.CharField(max_length=3, unique=True)),
                (
                    "display_parent_relationship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "special_administrative_region",
                                "Special administrative region",
                            ),
                            ("owner_display_context", "Owner-selected display context"),
                            ("us_insular_area", "US insular area"),
                            ("french_overseas", "French overseas arrangement"),
                            (
                                "british_overseas_territory",
                                "British Overseas Territory",
                            ),
                            ("crown_dependency", "Crown Dependency"),
                            (
                                "kingdom_constituent_country",
                                "Kingdom constituent country",
                            ),
                            ("netherlands_public_body", "Netherlands public body"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "display_parent_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="display_children",
                        to="core.country",
                    ),
                ),
            ],
            options={"db_table": "countries", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="RegionLabel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "region",
                        "lang",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lang", models.CharField(max_length=16)),
                ("label", models.TextField()),
                (
                    "region",
                    models.ForeignKey(
                        db_column="region_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="core.region",
                    ),
                ),
            ],
            options={"db_table": "region_labels"},
        ),
        migrations.CreateModel(
            name="CountryLabel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "country",
                        "lang",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lang", models.CharField(max_length=16)),
                ("label", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="core.country",
                    ),
                ),
            ],
            options={"db_table": "country_labels"},
        ),
        migrations.CreateModel(
            name="CountryRegion",
            fields=[
                (
                    "country",
                    models.OneToOneField(
                        db_column="country_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="region_mapping",
                        serialize=False,
                        to="core.country",
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                (
                    "region",
                    models.ForeignKey(
                        db_column="region_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_mappings",
                        to="core.region",
                    ),
                ),
            ],
            options={"db_table": "country_codes_region"},
        ),
        migrations.CreateModel(
            name="AccountBasedInMapping",
            fields=[
                ("value", models.TextField(primary_key=True, serialize=False)),
                ("review_note", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country_code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="core.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_key",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="core.region",
                    ),
                ),
            ],
            options={"db_table": "account_based_in_mappings"},
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        display_parent_country__isnull=True,
                        display_parent_relationship_type__isnull=True,
                    ),
                    models.Q(
                        display_parent_country__isnull=False,
                        display_parent_relationship_type__isnull=False,
                    ),
                    _connector="OR",
                ),
                name="ck_countries_display_parent_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_parent_country__isnull", True),
                    ~models.Q(display_parent_country=models.F("code")),
                    _connector="OR",
                ),
                name="ck_countries_not_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("display_parent_relationship_type__isnull", True),
                    (
                        "display_parent_relationship_type__in",
                        (
                            "special_administrative_region",
                            "owner_display_context",
                            "us_insular_area",
                            "french_overseas",
                            "british_overseas_territory",
                            "crown_dependency",
                            "kingdom_constituent_country",
                            "netherlands_public_body",
                        ),
                    ),
                    _connector="OR",
                ),
                name="ck_countries_parent_relationship_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    ~models.Q(parent=models.F("key")),
                    _connector="OR",
                ),
                name="ck_regions_not_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbasedinmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(country__isnull=False, region__isnull=True),
                    models.Q(country__isnull=True, region__isnull=False),
                    _connector="OR",
                ),
                name="ck_account_based_in_mapping_one_target",
            ),
        ),
        migrations.RunPython(
            seed_account_geography,
            unseed_account_geography,
            atomic=True,
        ),
        migrations.AddField(
            model_name="account",
            name="based_in_region",
            field=models.ForeignKey(
                blank=True,
                db_column="based_in_region_key",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="core.region",
            ),
        ),
    ]
