# Generated by Django 5.2.16 on 2026-09-01

# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


def preflight_country_codes(apps, schema_editor) -> None:
    Account = apps.get_model("core", "Account")
    Country = apps.get_model("core", "Country")
    existing_codes = set(
        Account.objects.exclude(country_code__isnull=True)
        .values_list("country_code", flat=True)
        .distinct()
    )
    seeded_codes = set(Country.objects.values_list("code", flat=True))
    residue = sorted(existing_codes - seeded_codes)
    if residue:
        raise RuntimeError(f"accounts contain unsupported country codes: {residue!r}")


class Migration(migrations.Migration):
    dependencies = [("core", "0026_account_geography_taxonomy")]

    operations = [
        migrations.RunPython(preflight_country_codes, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE accounts
                        ADD CONSTRAINT fk_accounts_country_code
                        FOREIGN KEY (country_code) REFERENCES countries(code)
                        DEFERRABLE INITIALLY DEFERRED NOT VALID;
                        ALTER TABLE accounts
                        VALIDATE CONSTRAINT fk_accounts_country_code;
                        ALTER TABLE accounts
                        ADD CONSTRAINT ck_accounts_one_geography_target
                        CHECK (country_code IS NULL OR based_in_region_key IS NULL)
                        NOT VALID;
                        ALTER TABLE accounts
                        VALIDATE CONSTRAINT ck_accounts_one_geography_target;
                    """,
                    reverse_sql="""
                        ALTER TABLE accounts
                        DROP CONSTRAINT IF EXISTS ck_accounts_one_geography_target;
                        ALTER TABLE accounts
                        DROP CONSTRAINT IF EXISTS fk_accounts_country_code;
                    """,
                )
            ],
            state_operations=[
                migrations.RemoveField(model_name="account", name="country_code"),
                migrations.AddField(
                    model_name="account",
                    name="country",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="country_code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="core.country",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("country__isnull", True),
                            ("based_in_region__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_accounts_one_geography_target",
                    ),
                ),
            ],
        ),
    ]
