# Generated by Django 5.2.16 on 2026-09-08

# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models

POST_TYPES = {
    "buzz_releases": ("Releases & Updates", "发布与更新"),
    "hands_on_usage": ("Hands-On Usage", "实际使用"),
    "performance_comparisons": ("Results and Evaluations", "结果与评测"),
    "feedback_questions": ("Questions & Requests", "问题与请求"),
    "advertising_marketing": ("Advertising & Marketing", "广告营销"),
    "event_announcement": ("Events & Opportunities", "活动与机会"),
    "opinions_reactions": ("Opinions & Reactions", "观点与反应"),
    "research_explanations": ("Research & Explanations", "研究与解释"),
    "business_finance": ("Business & Finance", "商业与金融"),
    "other": ("Other", "其他"),
}
PRODUCT_LABELS = {
    "bug": ("Bug", "缺陷"),
    "complaint": ("Complaint", "投诉"),
    "testimonial": ("Testimonial", "推荐评价"),
    "product_request": ("Ideas & requests", "想法与请求"),
    "misinformation": ("Misinformation", "可能误导的信息"),
}


def seed_stage1_taxonomy(apps, schema_editor):
    PostTypeKey = apps.get_model("core", "PostTypeKey")
    PostTypeLabel = apps.get_model("core", "PostTypeLabel")
    ProductLabelKey = apps.get_model("core", "ProductLabelKey")
    ProductLabelLabel = apps.get_model("core", "ProductLabelLabel")
    for key, (en, zh_cn) in POST_TYPES.items():
        PostTypeKey.objects.get_or_create(key=key)
        for lang, label in (("en", en), ("zh-cn", zh_cn)):
            PostTypeLabel.objects.update_or_create(
                post_type_id=key, lang=lang, defaults={"label": label}
            )
    for key, (en, zh_cn) in PRODUCT_LABELS.items():
        ProductLabelKey.objects.get_or_create(key=key)
        for lang, label in (("en", en), ("zh-cn", zh_cn)):
            ProductLabelLabel.objects.update_or_create(
                product_label_id=key, lang=lang, defaults={"label": label}
            )


class Migration(migrations.Migration):
    dependencies = [("core", "0027_account_country_foreign_key")]

    operations = [
        migrations.CreateModel(
            name="ProductLabelKey",
            fields=[
                (
                    "key",
                    models.CharField(
                        db_collation="case_insensitive",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "product_label_keys", "ordering": ["key"]},
        ),
        migrations.CreateModel(
            name="ProductLabelLabel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "product_label",
                        "lang",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lang", models.TextField()),
                ("label", models.TextField()),
                (
                    "product_label",
                    models.ForeignKey(
                        db_column="key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="core.productlabelkey",
                    ),
                ),
            ],
            options={"db_table": "product_label_labels"},
        ),
        migrations.CreateModel(
            name="PostBrandClassificationState",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "brand",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_version", models.CharField(max_length=64)),
                ("taxonomy_version", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=256)),
                (
                    "source_language",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("input_context_fingerprint", models.CharField(max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("classified", "Classified"),
                            ("context_missing", "Context missing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("classified_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        db_column="brand_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.brand",
                    ),
                ),
                (
                    "china_nationalism",
                    models.ForeignKey(
                        blank=True,
                        db_column="china_nationalism",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.nationalismkey",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_states",
                        to="core.post",
                    ),
                ),
                (
                    "sentiment",
                    models.ForeignKey(
                        blank=True,
                        db_column="sentiment",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.sentimentkey",
                    ),
                ),
                (
                    "us_nationalism",
                    models.ForeignKey(
                        blank=True,
                        db_column="us_nationalism",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.nationalismkey",
                    ),
                ),
            ],
            options={
                "db_table": "posts_brands_classification_states",
                "indexes": [
                    models.Index(
                        fields=["brand", "outcome"],
                        name="idx_pb_cls_state_brand_outcome",
                    ),
                    models.Index(
                        fields=["contract_version"], name="idx_pb_cls_state_contract"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostBrandProductLabel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "brand",
                        "product_label",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        db_column="brand_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.brand",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_label_edges",
                        to="core.post",
                    ),
                ),
                (
                    "product_label",
                    models.ForeignKey(
                        db_column="product_label_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.productlabelkey",
                    ),
                ),
            ],
            options={
                "db_table": "posts_brands_product_labels",
                "indexes": [
                    models.Index(
                        fields=["brand", "product_label"],
                        name="idx_pb_product_brand_label",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_stage1_taxonomy, migrations.RunPython.noop),
    ]
