# Generated by Django 5.2.16 on 2026-09-09

from django.db import migrations

POST_TYPES = {
    "releases_updates": ("Releases & Updates", "发布与更新", "リリース・アップデート"),
    "hands_on_usage": ("Hands-On Usage", "实际使用", "使用体験"),
    "results_evaluations": ("Results and Evaluations", "结果与评测", "結果・評価"),
    "questions_requests": ("Questions & Requests", "问题与请求", "質問・要望"),
    "advertising_marketing": ("Advertising & Marketing", "广告营销", "広告・マーケティング"),
    "events_opportunities": ("Events & Opportunities", "活动与机会", "イベント・機会"),
    "opinions_reactions": ("Opinions & Reactions", "观点与反应", "意見・反応"),
    "research_explanations": ("Research & Explanations", "研究与解释", "研究・解説"),
    "business_finance": ("Business & Finance", "商业与金融", "ビジネス・金融"),
    "other": ("Other", "其他", "その他"),
}
PRODUCT_LABELS = {
    "bug": ("Bug", "缺陷", "バグ"),
    "complaint": ("Complaint", "投诉", "苦情"),
    "testimonial": ("Testimonial", "推荐评价", "推奨の声"),
    "ideas_requests": ("Ideas & requests", "想法与请求", "アイデア・要望"),
    "misinformation": ("Misinformation", "可能误导的信息", "誤情報の可能性"),
}
SENTIMENTS = {
    "positive": ("Positive", "正面", "ポジティブ"),
    "negative": ("Negative", "负面", "ネガティブ"),
    "neutral": ("Neutral", "中性", "中立"),
    "mixed": ("Mixed", "混合", "賛否混在"),
}
NATIONALISMS = {
    "none": ("None", "无", "なし"),
    "mild_pro": ("Mild Pro", "温和支持", "控えめな支持"),
    "pro": ("Pro", "支持", "支持"),
    "constructive_critical": ("Constructive Critical", "建设性批评", "建設的な批判"),
    "anti": ("Anti", "反对", "反対"),
    "mixed": ("Mixed", "混合", "賛否混在"),
}
LOCALES = ("en", "zh-cn", "ja")


def seed_taxonomy_v2_labels(apps, schema_editor):
    families = (
        ("PostTypeKey", "PostTypeLabel", "post_type_id", POST_TYPES),
        ("ProductLabelKey", "ProductLabelLabel", "product_label_id", PRODUCT_LABELS),
        ("SentimentKey", "SentimentLabel", "sentiment_id", SENTIMENTS),
        ("NationalismKey", "NationalismLabel", "nationalism_id", NATIONALISMS),
    )
    for key_model_name, label_model_name, foreign_key, values in families:
        KeyModel = apps.get_model("core", key_model_name)
        LabelModel = apps.get_model("core", label_model_name)
        for key, labels in values.items():
            KeyModel.objects.get_or_create(key=key)
            for lang, label in zip(LOCALES, labels, strict=True):
                LabelModel.objects.update_or_create(
                    **{foreign_key: key, "lang": lang}, defaults={"label": label}
                )


class Migration(migrations.Migration):
    dependencies = [("core", "0028_ai_enrichment_stage1_taxonomy")]

    operations = [
        migrations.RunPython(seed_taxonomy_v2_labels, migrations.RunPython.noop),
    ]
