# Generated by Django 5.2.16 on 2026-09-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_stage1c_frontier_organization_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetedExtractionState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('content_identity', models.CharField(max_length=64)),
                ('model', models.TextField()),
                ('prompt_version', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='targeted_extraction_states', to='core.post')),
            ],
            options={
                'db_table': 'targeted_extraction_states',
            },
        ),
        migrations.CreateModel(
            name='TargetedExtractionAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_identity', models.CharField(max_length=64, unique=True)),
                ('attempted_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('model', models.TextField()),
                ('prompt_version', models.CharField(max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_events', to='core.targetedextractionstate')),
            ],
            options={
                'db_table': 'targeted_extraction_attempts',
                'ordering': ['attempted_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='targetedextractionstate',
            index=models.Index(fields=['status', 'role'], name='idx_target_extract_due'),
        ),
        migrations.AddConstraint(
            model_name='targetedextractionstate',
            constraint=models.UniqueConstraint(fields=('post', 'role'), name='uq_target_extract_post_role'),
        ),
    ]
