# Generated by Django 5.2.16 on 2026-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_stage1c_targeted_extraction_state"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="branddiscoverycandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_brand_candidate_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "attendance_mode__in",
                        ["in_person", "online_live", "hybrid", "unknown"],
                    )
                ),
                name="ck_events_attendance_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_status__in",
                        [
                            "scheduled",
                            "live",
                            "completed",
                            "cancelled",
                            "postponed",
                            "unknown",
                        ],
                    )
                ),
                name="ck_events_source_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_events_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__isnull", True),
                    models.Q(
                        ("extraction_confidence__gte", 0.0),
                        ("extraction_confidence__lte", 1.0),
                    ),
                    _connector="OR",
                ),
                name="ck_events_extraction_conf",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobdiscoveryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "planned",
                            "running",
                            "completed",
                            "failed",
                            "truncated",
                            "blocked",
                        ],
                    )
                ),
                name="ck_job_runs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("brand__isnull", False),
                        ("brand_discovery_candidate__isnull", True),
                    ),
                    models.Q(
                        ("brand__isnull", True),
                        ("brand_discovery_candidate__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_jobs_one_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "application_route_kind__in",
                        [
                            "direct_url",
                            "careers_page",
                            "email",
                            "qr",
                            "direct_message",
                            "other",
                            "unresolved",
                        ],
                    )
                ),
                name="ck_jobs_application_route",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblisting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "closed", "future", "unknown"])
                ),
                name="ck_jobs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblistingevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_relationship__in", ["official", "staff", "third_party"])
                ),
                name="ck_job_evidence_relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="joblistingevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "extraction_method__in",
                        ["structured_text", "ocr", "vision", "manual"],
                    )
                ),
                name="ck_job_evidence_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "opportunity_type__in",
                        [
                            "giveaway",
                            "discount",
                            "free_credits",
                            "beta_access",
                            "grant",
                            "bounty",
                            "contest",
                            "referral",
                            "collaboration",
                            "other",
                        ],
                    )
                ),
                name="ck_opportunities_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_status__in",
                        ["upcoming", "open", "closed", "cancelled", "unknown"],
                    )
                ),
                name="ck_opportunities_source_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_opportunities_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__isnull", True),
                    models.Q(
                        ("extraction_confidence__gte", 0.0),
                        ("extraction_confidence__lte", 1.0),
                    ),
                    _connector="OR",
                ),
                name="ck_opportunities_extraction_conf",
            ),
        ),
        migrations.AddConstraint(
            model_name="personaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "resolution_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_people_accounts_resolution",
            ),
        ),
        migrations.AddConstraint(
            model_name="personbrandaffiliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "affiliation_type__in",
                        [
                            "employment",
                            "founder",
                            "advisor",
                            "board_member",
                            "contractor",
                            "ambassador",
                            "creator_partner",
                            "affiliate",
                            "investor",
                            "community",
                            "other",
                        ],
                    )
                ),
                name="ck_pba_affiliation_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="personbrandaffiliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["current", "former", "future", "unknown"])
                ),
                name="ck_pba_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="personbrandaffiliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_pba_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="personbrandaffiliationevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "review_status__in",
                        ["pending", "confirmed", "rejected", "needs_review"],
                    )
                ),
                name="ck_pbae_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="personneldiscoveryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "planned",
                            "running",
                            "completed",
                            "failed",
                            "truncated",
                            "blocked",
                        ],
                    )
                ),
                name="ck_personnel_runs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetedextractionstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "succeeded", "failed"])),
                name="ck_target_extract_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetedextractionstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        [
                            "event_extraction",
                            "opportunity_extraction",
                            "job_listing_extraction",
                            "personnel_change_extraction",
                            "profile_affiliation_extraction",
                        ],
                    )
                ),
                name="ck_target_extract_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetedextractionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome__in", ["succeeded", "failed"])),
                name="ck_target_attempt_outcome",
            ),
        ),
    ]
