# Generated by Django 5.2.16 on 2026-09-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_stage1c_intelligence_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salary_min__isnull', True), ('salary_min__gte', 0), _connector='OR'), models.Q(('salary_max__isnull', True), ('salary_max__gte', 0), _connector='OR')), name='ck_jobs_salary_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(condition=models.Q(('campaign_openings__isnull', True), ('campaign_openings__gte', 1), _connector='OR'), name='ck_jobs_campaign_openings'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(condition=models.Q(('role_openings__isnull', True), ('role_openings__gte', 1), _connector='OR'), name='ck_jobs_role_openings'),
        ),
        migrations.AddConstraint(
            model_name='personbrandaffiliation',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), models.Q(('start_date_precision', models.F('end_date_precision')), _negated=True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='ck_pba_comparable_dates'),
        ),
    ]
