# Generated by Django 5.2.16 on 2026-09-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_joblisting_ck_jobs_salary_nonnegative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendNarrativeDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.PositiveSmallIntegerField()),
                ('target_contract_version', models.CharField(max_length=64)),
                ('target_prompt_version', models.CharField(max_length=255)),
                ('target_model', models.CharField(max_length=128)),
                ('demand_reason', models.CharField(choices=[('visible', 'Visible'), ('prewarm', 'Prewarm'), ('operator', 'Operator')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('last_enqueued_request_count', models.PositiveIntegerField(default=0)),
                ('operator_request_count', models.PositiveIntegerField(default=0)),
                ('last_enqueued_operator_request_count', models.PositiveIntegerField(default=0)),
                ('first_requested_at', models.DateTimeField()),
                ('last_requested_at', models.DateTimeField()),
                ('hot_until', models.DateTimeField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_material_input_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('last_satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('last_decision_reason', models.CharField(blank=True, default='', max_length=64)),
                ('suppression_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('satisfied', 'Satisfied'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trend_narrative_demands',
            },
        ),
        migrations.AddField(
            model_name='brandtrendnarrative',
            name='critic_audit_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandtrendnarrative',
            name='critic_reason_codes',
            field=models.JSONField(db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='brandtrendnarrative',
            name='critic_review_state',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='brandtrendnarrative',
            constraint=models.CheckConstraint(condition=models.Q(('critic_review_state__in', ['', 'bypassed', 'reviewed'])), name='ck_btn_critic_review_state'),
        ),
        migrations.AddField(
            model_name='trendnarrativedemand',
            name='brand',
            field=models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='trend_narrative_demands', to='core.brand'),
        ),
        migrations.AddIndex(
            model_name='trendnarrativedemand',
            index=models.Index(fields=['window_days', 'state', 'hot_until'], name='idx_tnd_window_due'),
        ),
        migrations.AddIndex(
            model_name='trendnarrativedemand',
            index=models.Index(fields=['state', '-priority'], name='idx_tnd_state_priority'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.UniqueConstraint(fields=('brand', 'window_days'), name='uq_tnd_brand_window'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('window_days__in', [1, 7, 30, 365])), name='ck_tnd_window'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 100)), name='ck_tnd_priority'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('last_requested_at__gte', models.F('first_requested_at'))), name='ck_tnd_request_order'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('hot_until__gte', models.F('last_requested_at'))), name='ck_tnd_hot_order'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('last_enqueued_request_count__lte', models.F('request_count'))), name='ck_tnd_enqueued_count'),
        ),
        migrations.AddConstraint(
            model_name='trendnarrativedemand',
            constraint=models.CheckConstraint(condition=models.Q(('last_enqueued_operator_request_count__lte', models.F('operator_request_count'))), name='ck_tnd_operator_count'),
        ),
    ]
