# Generated by Django 5.2.16 on 2026-09-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_headline_demand_risk_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSynthesisArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_context_fingerprint', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('provider_role', models.CharField(max_length=64)),
                ('output_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('generating', 'Generating'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('evidence_provenance', models.JSONField(db_default=[], default=list)),
                ('review_state', models.CharField(blank=True, default='', max_length=32)),
                ('is_current', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='synthesis_artifacts', to='core.post')),
            ],
            options={
                'db_table': 'post_synthesis_artifacts',
            },
        ),
        migrations.CreateModel(
            name='PostSynthesisDailyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('control_revision', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('reserved_requests', models.PositiveIntegerField(default=0)),
                ('reserved_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('reserved_output_tokens', models.PositiveBigIntegerField(default=0)),
                ('observed_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('observed_output_tokens', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_synthesis_daily_budgets',
                'constraints': [models.UniqueConstraint(fields=('usage_date', 'control_revision', 'provider', 'model'), name='uq_post_synth_daily_budget')],
            },
        ),
        migrations.CreateModel(
            name='PostSynthesisDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_context_fingerprint', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('output_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.CharField(choices=[('prewarm', 'Prewarm'), ('lookahead', 'Lookahead'), ('visible', 'Visible'), ('expanded', 'Expanded'), ('operator', 'Operator')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField()),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('first_requested_at', models.DateTimeField()),
                ('last_requested_at', models.DateTimeField()),
                ('not_before', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lease_fence', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='core.postsynthesisartifact')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='core.postsynthesisdailybudget')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='synthesis_demands', to='core.post')),
            ],
            options={
                'db_table': 'post_synthesis_demands',
            },
        ),
        migrations.CreateModel(
            name='PostSynthesisRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField()),
                ('scope_hash', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_synthesis_rate_limit_buckets',
                'indexes': [models.Index(fields=['bucket_start'], name='idx_psynth_rate_time')],
                'constraints': [models.UniqueConstraint(fields=('bucket_start', 'scope_hash'), name='uq_post_synth_rate_bucket')],
            },
        ),
        migrations.CreateModel(
            name='PostSynthesisText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='core.postsynthesisartifact')),
            ],
            options={
                'db_table': 'post_synthesis_texts',
            },
        ),
        migrations.CreateModel(
            name='PostTranslationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_fingerprint', models.CharField(max_length=64)),
                ('source_language', models.CharField(max_length=16)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('provider_role', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('generating', 'Generating'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('is_current', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='translation_artifacts', to='core.post')),
            ],
            options={
                'db_table': 'post_translation_artifacts',
            },
        ),
        migrations.CreateModel(
            name='PostTranslationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('text', models.TextField()),
                ('is_source', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='core.posttranslationartifact')),
            ],
            options={
                'db_table': 'post_translation_texts',
            },
        ),
        migrations.CreateModel(
            name='BrandTrendNarrativeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('headline', models.TextField()),
                ('secondary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_texts', to='core.brandtrendnarrative')),
            ],
            options={
                'db_table': 'brand_trend_narrative_texts',
                'constraints': [models.UniqueConstraint(fields=('narrative', 'locale'), name='uq_brand_trend_narrative_locale'), models.CheckConstraint(condition=models.Q(('locale__in', ['en', 'zh-cn', 'ja'])), name='ck_brand_trend_narrative_locale'), models.CheckConstraint(condition=models.Q(models.Q(('headline', ''), _negated=True), models.Q(('secondary', ''), _negated=True)), name='ck_brand_trend_narrative_text')],
            },
        ),
        migrations.AddIndex(
            model_name='postsynthesisartifact',
            index=models.Index(fields=['post', '-created_at'], name='idx_post_synthesis_post'),
        ),
        migrations.AddIndex(
            model_name='postsynthesisartifact',
            index=models.Index(fields=['state', 'updated_at'], name='idx_post_synthesis_state'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisartifact',
            constraint=models.UniqueConstraint(fields=('post', 'input_context_fingerprint', 'prompt_version', 'model', 'provider_role', 'output_schema_version'), name='uq_post_synthesis_identity'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('post',), name='uq_post_synthesis_current'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('is_current', False), ('state', 'generating')), models.Q(('completed_at__isnull', False), ('error_code', ''), ('state', 'succeeded')), models.Q(('completed_at__isnull', False), ('error_code__gt', ''), ('is_current', False), ('state', 'failed')), _connector='OR'), name='ck_post_synthesis_state'),
        ),
        migrations.AddIndex(
            model_name='postsynthesisdemand',
            index=models.Index(fields=['state', 'not_before', '-priority'], name='idx_post_synth_demand_due'),
        ),
        migrations.AddIndex(
            model_name='postsynthesisdemand',
            index=models.Index(fields=['lease_expires_at'], name='idx_post_synth_lease_expiry'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisdemand',
            constraint=models.UniqueConstraint(fields=('post', 'input_context_fingerprint', 'prompt_version', 'model', 'output_schema_version'), name='uq_post_synthesis_demand_identity'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisdemand',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 100)), name='ck_post_synth_demand_priority'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisdemand',
            constraint=models.CheckConstraint(condition=models.Q(('last_requested_at__gte', models.F('first_requested_at'))), name='ck_post_synth_request_order'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesisdemand',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_fence__gt', 0), ('lease_owner__gt', ''), ('state', 'processing')), models.Q(models.Q(('state', 'processing'), _negated=True), ('lease_expires_at__isnull', True), ('lease_owner', '')), _connector='OR'), name='ck_post_synth_demand_lease'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesistext',
            constraint=models.UniqueConstraint(fields=('artifact', 'locale'), name='uq_post_synthesis_locale'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesistext',
            constraint=models.CheckConstraint(condition=models.Q(('locale__in', ['en', 'zh-cn', 'ja'])), name='ck_post_synthesis_locale'),
        ),
        migrations.AddConstraint(
            model_name='postsynthesistext',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='ck_post_synthesis_text'),
        ),
        migrations.AddIndex(
            model_name='posttranslationartifact',
            index=models.Index(fields=['post', '-created_at'], name='idx_post_translation_post'),
        ),
        migrations.AddIndex(
            model_name='posttranslationartifact',
            index=models.Index(fields=['state', 'updated_at'], name='idx_post_translation_state'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationartifact',
            constraint=models.UniqueConstraint(fields=('post', 'source_content_fingerprint', 'source_language', 'prompt_version', 'model', 'provider_role'), name='uq_post_translation_identity'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('post',), name='uq_post_translation_current'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('is_current', False), ('state', 'generating')), models.Q(('completed_at__isnull', False), ('error_code', ''), ('state', 'succeeded')), models.Q(('completed_at__isnull', False), ('error_code__gt', ''), ('is_current', False), ('state', 'failed')), _connector='OR'), name='ck_post_translation_state'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationtext',
            constraint=models.UniqueConstraint(fields=('artifact', 'locale'), name='uq_post_translation_locale'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationtext',
            constraint=models.CheckConstraint(condition=models.Q(('locale__in', ['en', 'zh-cn', 'ja'])), name='ck_post_translation_locale'),
        ),
        migrations.AddConstraint(
            model_name='posttranslationtext',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='ck_post_translation_text'),
        ),
    ]
