# Generated by Django 5.2.16 on 2026-09-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_split_translation_synthesis_ja"),
    ]

    operations = [
        migrations.AddField(
            model_name="personbrandaffiliation",
            name="brand_discovery_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_affiliations",
                to="core.branddiscoverycandidate",
            ),
        ),
        migrations.AlterField(
            model_name="personbrandaffiliation",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person_affiliations",
                to="core.brand",
            ),
        ),
        migrations.AddConstraint(
            model_name="personbrandaffiliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("brand__isnull", False),
                        ("brand_discovery_candidate__isnull", True),
                    ),
                    models.Q(
                        ("brand__isnull", True),
                        ("brand_discovery_candidate__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_pba_one_organization",
            ),
        ),
    ]
