# Generated by Django 5.2.16 on 2026-09-12 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_affiliation_candidate_and_integrity_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="consecutive_missing_snapshots",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="last_complete_source_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="source_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["source_key", "status"], name="idx_jobs_source_status"
            ),
        ),
        migrations.CreateModel(
            name="JobSourceSyncRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_complete", models.BooleanField(default=False)),
                ("declared_total", models.PositiveIntegerField(blank=True, null=True)),
                ("observed_total", models.PositiveIntegerField(blank=True, null=True)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("reopened_count", models.PositiveIntegerField(default=0)),
                ("closed_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "job_source_sync_runs",
                "ordering": ["-started_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["source_key", "started_at"],
                        name="idx_job_sync_source_started",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "running",
                                    "succeeded",
                                    "partial",
                                    "failed",
                                    "skipped",
                                ],
                            )
                        ),
                        name="ck_job_sync_run_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobSourceState",
            fields=[
                (
                    "source_key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("lease_token", models.CharField(blank=True, max_length=64, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_snapshot_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_source_states",
                        to="core.jobsourcesyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "job_source_states",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lease_expires_at__isnull", True),
                                ("lease_token__isnull", True),
                            ),
                            models.Q(
                                ("lease_expires_at__isnull", False),
                                ("lease_token__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_job_source_lease_complete",
                    )
                ],
            },
        ),
    ]
