# Generated by Django 5.2.16 on 2026-09-18 11:00

import django.db.models.deletion
from django.db import migrations, models


LOCALES = ("en", "zh-cn", "ja")
AUDIENCE_TOPIC_SCHEME_KEY = "ai_audience_topics/v1"
AUDIENCE_TOPIC_MANIFEST_HASH = (
    "a31f753183b4287b050e7ed8740cba0153ac79ab7ea6ff634a22c28713007a7d"
)
AUDIENCE_TOPIC_LABELS = {
    "local_inference": ("Local Inference", "本地推理", "ローカル推論"),
    "cost_performance": ("Cost & Performance", "成本与性能", "コスト・性能"),
    "model_distillation": ("Model Distillation", "模型蒸馏", "モデル蒸留"),
    "evals_benchmarks": ("Evaluations & Benchmarks", "评测与基准", "評価・ベンチマーク"),
    "openness_license": ("Openness & Licensing", "开放性与许可证", "オープン性・ライセンス"),
    "agents_tools": ("Agents & Tools", "智能体与工具", "エージェント・ツール"),
    "api_developer_surface": ("API & Developer Surface", "API 与开发者平台", "API・開発者向け機能"),
}
POST_TYPE_LABELS = {
    "results_analysis": ("Results Analysis", "结果分析", "結果分析"),
    "news_reporting": ("News Reporting", "新闻报道", "ニュース報道"),
}
PRODUCT_LABELS = {
    "investigate_claim": ("Claim to Investigate", "待核实声明", "要確認の主張"),
}
GEOPOLITICAL_MODE_LABELS = {
    "reporting": ("Reporting", "地缘政治报道", "地政学的報道"),
    "framework": ("Framework", "地缘政治框架", "地政学的フレームワーク"),
    "nationalism": ("Nationalism", "民族主义", "ナショナリズム"),
}
NATIONAL_STANCE_LABELS = {
    "none": ("None", "无", "なし"),
    "mild_pro": ("Mild Pro", "温和支持", "控えめな支持"),
    "pro": ("Pro", "支持", "支持"),
    "constructive_critical": ("Constructive Critical", "建设性批评", "建設的な批判"),
    "anti": ("Anti", "反对", "反対"),
    "mixed": ("Mixed", "混合", "賛否混在"),
}
UNTRACKED_BRAND_PROMOTION_LABELS = {
    "general": ("General", "一般推广", "一般"),
    "spam": ("Spam", "垃圾推广", "スパム"),
    "scam": ("Scam", "欺诈", "詐欺"),
    "crypto": ("Crypto", "加密货币", "暗号資産"),
    "unauthorized": ("Unauthorized", "未经授权", "無許可"),
}


def seed_u18a_catalog_and_copy_v3_stances(apps, schema_editor):
    """Seed immutable v4 catalogs and copy v3 scalar stance values exactly."""
    alias = schema_editor.connection.alias
    PostTypeKey = apps.get_model("core", "PostTypeKey")
    PostTypeLabel = apps.get_model("core", "PostTypeLabel")
    ProductLabelKey = apps.get_model("core", "ProductLabelKey")
    ProductLabelLabel = apps.get_model("core", "ProductLabelLabel")
    AudienceTopicScheme = apps.get_model("core", "AudienceTopicScheme")
    AudienceTopicConcept = apps.get_model("core", "AudienceTopicConcept")
    AudienceTopicLabel = apps.get_model("core", "AudienceTopicLabel")
    GeopoliticalModeKey = apps.get_model("core", "GeopoliticalModeKey")
    GeopoliticalModeLabel = apps.get_model("core", "GeopoliticalModeLabel")
    NationalStanceKey = apps.get_model("core", "NationalStanceKey")
    NationalStanceLabel = apps.get_model("core", "NationalStanceLabel")
    PromotionKey = apps.get_model("core", "UntrackedBrandPromotionKey")
    PromotionLabel = apps.get_model("core", "UntrackedBrandPromotionLabel")
    State = apps.get_model("core", "PostBrandClassificationState")

    def seed_enum(Key, Label, field, labels):
        for key, values in labels.items():
            Key.objects.using(alias).get_or_create(key=key)
            for lang, label in zip(LOCALES, values, strict=True):
                Label.objects.using(alias).update_or_create(
                    **{f"{field}_id": key, "lang": lang},
                    defaults={"label": label},
                )

    seed_enum(PostTypeKey, PostTypeLabel, "post_type", POST_TYPE_LABELS)
    seed_enum(ProductLabelKey, ProductLabelLabel, "product_label", PRODUCT_LABELS)
    seed_enum(
        GeopoliticalModeKey,
        GeopoliticalModeLabel,
        "geopolitical_mode",
        GEOPOLITICAL_MODE_LABELS,
    )
    seed_enum(NationalStanceKey, NationalStanceLabel, "national_stance", NATIONAL_STANCE_LABELS)
    # Preserve every historical scalar value before the compatibility copy.
    # NationalismKey was intentionally extensible, so operator-added keys may
    # exist even though only the canonical catalog has localized labels.
    legacy_stance_keys = set(
        State.objects.using(alias)
        .exclude(china_nationalism__isnull=True)
        .values_list("china_nationalism_id", flat=True)
    )
    legacy_stance_keys.update(
        State.objects.using(alias)
        .exclude(us_nationalism__isnull=True)
        .values_list("us_nationalism_id", flat=True)
    )
    for key in sorted(legacy_stance_keys):
        NationalStanceKey.objects.using(alias).get_or_create(key=key)
    seed_enum(
        PromotionKey,
        PromotionLabel,
        "untracked_brand_promotion",
        UNTRACKED_BRAND_PROMOTION_LABELS,
    )

    scheme, _created = AudienceTopicScheme.objects.using(alias).get_or_create(
        key=AUDIENCE_TOPIC_SCHEME_KEY,
        defaults={"revision": 1, "manifest_hash": AUDIENCE_TOPIC_MANIFEST_HASH},
    )
    for key, values in AUDIENCE_TOPIC_LABELS.items():
        concept, _created = AudienceTopicConcept.objects.using(alias).get_or_create(
            scheme_id=scheme.pk,
            key=key,
        )
        for lang, label in zip(LOCALES, values, strict=True):
            AudienceTopicLabel.objects.using(alias).update_or_create(
                concept_id=concept.pk,
                revision=1,
                lang=lang,
                defaults={"label": label},
            )

    # This is intentionally a copy only.  A v3 `none` stays a stance value;
    # it is never inferred to mean the new Geopolitical `framework` mode.
    State.objects.using(alias).filter(china_national_stance__isnull=True).update(
        china_national_stance=models.F("china_nationalism")
    )
    State.objects.using(alias).filter(us_national_stance__isnull=True).update(
        us_national_stance=models.F("us_nationalism")
    )
    # Django executes deferred FK/index SQL after RunPython.  PostgreSQL will
    # not create those indexes while deferred FK trigger work is pending.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_u18_two_role_classification_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceTopicConcept',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_collation='case_insensitive', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audience_topic_concepts',
                'ordering': ['scheme_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AudienceTopicScheme',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=128, primary_key=True, serialize=False)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audience_topic_schemes',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GeopoliticalModeKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geopolitical_mode_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NationalStanceKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'national_stance_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UntrackedBrandPromotionKey',
            fields=[
                ('key', models.CharField(db_collation='case_insensitive', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'untracked_brand_promotion_keys',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AudienceTopicLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('concept', 'revision', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('lang', models.CharField(max_length=16)),
                ('label', models.TextField()),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.audiencetopicconcept')),
            ],
            options={
                'db_table': 'audience_topic_labels',
            },
        ),
        migrations.AddField(
            model_name='audiencetopicconcept',
            name='scheme',
            field=models.ForeignKey(db_column='scheme_key', on_delete=django.db.models.deletion.PROTECT, related_name='concepts', to='core.audiencetopicscheme'),
        ),
        migrations.CreateModel(
            name='GeopoliticalModeLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('geopolitical_mode', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=16)),
                ('label', models.TextField()),
                ('geopolitical_mode', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.geopoliticalmodekey')),
            ],
            options={
                'db_table': 'geopolitical_mode_labels',
            },
        ),
        migrations.AddField(
            model_name='postbrandclassificationstate',
            name='china_national_stance',
            field=models.ForeignKey(blank=True, db_column='china_national_stance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.nationalstancekey'),
        ),
        migrations.AddField(
            model_name='postbrandclassificationstate',
            name='us_national_stance',
            field=models.ForeignKey(blank=True, db_column='us_national_stance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.nationalstancekey'),
        ),
        migrations.CreateModel(
            name='NationalStanceLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('national_stance', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=16)),
                ('label', models.TextField()),
                ('national_stance', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.nationalstancekey')),
            ],
            options={
                'db_table': 'national_stance_labels',
            },
        ),
        migrations.CreateModel(
            name='PostBrandAudienceTopic',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', 'concept', blank=True, editable=False, primary_key=True, serialize=False)),
                ('scheme_revision', models.PositiveSmallIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=256)),
                ('provider_role', models.CharField(max_length=64)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand')),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.audiencetopicconcept')),
                ('final_judgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_topic_assignments', to='core.postbrandclassificationjudgment')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='audience_topic_assignments', to='core.post')),
                ('scheme', models.ForeignKey(db_column='scheme_key', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.audiencetopicscheme')),
            ],
            options={
                'db_table': 'posts_brands_audience_topics',
            },
        ),
        migrations.CreateModel(
            name='PostBrandGeopoliticalMode',
            fields=[
                ('pk', models.CompositePrimaryKey('post', 'brand', 'geopolitical_mode', blank=True, editable=False, primary_key=True, serialize=False)),
                ('taxonomy_version', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=256)),
                ('provider_role', models.CharField(max_length=64)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand')),
                ('final_judgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geopolitical_mode_assignments', to='core.postbrandclassificationjudgment')),
                ('geopolitical_mode', models.ForeignKey(db_column='geopolitical_mode_key', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.geopoliticalmodekey')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='geopolitical_mode_assignments', to='core.post')),
            ],
            options={
                'db_table': 'posts_brands_geopolitical_modes',
            },
        ),
        migrations.CreateModel(
            name='PostUntrackedBrandPromotion',
            fields=[
                ('post', models.OneToOneField(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='untracked_brand_promotion', serialize=False, to='core.post')),
                ('promotion_keys', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('contract_version', models.CharField(max_length=64)),
                ('taxonomy_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=256)),
                ('provider_role', models.CharField(max_length=64)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('final_judgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untracked_brand_promotions', to='core.postbrandclassificationjudgment')),
            ],
            options={
                'db_table': 'posts_untracked_brand_promotions',
            },
        ),
        migrations.CreateModel(
            name='UntrackedBrandPromotionEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_name', models.TextField()),
                ('aliases', models.JSONField(default=list)),
                ('handles', models.JSONField(default=list)),
                ('domains', models.JSONField(default=list)),
                ('products', models.JSONField(default=list)),
                ('hashtags', models.JSONField(default=list)),
                ('evidence_spans', models.JSONField(default=list)),
                ('subject_identity', models.CharField(max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('recurrence_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_discovery_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='untracked_brand_promotion_evidence', to='core.branddiscoverycandidate')),
                ('exact_matched_account', models.ForeignKey(blank=True, db_column='exact_matched_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untracked_brand_promotion_evidence', to='core.account')),
                ('promotion', models.ForeignKey(db_column='promotion_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='subject_evidence', to='core.postuntrackedbrandpromotion', to_field='post_id')),
                ('source_post', models.ForeignKey(db_column='source_post_id', on_delete=django.db.models.deletion.PROTECT, related_name='untracked_brand_promotion_evidence', to='core.post')),
            ],
            options={
                'db_table': 'untracked_brand_promotion_evidence',
                'ordering': ['source_post_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UntrackedBrandPromotionLabel',
            fields=[
                ('pk', models.CompositePrimaryKey('untracked_brand_promotion', 'lang', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=16)),
                ('label', models.TextField()),
                ('untracked_brand_promotion', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.untrackedbrandpromotionkey')),
            ],
            options={
                'db_table': 'untracked_brand_promotion_labels',
            },
        ),
        migrations.AddConstraint(
            model_name='audiencetopicconcept',
            constraint=models.UniqueConstraint(fields=('scheme', 'key'), name='uq_audience_topic_scheme_key'),
        ),
        migrations.AddIndex(
            model_name='postbrandaudiencetopic',
            index=models.Index(fields=['brand', 'concept'], name='idx_pb_aud_topic_brand_concept'),
        ),
        migrations.AddIndex(
            model_name='postbrandaudiencetopic',
            index=models.Index(fields=['scheme', 'scheme_revision'], name='idx_pb_aud_topic_scheme_rev'),
        ),
        migrations.AddIndex(
            model_name='postbrandgeopoliticalmode',
            index=models.Index(fields=['brand', 'geopolitical_mode'], name='idx_pb_geo_mode_brand_mode'),
        ),
        migrations.AddIndex(
            model_name='postbrandgeopoliticalmode',
            index=models.Index(fields=['taxonomy_version'], name='idx_pb_geo_mode_taxonomy'),
        ),
        migrations.AddIndex(
            model_name='postuntrackedbrandpromotion',
            index=models.Index(fields=['promotion_keys'], name='idx_post_untracked_promo_keys'),
        ),
        migrations.AddIndex(
            model_name='untrackedbrandpromotionevidence',
            index=models.Index(fields=['brand_discovery_candidate', '-last_seen_at'], name='idx_untracked_promo_cand_last'),
        ),
        migrations.AddIndex(
            model_name='untrackedbrandpromotionevidence',
            index=models.Index(fields=['exact_matched_account', '-last_seen_at'], name='idx_untracked_promo_acct_last'),
        ),
        migrations.AddConstraint(
            model_name='untrackedbrandpromotionevidence',
            constraint=models.UniqueConstraint(fields=('promotion', 'subject_identity'), name='uq_untracked_promo_subject_identity'),
        ),
        migrations.AddConstraint(
            model_name='untrackedbrandpromotionevidence',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('first_seen_at'))), name='ck_untracked_promo_evidence_window'),
        ),
        migrations.AddConstraint(
            model_name='untrackedbrandpromotionevidence',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_count__gte', 1)), name='ck_untracked_promo_evidence_recurrence'),
        ),
        migrations.AddConstraint(
            model_name='untrackedbrandpromotionevidence',
            constraint=models.CheckConstraint(condition=models.Q(('source_post', models.F('promotion'))), name='ck_untracked_promo_evidence_source_post'),
        ),
        migrations.RunPython(seed_u18a_catalog_and_copy_v3_stances, migrations.RunPython.noop),
    ]
