# Generated by Django 5.2.16 on 2026-09-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_direct_job_sources'),
        ('core', '0043_audiencetopicconcept_audiencetopicscheme_and_more'),
    ]

    operations = [
    ]
