# Generated by Django 5.2.16 on 2026-09-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20260918_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareTypeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_post_id', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=255)),
                ('question_version', models.CharField(max_length=128)),
                ('threshold_version', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('review_needed', 'Review needed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('response_id', models.CharField(blank=True, default='', max_length=255)),
                ('probabilities', models.JSONField(default=dict)),
                ('derived_types', models.JSONField(default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('claim_owner', models.CharField(blank=True, default='', max_length=128)),
                ('claim_fence', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rare_type_decisions',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_rare_decision_due'), models.Index(fields=['provider_post_id'], name='idx_rare_decision_post')],
                'constraints': [models.UniqueConstraint(fields=('provider_post_id', 'content_hash', 'model', 'question_version', 'threshold_version'), name='uq_rare_decision_identity'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'completed', 'review_needed', 'failed'])), name='ck_rare_decision_status'), models.CheckConstraint(condition=models.Q(('attempts__lte', 2)), name='ck_rare_decision_attempts'), models.CheckConstraint(condition=models.Q(models.Q(('claim_expires_at__gt', models.F('claimed_at')), ('claim_expires_at__isnull', False), ('claim_fence__gt', 0), ('claim_owner__gt', ''), ('claimed_at__isnull', False), ('status', 'claimed')), models.Q(models.Q(('status', 'claimed'), _negated=True), ('claim_expires_at__isnull', True), ('claim_owner', ''), ('claimed_at__isnull', True)), _connector='OR'), name='ck_rare_decision_claim_shape'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('response_id__gt', ''), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='ck_rare_decision_complete_shape'), models.CheckConstraint(condition=models.Q(('cost_usd__gte', 0)), name='ck_rare_decision_cost')],
            },
        ),
        migrations.CreateModel(
            name='RareTypeSearchDailyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('lane', models.CharField(max_length=64)),
                ('search_credits_reserved', models.PositiveIntegerField(default=0)),
                ('search_credits_accounted', models.PositiveIntegerField(default=0)),
                ('decision_usd_reserved', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('decision_usd_accounted', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('decision_usd_confirmed', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rare_type_search_daily_budgets',
                'constraints': [models.UniqueConstraint(fields=('usage_date', 'lane'), name='uq_rare_budget_day_lane'), models.CheckConstraint(condition=models.Q(('decision_usd_reserved__gte', 0)), name='ck_rare_budget_dec_reserved'), models.CheckConstraint(condition=models.Q(('decision_usd_accounted__gte', 0)), name='ck_rare_budget_dec_accounted'), models.CheckConstraint(condition=models.Q(('decision_usd_confirmed__gte', 0)), name='ck_rare_budget_dec_confirmed')],
            },
        ),
        migrations.CreateModel(
            name='RareTypeSearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=64)),
                ('slot_start', models.DateTimeField()),
                ('query_string', models.TextField()),
                ('query_hash', models.CharField(max_length=64)),
                ('query_version', models.CharField(max_length=128)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('attempted_start', models.DateTimeField()),
                ('attempted_end', models.DateTimeField()),
                ('complete_start', models.DateTimeField(blank=True, null=True)),
                ('complete_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('empty', 'Empty'), ('failed', 'Failed'), ('usage_unknown', 'Usage unknown')], default='reserved', max_length=16)),
                ('request_count', models.PositiveSmallIntegerField(default=0)),
                ('raw_result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('normalized_result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reserved_credits', models.PositiveIntegerField(default=300)),
                ('estimated_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('decision_usd_reserved', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('decision_usd_accounted', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('decision_usd_confirmed', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('has_coverage_gap', models.BooleanField(default=False)),
                ('gap_start', models.DateTimeField(blank=True, null=True)),
                ('gap_end', models.DateTimeField(blank=True, null=True)),
                ('gap_reason', models.CharField(blank=True, default='', max_length=128)),
                ('truncated', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('environment', models.CharField(max_length=64)),
                ('release_sha', models.CharField(max_length=64)),
                ('reserved_at', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_runs', to='core.raretypesearchdailybudget')),
                ('source_query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rare_type_search_runs', to='core.searchquery')),
            ],
            options={
                'db_table': 'rare_type_search_runs',
            },
        ),
        migrations.CreateModel(
            name='RareTypeSearchHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_post_id', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('original_text', models.TextField(blank=True, default='')),
                ('public_payload', models.JSONField(default=dict)),
                ('payload_expires_at', models.DateTimeField()),
                ('payload_expired_at', models.DateTimeField(blank=True, null=True)),
                ('source_query_hash', models.CharField(max_length=64)),
                ('source_query_version', models.CharField(max_length=128)),
                ('source_window_start', models.DateTimeField()),
                ('source_window_end', models.DateTimeField()),
                ('gate_state', models.CharField(choices=[('decision_pending', 'Decision pending'), ('kept', 'Kept'), ('junk', 'Junk'), ('review_needed', 'Review needed'), ('provider_failed', 'Provider failed'), ('expired_unprocessed', 'Expired unprocessed')], default='decision_pending', max_length=24)),
                ('fetched_at', models.DateTimeField()),
                ('gate_completed_at', models.DateTimeField(blank=True, null=True)),
                ('post_persisted_at', models.DateTimeField(blank=True, null=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('first_visible_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='core.raretypedecision')),
                ('post', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rare_type_search_hits', to='core.post')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='core.raretypesearchrun')),
            ],
            options={
                'db_table': 'rare_type_search_hits',
            },
        ),
        migrations.AddIndex(
            model_name='raretypesearchrun',
            index=models.Index(fields=['lane', '-attempted_end'], name='idx_rare_run_attempted'),
        ),
        migrations.AddIndex(
            model_name='raretypesearchrun',
            index=models.Index(fields=['status', 'slot_start'], name='idx_rare_run_status_slot'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.UniqueConstraint(fields=('lane', 'slot_start'), name='uq_rare_run_lane_slot'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['reserved', 'dispatched', 'returned', 'empty', 'failed', 'usage_unknown'])), name='ck_rare_run_status'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('window_end__gt', models.F('window_start'))), name='ck_rare_run_window'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempted_end__gt', models.F('attempted_start'))), name='ck_rare_run_attempted_window'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complete_end__isnull', True), ('complete_start__isnull', True)), models.Q(('complete_end__gt', models.F('complete_start')), ('complete_end__isnull', False), ('complete_start__isnull', False)), _connector='OR'), name='ck_rare_run_complete_window'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gap_end__isnull', True), ('gap_reason', ''), ('gap_start__isnull', True), ('has_coverage_gap', False)), models.Q(('gap_end__gt', models.F('gap_start')), ('gap_end__isnull', False), ('gap_reason__gt', ''), ('gap_start__isnull', False), ('has_coverage_gap', True)), _connector='OR'), name='ck_rare_run_gap_shape'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispatched_at__isnull', True), ('request_count', 0), ('status', 'reserved')), models.Q(('dispatched_at__isnull', False), ('request_count', 1), ('status__in', ['dispatched', 'returned', 'empty', 'usage_unknown'])), models.Q(('request_count__in', [0, 1]), ('status', 'failed')), _connector='OR'), name='ck_rare_run_dispatch_shape'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_credits__isnull', True), ('estimated_credits__isnull', True), ('normalized_result_count__isnull', True), ('raw_result_count__isnull', True), ('returned_at__isnull', True), ('status__in', ['reserved', 'dispatched'])), models.Q(('estimated_credits__isnull', False), ('normalized_result_count__isnull', False), ('normalized_result_count__lte', models.F('raw_result_count')), ('raw_result_count__gt', 0), ('returned_at__isnull', False), ('status', 'returned')), models.Q(('estimated_credits__isnull', False), ('normalized_result_count', 0), ('raw_result_count', 0), ('returned_at__isnull', False), ('status', 'empty')), ('status__in', ['failed', 'usage_unknown']), _connector='OR'), name='ck_rare_run_result_shape'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('decision_usd_reserved__gte', 0)), name='ck_rare_run_dec_reserved'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('decision_usd_accounted__gte', 0)), name='ck_rare_run_dec_accounted'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchrun',
            constraint=models.CheckConstraint(condition=models.Q(('decision_usd_confirmed__gte', 0)), name='ck_rare_run_dec_confirmed'),
        ),
        migrations.AddIndex(
            model_name='raretypesearchhit',
            index=models.Index(fields=['gate_state', 'fetched_at'], name='idx_rare_hit_gate_due'),
        ),
        migrations.AddIndex(
            model_name='raretypesearchhit',
            index=models.Index(fields=['provider_post_id'], name='idx_rare_hit_post'),
        ),
        migrations.AddIndex(
            model_name='raretypesearchhit',
            index=models.Index(fields=['payload_expires_at'], name='idx_rare_hit_expiry'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchhit',
            constraint=models.UniqueConstraint(fields=('run', 'provider_post_id'), name='uq_rare_hit_run_post'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchhit',
            constraint=models.CheckConstraint(condition=models.Q(('gate_state__in', ['decision_pending', 'kept', 'junk', 'review_needed', 'provider_failed', 'expired_unprocessed'])), name='ck_rare_hit_gate_state'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchhit',
            constraint=models.CheckConstraint(condition=models.Q(('source_window_end__gt', models.F('source_window_start'))), name='ck_rare_hit_source_window'),
        ),
        migrations.AddConstraint(
            model_name='raretypesearchhit',
            constraint=models.CheckConstraint(condition=models.Q(('payload_expires_at__gt', models.F('fetched_at'))), name='ck_rare_hit_payload_expiry'),
        ),
    ]
