# Generated by Django 5.2.16 on 2026-09-24 08:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_merge_20260918_1344"),
    ]

    operations = [
        migrations.CreateModel(
            name="HFModelCatalogRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.JSONField()),
                ("outcome", models.CharField(default="pending", max_length=40)),
                ("invocations", models.JSONField(default=list)),
                ("report", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hf_model_catalog_runs",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="hf_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="downloads",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="downloads_all_time",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="likes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HFModelCatalogNamespaceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=64)),
                ("ownership", models.JSONField()),
                ("cursor", models.TextField(blank=True, null=True)),
                ("cursor_history", models.JSONField(default=list)),
                ("enumeration_complete", models.BooleanField(default=False)),
                ("outcome", models.CharField(default="pending", max_length=64)),
                ("envelopes", models.JSONField(default=list)),
                ("raw_count", models.BigIntegerField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="core.hfmodelcatalogrun",
                    ),
                ),
            ],
            options={
                "db_table": "hf_model_catalog_namespace_runs",
            },
        ),
        migrations.CreateModel(
            name="HFModelCatalogObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_key", models.CharField(max_length=256)),
                ("repo_id", models.CharField(max_length=256)),
                ("created_product", models.BooleanField(default=False)),
                ("listing", models.JSONField(default=dict)),
                ("envelopes", models.JSONField(default=list)),
                ("groups", models.JSONField(default=dict)),
                ("outcome", models.CharField(default="pending", max_length=64)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "namespace_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="core.hfmodelcatalognamespacerun",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "hf_model_catalog_observations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace_run", "repo_key"),
                        name="uq_hf_catalog_repo_observation",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hfmodelcatalognamespacerun",
            constraint=models.UniqueConstraint(
                fields=("run", "namespace"), name="uq_hf_catalog_run_namespace"
            ),
        ),
    ]
