# Generated by Django 5.2.16 on 2026-09-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_remove_raretypesearchrun_ck_rare_run_result_shape_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RareTypeDecisionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fence", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("sent", "Sent"),
                            ("settled", "Settled"),
                            ("retained", "Retained"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("reserved_usd", models.DecimalField(decimal_places=9, max_digits=16)),
                (
                    "accounted_usd",
                    models.DecimalField(decimal_places=9, default=0, max_digits=16),
                ),
                (
                    "confirmed_usd",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=16, null=True
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "response_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("reserved_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rare_type_decision_attempts",
            },
        ),
        migrations.CreateModel(
            name="RareTypeDecisionProcessingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lane", models.CharField(max_length=64)),
                ("environment", models.CharField(max_length=16)),
                ("slot_start", models.DateTimeField()),
                ("usage_date", models.DateField()),
                ("attempts_reserved", models.PositiveSmallIntegerField(default=0)),
                ("attempts_accounted", models.PositiveSmallIntegerField(default=0)),
                ("attempts_in_flight", models.PositiveSmallIntegerField(default=0)),
                (
                    "decision_usd_reserved",
                    models.DecimalField(decimal_places=9, default=0, max_digits=16),
                ),
                (
                    "decision_usd_accounted",
                    models.DecimalField(decimal_places=9, default=0, max_digits=16),
                ),
                (
                    "decision_usd_confirmed",
                    models.DecimalField(decimal_places=9, default=0, max_digits=16),
                ),
                ("allocation_started_at", models.DateTimeField()),
                ("allocation_deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rare_type_decision_processing_cycles",
            },
        ),
        migrations.RemoveConstraint(
            model_name="raretypesearchrun",
            name="ck_rare_run_result_shape",
        ),
        migrations.AddField(
            model_name="raretypedecision",
            name="gate_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kept", "Kept"),
                    ("junk", "Junk"),
                    ("review_needed", "Review needed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypesearchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_credits__isnull", True),
                        ("estimated_credits__isnull", True),
                        ("normalized_result_count__isnull", True),
                        ("raw_result_count__isnull", True),
                        ("returned_at__isnull", True),
                        ("status__in", ["reserved", "dispatched"]),
                    ),
                    models.Q(
                        ("estimated_credits__isnull", False),
                        ("normalized_result_count__isnull", False),
                        ("normalized_result_count__lte", models.F("raw_result_count")),
                        ("raw_result_count__gt", 0),
                        ("raw_result_count__isnull", False),
                        ("returned_at__isnull", False),
                        ("status", "returned"),
                    ),
                    models.Q(
                        ("estimated_credits__isnull", False),
                        ("normalized_result_count", 0),
                        ("normalized_result_count__isnull", False),
                        ("raw_result_count", 0),
                        ("raw_result_count__isnull", False),
                        ("returned_at__isnull", False),
                        ("status", "empty"),
                    ),
                    ("status__in", ["failed", "usage_unknown"]),
                    _connector="OR",
                ),
                name="ck_rare_run_result_shape",
            ),
        ),
        migrations.AddField(
            model_name="raretypedecisionattempt",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_events",
                to="core.raretypedecision",
            ),
        ),
        migrations.AddField(
            model_name="raretypedecisionprocessingcycle",
            name="daily_budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decision_processing_cycles",
                to="core.raretypesearchdailybudget",
            ),
        ),
        migrations.AddField(
            model_name="raretypedecisionattempt",
            name="processing_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_events",
                to="core.raretypedecisionprocessingcycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.UniqueConstraint(
                fields=("lane", "environment", "slot_start"),
                name="uq_rare_dec_cycle_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment__in", ["normal", "staging"])),
                name="ck_rare_dec_cycle_environment",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision_usd_reserved__gte", 0)),
                name="ck_rare_dec_cycle_reserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision_usd_accounted__gte", 0)),
                name="ck_rare_dec_cycle_accounted",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision_usd_confirmed__gte", 0)),
                name="ck_rare_dec_cycle_confirmed",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts_in_flight__lte", 2)),
                name="ck_rare_dec_cycle_inflight",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionprocessingcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocation_deadline__gt", models.F("allocation_started_at"))
                ),
                name="ck_rare_dec_cycle_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.UniqueConstraint(
                fields=("decision", "fence"), name="uq_rare_dec_attempt_fence"
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["reserved", "sent", "settled", "retained"])
                ),
                name="ck_rare_dec_attempt_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_usd__gt", 0)),
                name="ck_rare_dec_attempt_reserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("accounted_usd__gte", 0)),
                name="ck_rare_dec_attempt_accounted",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confirmed_usd__isnull", True),
                    ("confirmed_usd__gte", 0),
                    _connector="OR",
                ),
                name="ck_rare_dec_attempt_confirmed",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sent_at__isnull", True), ("state", "reserved")),
                    models.Q(
                        ("sent_at__isnull", False),
                        ("state__in", ["sent", "settled", "retained"]),
                    ),
                    _connector="OR",
                ),
                name="ck_rare_dec_attempt_send_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="raretypedecisionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("settled_at__isnull", False), ("state", "settled")),
                    models.Q(
                        models.Q(("state", "settled"), _negated=True),
                        ("settled_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_rare_dec_attempt_settle_shape",
            ),
        ),
    ]
