# Generated by Django 5.2.16 on 2026-09-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_raretypedecisionattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandDiscoveryCandidateToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("form", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("spelling", "Spelling"),
                            ("handle", "Handle"),
                            ("nickname", "Nickname"),
                        ],
                        max_length=16,
                    ),
                ),
                ("script", models.CharField(max_length=16)),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exact_tokens",
                        to="core.branddiscoverycandidate",
                    ),
                ),
            ],
            options={
                "db_table": "brand_discovery_candidate_tokens",
                "ordering": ["candidate_id", "kind", "form", "id"],
            },
        ),
        migrations.CreateModel(
            name="BrandDiscoveryCandidateTokenEvidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rare_type",
                    models.CharField(
                        choices=[
                            ("personnel_changes", "Personnel changes"),
                            ("job_listings", "Job listings"),
                            ("events", "Events"),
                            ("opportunities", "Opportunities"),
                            ("model_releases", "Model releases"),
                        ],
                        max_length=32,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_hit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_token_evidence",
                        to="core.raretypesearchhit",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        db_column="source_post_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_token_evidence",
                        to="core.post",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.branddiscoverycandidatetoken",
                    ),
                ),
            ],
            options={
                "db_table": "brand_discovery_candidate_token_evidence",
                "ordering": [
                    "token_id",
                    "observed_at",
                    "source_post_id",
                    "rare_type",
                    "id",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetoken",
            constraint=models.UniqueConstraint(
                fields=("candidate", "form", "kind"),
                name="uq_brand_candidate_token_exact",
            ),
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("form", ""), _negated=True),
                name="ck_brand_candidate_token_form",
            ),
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["spelling", "handle", "nickname"])),
                name="ck_brand_candidate_token_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_observed_at__gte", models.F("first_observed_at"))
                ),
                name="ck_brand_candidate_token_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetokenevidence",
            constraint=models.UniqueConstraint(
                fields=("token", "source_hit", "source_post", "rare_type"),
                name="uq_brand_candidate_token_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="branddiscoverycandidatetokenevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rare_type__in",
                        [
                            "personnel_changes",
                            "job_listings",
                            "events",
                            "opportunities",
                            "model_releases",
                        ],
                    )
                ),
                name="ck_brand_candidate_token_rare_type",
            ),
        ),
    ]
