# Generated by Django 5.2.16 on 2026-09-23 22:53

import django.db.models.deletion
from django.db import migrations, models


UNTRACKED_ORGANIZATIONS = (
    ("openai", "OpenAI", "openai", "OpenAI"),
    ("anthropic", "Anthropic", "anthropic", "Anthropic"),
    ("spacexai", "SpaceXAI", "xai", "xAI"),
    ("gemini", "Google Gemini", "google", "Google"),
)


def seed_untracked_organization_brands(apps, schema_editor):
    Brand = apps.get_model("core", "Brand")
    Company = apps.get_model("core", "Company")
    BrandCompany = apps.get_model("core", "BrandCompany")
    for brand_id, brand_name, company_id, company_name in UNTRACKED_ORGANIZATIONS:
        brand, _ = Brand.objects.get_or_create(
            nickname=brand_id,
            defaults={"display_name": brand_name, "display_name_en": brand_name},
        )
        company, _ = Company.objects.get_or_create(
            nickname=company_id,
            defaults={"display_name": company_name, "display_name_en": company_name},
        )
        conflicting = BrandCompany.objects.filter(brand=brand).exclude(
            company=company
        )
        if conflicting.exists():
            raise RuntimeError(
                f"canonical Brand {brand_id} already has a conflicting Company link"
            )
        BrandCompany.objects.get_or_create(
            brand=brand, company=company, defaults={"ownership_pct": 1.0}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rare_type_candidate_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRelease',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_model_name', models.TextField()),
                ('version', models.TextField(blank=True, default='')),
                ('release_channel', models.CharField(choices=[('stable', 'Stable'), ('preview', 'Preview'), ('beta', 'Beta'), ('other', 'Other')], default='other', max_length=16)),
                ('release_value', models.CharField(blank=True, max_length=64, null=True)),
                ('release_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('release_identity', models.CharField(max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('extraction_version', models.TextField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'model_releases',
                'ordering': ['-first_seen_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelReleaseEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('observed_at', models.DateTimeField()),
                ('observed_claim', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('extraction_version', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_release_evidence',
            },
        ),
        migrations.CreateModel(
            name='RareTypeCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('llm-model', 'LLM model'), ('other-ai-model', 'Other AI model'), ('agent-harness', 'Agent harness')], max_length=32)),
                ('source_evidence', models.JSONField(default=dict)),
                ('classification_version', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rare_type_category_assignments',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='brand_discovery_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.branddiscoverycandidate'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='brand_discovery_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.branddiscoverycandidate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.brand'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.brand'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', False), ('brand_discovery_candidate__isnull', True)), models.Q(('brand__isnull', True), ('brand_discovery_candidate__isnull', False)), _connector='OR'), name='ck_events_one_organization'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', False), ('brand_discovery_candidate__isnull', True)), models.Q(('brand__isnull', True), ('brand_discovery_candidate__isnull', False)), _connector='OR'), name='ck_opportunities_one_organization'),
        ),
        migrations.AddField(
            model_name='modelrelease',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_releases', to='core.brand'),
        ),
        migrations.AddField(
            model_name='modelrelease',
            name='brand_discovery_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_releases', to='core.branddiscoverycandidate'),
        ),
        migrations.AddField(
            model_name='modelreleaseevidence',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.modelrelease'),
        ),
        migrations.AddField(
            model_name='modelreleaseevidence',
            name='source_post',
            field=models.ForeignKey(db_column='source_post_id', on_delete=django.db.models.deletion.PROTECT, related_name='model_release_evidence', to='core.post'),
        ),
        migrations.AddField(
            model_name='raretypecategoryassignment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rare_type_categories', to='core.brand'),
        ),
        migrations.AddField(
            model_name='raretypecategoryassignment',
            name='brand_discovery_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rare_type_categories', to='core.branddiscoverycandidate'),
        ),
        migrations.AddField(
            model_name='raretypecategoryassignment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rare_type_categories', to='core.post'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', False), ('brand_discovery_candidate__isnull', True)), models.Q(('brand__isnull', True), ('brand_discovery_candidate__isnull', False)), _connector='OR'), name='ck_model_release_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('first_seen_at'))), name='ck_model_release_seen_window'),
        ),
        migrations.AddConstraint(
            model_name='modelrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release_precision', 'unknown'), ('release_value__isnull', True)), models.Q(('release_precision', 'day'), ('release_value__regex', '^[0-9]{4}-[0-9]{2}-[0-9]{2}$')), models.Q(('release_precision', 'month'), ('release_value__regex', '^[0-9]{4}-[0-9]{2}$')), models.Q(('release_precision', 'year'), ('release_value__regex', '^[0-9]{4}$')), _connector='OR'), name='ck_model_release_precision'),
        ),
        migrations.AddConstraint(
            model_name='modelreleaseevidence',
            constraint=models.UniqueConstraint(fields=('release', 'source_post', 'evidence_hash'), name='uq_model_release_evidence'),
        ),
        migrations.AddConstraint(
            model_name='raretypecategoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', False), ('brand_discovery_candidate__isnull', True)), models.Q(('brand__isnull', True), ('brand_discovery_candidate__isnull', False)), _connector='OR'), name='ck_rare_category_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='raretypecategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('post', 'brand', 'category'), name='uq_rare_category_post_brand'),
        ),
        migrations.AddConstraint(
            model_name='raretypecategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('brand_discovery_candidate__isnull', False)), fields=('post', 'brand_discovery_candidate', 'category'), name='uq_rare_category_post_candidate'),
        ),
        migrations.RemoveConstraint(
            model_name='targetedextractionstate',
            name='ck_target_extract_role',
        ),
        migrations.AddConstraint(
            model_name='targetedextractionstate',
            constraint=models.CheckConstraint(
                condition=models.Q(role__in=[
                    'event_extraction', 'opportunity_extraction',
                    'job_listing_extraction', 'personnel_change_extraction',
                    'profile_affiliation_extraction', 'model_release_extraction',
                ]),
                name='ck_target_extract_role',
            ),
        ),
        migrations.RunPython(
            seed_untracked_organization_brands, migrations.RunPython.noop
        ),
    ]
