# Generated by Django 5.2.16 on 2026-09-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rare_type_domain_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMovementCandidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prior_description', models.TextField()),
                ('new_description', models.TextField()),
                ('observed_at', models.DateTimeField()),
                ('effective_date', models.CharField(blank=True, max_length=10, null=True)),
                ('effective_date_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('movement_identity', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_movement_candidates', to='core.account')),
                ('new_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_candidates_as_new', to='core.accountprofilesnapshot')),
                ('prior_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_candidates_as_prior', to='core.accountprofilesnapshot')),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_movement_candidates', to='core.post')),
            ],
            options={
                'db_table': 'profile_movement_candidates',
                'constraints': [models.UniqueConstraint(fields=('account', 'prior_snapshot', 'new_snapshot'), name='uq_profile_movement_transition'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'succeeded', 'failed'])), name='ck_profile_movement_status'), models.CheckConstraint(condition=models.Q(models.Q(('effective_date__isnull', True), ('effective_date_precision', 'unknown')), models.Q(('effective_date__regex', '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'), ('effective_date_precision', 'day')), models.Q(('effective_date__regex', '^[0-9]{4}-[0-9]{2}$'), ('effective_date_precision', 'month')), models.Q(('effective_date__regex', '^[0-9]{4}$'), ('effective_date_precision', 'year')), _connector='OR'), name='ck_profile_movement_date_precision')],
            },
        ),
    ]
