# Generated by Django 5.2.16 on 2026-09-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_profile_movement_candidates'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branddiscoverycandidatetokenevidence',
            name='uq_brand_candidate_token_evidence',
        ),
        migrations.AddField(
            model_name='branddiscoverycandidatetokenevidence',
            name='source_profile_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_token_evidence', to='core.profilemovementcandidate'),
        ),
        migrations.AlterField(
            model_name='branddiscoverycandidatetokenevidence',
            name='source_hit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_token_evidence', to='core.raretypesearchhit'),
        ),
        migrations.AddConstraint(
            model_name='branddiscoverycandidatetokenevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('source_hit__isnull', False)), fields=('token', 'source_hit', 'source_post', 'rare_type'), name='uq_candidate_token_hit_evidence'),
        ),
        migrations.AddConstraint(
            model_name='branddiscoverycandidatetokenevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('source_profile_movement__isnull', False)), fields=('token', 'source_profile_movement', 'source_post', 'rare_type'), name='uq_candidate_token_movement_evidence'),
        ),
        migrations.AddConstraint(
            model_name='branddiscoverycandidatetokenevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_hit__isnull', False), ('source_profile_movement__isnull', True)), models.Q(('source_hit__isnull', True), ('source_profile_movement__isnull', False)), _connector='OR'), name='ck_candidate_token_one_source'),
        ),
    ]
