# Generated by Django 5.2.16 on 2026-09-23 23:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_product_keys(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    for product_id in (
        Product.objects.filter(product_key__isnull=True)
        .values_list("id", flat=True)
        .iterator(chunk_size=1000)
    ):
        Product.objects.filter(pk=product_id, product_key__isnull=True).update(
            product_key=uuid.uuid4()
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_profile_movement_token_evidence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["display_name", "id"]},
        ),
        migrations.AddField(
            model_name="product",
            name="product_key",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_product_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="product",
            name="product_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("llm-model", "LLM model"),
                    ("other-ai-model", "Other AI model"),
                    ("agent-harness", "Agent harness"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="repo_id",
            field=models.CharField(
                blank=True,
                db_collation="case_insensitive",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PostBrandProduct",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "post",
                        "brand",
                        "product",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("observed_name", models.TextField()),
                ("source_evidence", models.JSONField(default=dict)),
                ("verification_policy_version", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        db_column="brand_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_evidence",
                        to="core.brand",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_edges",
                        to="core.post",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_evidence",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "posts_brands_products",
                "indexes": [
                    models.Index(
                        fields=["product", "post"], name="idx_pbp_product_post"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVerificationProposal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("proposal_key", models.CharField(max_length=64, unique=True)),
                (
                    "account_handle_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("observed_name", models.TextField()),
                (
                    "candidate_repo_id",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("account_evidence", models.JSONField(default=dict)),
                ("hf_evidence", models.JSONField(default=dict)),
                (
                    "hf_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("missing", "Missing"),
                            ("private", "Private"),
                            ("timeout", "Timeout"),
                            ("throttled", "Throttled"),
                            ("error", "Error"),
                            ("malformed", "Malformed"),
                            ("deferred", "Deferred"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("policy_version", models.CharField(max_length=128)),
                ("rule_trace", models.JSONField(default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer", models.TextField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_verification_proposals",
                        to="core.account",
                    ),
                ),
                (
                    "proposed_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_verification_proposals",
                        to="core.brand",
                    ),
                ),
                (
                    "proposed_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_verification_proposals",
                        to="core.branddiscoverycandidate",
                    ),
                ),
                (
                    "resolved_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_proposals",
                        to="core.product",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        db_column="source_post_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_verification_proposals",
                        to="core.post",
                    ),
                ),
                (
                    "source_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_verification_proposals",
                        to="core.modelrelease",
                    ),
                ),
            ],
            options={
                "db_table": "product_verification_proposals",
                "indexes": [
                    models.Index(
                        fields=["hf_outcome", "next_attempt_at"],
                        name="idx_product_proposal_due",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("proposed_brand__isnull", False),
                                ("proposed_candidate__isnull", True),
                            ),
                            models.Q(
                                ("proposed_brand__isnull", True),
                                ("proposed_candidate__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_product_proposal_one_owner",
                    )
                ],
            },
        ),
    ]
