# Generated by Django 5.2.16 on 2026-09-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_product_options_product_product_key_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__isnull", True),
                    ("type__in", ["llm-model", "other-ai-model", "agent-harness"]),
                    _connector="OR",
                ),
                name="ck_product_type",
            ),
        ),
    ]
