# Generated by Django 5.2.16 on 2026-09-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_product_ck_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productverificationproposal",
            name="verification_claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productverificationproposal",
            name="verification_claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
