# Generated by Django 5.2.16 on 2026-09-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_merge_hf_catalog_rare_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_fingerprint', models.CharField(max_length=64)),
                ('source_chunk_fingerprint', models.CharField(max_length=64)),
                ('source_language', models.CharField(max_length=16)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('target_language', models.CharField(max_length=8)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('translated_text', models.TextField()),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='translation_chunks', to='core.post')),
            ],
            options={
                'db_table': 'post_translation_chunks',
                'constraints': [models.UniqueConstraint(fields=('post', 'source_content_fingerprint', 'source_language', 'prompt_version', 'model', 'target_language', 'chunk_index'), name='uq_post_translation_chunk_identity'), models.CheckConstraint(condition=models.Q(('target_language__in', ['en', 'zh-Hans', 'ja'])), name='ck_post_translation_chunk_target'), models.CheckConstraint(condition=models.Q(('translated_text', ''), _negated=True), name='ck_post_translation_chunk_text')],
            },
        ),
    ]
