# Generated by Django 5.2.16 on 2026-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_posttranslationchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='postenrichmentstate',
            name='translation_diagnostics',
            field=models.JSONField(db_default={}, default=dict),
        ),
    ]
