# Generated by Django 5.2.16 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_postenrichmentstate_translation_diagnostics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="sexs",
            new_name="sex",
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("given_name", models.TextField(blank=True, null=True)),
                ("family_name", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="und", max_length=35)),
                ("name_type", models.CharField(default="professional", max_length=32)),
                ("name_order", models.CharField(default="unknown", max_length=24)),
                ("origin", models.CharField(default="source", max_length=24)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("needs_review", "Needs review"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("review_history", models.JSONField(default=list)),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_names",
                        to="core.personname",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "db_table": "people_names",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="english_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="english_for",
                to="core.personname",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="primary_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for",
                to="core.personname",
            ),
        ),
        migrations.CreateModel(
            name="PersonNameEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_kind", models.CharField(max_length=40)),
                ("source_reference", models.TextField()),
                ("source_text", models.TextField(blank=True, default="")),
                ("supports_fields", models.JSONField(default=list)),
                ("observed_at", models.DateTimeField()),
                ("collection_method", models.CharField(max_length=64)),
                ("review_reason", models.TextField(blank=True, default="")),
                ("evidence_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.personname",
                    ),
                ),
            ],
            options={
                "db_table": "people_name_evidence",
            },
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.UniqueConstraint(
                fields=("person", "fingerprint"), name="uq_person_name_fingerprint"
            ),
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.CheckConstraint(
                condition=models.Q(("full_name", ""), _negated=True),
                name="ck_person_name_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review_status__in", ["pending", "confirmed", "rejected"])
                ),
                name="ck_person_name_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "origin__in",
                        ["source", "owner", "converted", "generated", "legacy"],
                    )
                ),
                name="ck_person_name_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="personname",
            constraint=models.CheckConstraint(
                condition=models.Q(("derived_from", models.F("pk")), _negated=True),
                name="ck_person_name_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="personnameevidence",
            constraint=models.UniqueConstraint(
                fields=("name", "evidence_hash"), name="uq_person_name_evidence"
            ),
        ),
        migrations.AddConstraint(
            model_name="personnameevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="ck_person_name_source",
            ),
        ),
    ]
