# Generated by Django 5.2.16 on 2026-10-01 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_person_name_provenance_and_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMediaObject",
            fields=[
                (
                    "sha256",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("storage_name", models.TextField()),
                ("media_type", models.CharField(max_length=64)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_media_objects",
            },
        ),
        migrations.CreateModel(
            name="PersonText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("language", models.CharField(max_length=35)),
                ("text", models.TextField()),
                ("source_reference", models.TextField()),
                ("version_hash", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "db_table": "people_texts",
            },
        ),
        migrations.CreateModel(
            name="PersonTextTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=35)),
                ("text", models.TextField()),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.persontext",
                    ),
                ),
            ],
            options={
                "db_table": "people_text_translations",
            },
        ),
        migrations.CreateModel(
            name="StaffCollectionWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("policy_version", models.CharField(default="staff-v1", max_length=32)),
                ("state", models.CharField(default="queued", max_length=24)),
                ("context", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_work",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_collection_work",
            },
        ),
        migrations.CreateModel(
            name="StaffIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=512)),
                ("fingerprint", models.CharField(max_length=64)),
                ("eligibility", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_intakes",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_intakes",
            },
        ),
        migrations.CreateModel(
            name="PersonMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("source_url", models.URLField(max_length=4096)),
                (
                    "original_url",
                    models.URLField(blank=True, default="", max_length=4096),
                ),
                ("source_kind", models.CharField(max_length=40)),
                (
                    "discovery_provider",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("kind", models.CharField(default="image", max_length=24)),
                ("availability", models.CharField(default="unfetched", max_length=24)),
                ("source_verified", models.BooleanField(default=False)),
                ("individual_portrait", models.BooleanField(default=False)),
                ("suitability", models.CharField(default="pending", max_length=24)),
                ("reuse_status", models.CharField(default="unknown", max_length=24)),
                ("verification_reason", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(default=dict)),
                ("review_history", models.JSONField(default=list)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.person",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributions",
                        to="core.staffmediaobject",
                    ),
                ),
            ],
            options={
                "db_table": "people_media",
            },
        ),
        migrations.CreateModel(
            name="StaffProviderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("fingerprint", models.CharField(max_length=64)),
                ("run_id", models.UUIDField()),
                ("parameters", models.JSONField(default=dict)),
                ("state", models.CharField(default="reserved", max_length=24)),
                ("response", models.JSONField(default=dict)),
                (
                    "error_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_requests",
                        to="core.person",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staffcollectionwork",
                    ),
                ),
            ],
            options={
                "db_table": "staff_provider_requests",
            },
        ),
        migrations.AddConstraint(
            model_name="persontext",
            constraint=models.UniqueConstraint(
                fields=("person", "kind", "source_reference", "version_hash"),
                name="uq_person_text_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="persontexttranslation",
            constraint=models.UniqueConstraint(
                fields=("original", "language", "provider", "model", "prompt_version"),
                name="uq_person_text_translation",
            ),
        ),
        migrations.AddIndex(
            model_name="staffcollectionwork",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="idx_staff_work_due"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcollectionwork",
            constraint=models.UniqueConstraint(
                fields=("person", "fingerprint", "policy_version"),
                name="uq_staff_work_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcollectionwork",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "queued",
                            "running",
                            "retry_due",
                            "complete",
                            "needs_review",
                            "needs_evidence",
                        ],
                    )
                ),
                name="ck_staff_work_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcollectionwork",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("state", "running"),
                    ),
                    models.Q(
                        models.Q(("state", "running"), _negated=True),
                        ("lease_expires_at__isnull", True),
                        ("lease_token__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_staff_work_lease",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffintake",
            constraint=models.UniqueConstraint(
                fields=("source_key", "fingerprint"), name="uq_staff_intake_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="personmedia",
            constraint=models.UniqueConstraint(
                fields=("person", "fingerprint"), name="uq_person_media_attribution"
            ),
        ),
        migrations.AddConstraint(
            model_name="personmedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_verified", False),
                    models.Q(("verification_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_media_verification_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="personmedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("suitability__in", ["pending", "approved", "rejected"])
                ),
                name="ck_media_suitability",
            ),
        ),
        migrations.AddConstraint(
            model_name="personmedia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reuse_status__in", ["unknown", "permitted", "restricted"])
                ),
                name="ck_media_reuse",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffproviderrequest",
            constraint=models.UniqueConstraint(
                fields=("person", "provider", "fingerprint"),
                name="uq_staff_request_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffproviderrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["reserved", "complete", "needs_review"])
                ),
                name="ck_staff_request_state",
            ),
        ),
    ]
