# Generated by Django 5.2.16 on 2026-10-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_staff_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentityCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(max_length=24)),
                ('reviewer', models.TextField()),
                ('reason', models.TextField()),
                ('request', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'people_identity_corrections',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_identities', to='core.person'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('pk')), _negated=True), name='ck_person_merge_not_self'),
        ),
        migrations.AddField(
            model_name='personidentitycorrection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_corrections_from', to='core.person'),
        ),
        migrations.AddField(
            model_name='personidentitycorrection',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_corrections_to', to='core.person'),
        ),
        migrations.AddConstraint(
            model_name='personidentitycorrection',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['merge', 'split', 'confirm_account'])), name='ck_identity_correction_kind'),
        ),
        migrations.AddConstraint(
            model_name='personidentitycorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewer', ''), _negated=True), models.Q(('reason', ''), _negated=True), models.Q(('request_key', ''), _negated=True)), name='ck_identity_correction_review'),
        ),
    ]
    operations += [migrations.RunSQL(
        """
        CREATE FUNCTION protect_identity_correction() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'Identity correction journals are append-only'
            USING ERRCODE = '23514';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER protect_identity_correction
          BEFORE UPDATE OR DELETE ON people_identity_corrections
          FOR EACH ROW EXECUTE FUNCTION protect_identity_correction();
        """,
        "DROP TRIGGER protect_identity_correction ON people_identity_corrections; "
        "DROP FUNCTION protect_identity_correction();",
    )]
