# Generated by Django 5.2.16 on 2026-10-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_person_identity_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbrandaffiliation',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personbrandaffiliation',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_claims', to='core.personbrandaffiliation'),
        ),
        migrations.AddField(
            model_name='personbrandaffiliation',
            name='superseded_by_reviewer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='personbrandaffiliation',
            name='supersession_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
    operations += [migrations.RunSQL(
        """
        CREATE FUNCTION g1_check_affiliation_replacement() RETURNS trigger AS $$
        DECLARE current_row record; replacement record;
        BEGIN
          SELECT * INTO current_row FROM people_brand_affiliations WHERE id = NEW.id;
          IF current_row.superseded_by_id IS NOT NULL THEN
            SELECT * INTO replacement FROM people_brand_affiliations WHERE id = current_row.superseded_by_id;
            IF current_row.person_id IS DISTINCT FROM replacement.person_id
              OR current_row.brand_id IS DISTINCT FROM replacement.brand_id
              OR current_row.brand_discovery_candidate_id IS DISTINCT FROM replacement.brand_discovery_candidate_id
              OR current_row.superseded_at IS NULL
              OR btrim(current_row.superseded_by_reviewer) = ''
              OR btrim(current_row.supersession_reason) = '' THEN
              RAISE EXCEPTION 'Replacement needs same person, organization and review' USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
              WITH RECURSIVE chain(id, next_id) AS (
                SELECT id, superseded_by_id FROM people_brand_affiliations WHERE id = current_row.superseded_by_id
                UNION
                SELECT p.id, p.superseded_by_id FROM people_brand_affiliations p JOIN chain c ON p.id = c.next_id
              ) SELECT 1 FROM chain WHERE id = current_row.id
            ) THEN
              RAISE EXCEPTION 'Replacement cycle' USING ERRCODE = '23514';
            END IF;
          END IF;
          IF EXISTS (SELECT 1 FROM people_brand_affiliations p
            WHERE p.superseded_by_id = NEW.id AND (
              p.person_id IS DISTINCT FROM current_row.person_id
              OR p.brand_id IS DISTINCT FROM current_row.brand_id
              OR p.brand_discovery_candidate_id IS DISTINCT FROM current_row.brand_discovery_candidate_id)) THEN
            RAISE EXCEPTION 'Replacement dependencies must move together' USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END; $$ LANGUAGE plpgsql;
        CREATE CONSTRAINT TRIGGER g1_affiliation_replacement
          AFTER INSERT OR UPDATE ON people_brand_affiliations DEFERRABLE INITIALLY DEFERRED
          FOR EACH ROW EXECUTE FUNCTION g1_check_affiliation_replacement();
        CREATE FUNCTION g1_preserve_affiliation_review() RETURNS trigger AS $$
        BEGIN
          IF OLD.superseded_by_id IS NOT NULL AND (
            NEW.superseded_by_id IS DISTINCT FROM OLD.superseded_by_id
            OR NEW.superseded_at IS DISTINCT FROM OLD.superseded_at
            OR NEW.superseded_by_reviewer IS DISTINCT FROM OLD.superseded_by_reviewer
            OR NEW.supersession_reason IS DISTINCT FROM OLD.supersession_reason) THEN
            RAISE EXCEPTION 'Retain the recorded replacement review' USING ERRCODE = '23514';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER g1_preserve_affiliation_review BEFORE UPDATE ON people_brand_affiliations
          FOR EACH ROW EXECUTE FUNCTION g1_preserve_affiliation_review();
        """,
        "DROP TRIGGER g1_preserve_affiliation_review ON people_brand_affiliations; "
        "DROP FUNCTION g1_preserve_affiliation_review(); "
        "DROP TRIGGER g1_affiliation_replacement ON people_brand_affiliations; "
        "DROP FUNCTION g1_check_affiliation_replacement();",
    )]
