# Generated by Django 5.2.16 on 2026-10-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_reviewed_affiliation_replacement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='persontext',
            name='uq_person_text_version',
        ),
        migrations.AddField(
            model_name='persontext',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='core.personbrandaffiliation'),
        ),
        migrations.AddField(
            model_name='persontext',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_texts', to='core.persontext'),
        ),
        migrations.AddField(
            model_name='persontext',
            name='origin',
            field=models.CharField(default='source', max_length=24),
        ),
        migrations.AddField(
            model_name='persontext',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persontext',
            name='review_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='personname',
            name='review_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='persontext',
            constraint=models.UniqueConstraint(fields=('person', 'affiliation', 'kind', 'source_reference', 'version_hash'), name='uq_person_text_version', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='persontext',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['source', 'translation', 'summary', 'unknown'])), name='ck_person_text_origin'),
        ),
        migrations.AddConstraint(
            model_name='persontext',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'confirmed', 'rejected'])), name='ck_person_text_review'),
        ),
        migrations.AddConstraint(
            model_name='persontext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'title'), _negated=True), ('affiliation__isnull', False), _connector='OR'), name='ck_person_title_affiliation'),
        ),
    ]
    operations += [migrations.RunSQL(
        """
        CREATE FUNCTION g1_preserve_staff_source() RETURNS trigger AS $$
        BEGIN
          IF TG_TABLE_NAME = 'staff_intakes' THEN
            IF (NEW.source_key, NEW.fingerprint, NEW.payload, NEW.observed_at, NEW.created_at)
              IS DISTINCT FROM (OLD.source_key, OLD.fingerprint, OLD.payload, OLD.observed_at, OLD.created_at) THEN
              RAISE EXCEPTION 'Retain the intake source version' USING ERRCODE = '23514';
            END IF;
          ELSE
            IF (NEW.kind, NEW.language, NEW.text, NEW.source_reference, NEW.version_hash,
                NEW.observed_at, NEW.created_at, NEW.origin, NEW.derived_from_id, NEW.affiliation_id)
              IS DISTINCT FROM (OLD.kind, OLD.language, OLD.text, OLD.source_reference, OLD.version_hash,
                OLD.observed_at, OLD.created_at, OLD.origin, OLD.derived_from_id, OLD.affiliation_id) THEN
              RAISE EXCEPTION 'Create a new text version to retain the original' USING ERRCODE = '23514';
            END IF;
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER g1_preserve_intake BEFORE UPDATE ON staff_intakes
          FOR EACH ROW EXECUTE FUNCTION g1_preserve_staff_source();
        CREATE TRIGGER g1_preserve_text BEFORE UPDATE ON people_texts
          FOR EACH ROW EXECUTE FUNCTION g1_preserve_staff_source();
        CREATE FUNCTION g1_check_text_links() RETURNS trigger AS $$
        DECLARE current_row record; role_person uuid; parent record;
        BEGIN
          SELECT * INTO current_row FROM people_texts WHERE id = NEW.id;
          IF current_row.affiliation_id IS NOT NULL THEN
            SELECT person_id INTO role_person FROM people_brand_affiliations WHERE id = current_row.affiliation_id;
            IF current_row.person_id IS DISTINCT FROM role_person THEN
              RAISE EXCEPTION 'Text affiliation must belong to the same person' USING ERRCODE = '23514';
            END IF;
          END IF;
          IF current_row.derived_from_id IS NOT NULL THEN
            SELECT * INTO parent FROM people_texts WHERE id = current_row.derived_from_id;
            IF current_row.person_id IS DISTINCT FROM parent.person_id
              OR current_row.affiliation_id IS DISTINCT FROM parent.affiliation_id THEN
              RAISE EXCEPTION 'Derived text must belong to the same person and affiliation' USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
              WITH RECURSIVE chain(id, parent_id) AS (
                SELECT id, derived_from_id FROM people_texts WHERE id = current_row.derived_from_id
                UNION SELECT p.id, p.derived_from_id FROM people_texts p JOIN chain c ON p.id = c.parent_id
              ) SELECT 1 FROM chain WHERE id = current_row.id
            ) THEN
              RAISE EXCEPTION 'Text derivation cycle' USING ERRCODE = '23514';
            END IF;
          END IF;
          IF EXISTS (SELECT 1 FROM people_texts child WHERE child.derived_from_id = NEW.id AND (
              child.person_id IS DISTINCT FROM current_row.person_id
              OR child.affiliation_id IS DISTINCT FROM current_row.affiliation_id)) THEN
            RAISE EXCEPTION 'Text dependencies must move together' USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END; $$ LANGUAGE plpgsql;
        CREATE CONSTRAINT TRIGGER g1_text_links AFTER INSERT OR UPDATE ON people_texts
          DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION g1_check_text_links();
        CREATE FUNCTION g1_check_affiliation_text_owner() RETURNS trigger AS $$
        BEGIN
          IF EXISTS (SELECT 1 FROM people_texts t JOIN people_brand_affiliations a ON a.id = t.affiliation_id
                     WHERE a.id = NEW.id AND t.person_id <> a.person_id) THEN
            RAISE EXCEPTION 'Affiliation texts must move with their person' USING ERRCODE = '23514';
          END IF;
          RETURN NULL;
        END; $$ LANGUAGE plpgsql;
        CREATE CONSTRAINT TRIGGER g1_affiliation_text_owner AFTER UPDATE ON people_brand_affiliations
          DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION g1_check_affiliation_text_owner();
        """,
        "DROP TRIGGER g1_affiliation_text_owner ON people_brand_affiliations; "
        "DROP FUNCTION g1_check_affiliation_text_owner(); "
        "DROP TRIGGER g1_text_links ON people_texts; DROP FUNCTION g1_check_text_links(); "
        "DROP TRIGGER g1_preserve_intake ON staff_intakes; "
        "DROP TRIGGER g1_preserve_text ON people_texts; DROP FUNCTION g1_preserve_staff_source();",
    )]
