# Generated by Django 5.2.17 on 2026-10-05 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_affiliation_text_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('development_key', models.CharField(max_length=160, unique=True)),
                ('anchor_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'editorial_stories',
            },
        ),
        migrations.CreateModel(
            name='EditorialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DateTimeField(unique=True)),
                ('cutoff', models.DateTimeField()),
                ('source_cycle_id', models.TextField()),
                ('state', models.CharField(default='running', max_length=24)),
                ('fence', models.PositiveIntegerField(default=1)),
                ('lease_until', models.DateTimeField()),
                ('packet', models.JSONField(default=dict)),
                ('decisions', models.JSONField(default=dict)),
                ('outcome', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'editorial_assessments',
                'indexes': [models.Index(fields=['state', 'interval'], name='idx_editorial_assessment_state')],
            },
        ),
        migrations.CreateModel(
            name='EditorialBudget',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('media_calls', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'editorial_budgets',
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_usd__gte', 0)), name='ck_editorial_budget_positive')],
            },
        ),
        migrations.CreateModel(
            name='EditorialEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track', models.CharField(max_length=16)),
                ('locale', models.CharField(max_length=12)),
                ('revision', models.PositiveIntegerField()),
                ('headline', models.CharField(max_length=160)),
                ('byline', models.CharField(max_length=500)),
                ('article', models.TextField()),
                ('importance', models.FloatField()),
                ('occurred_at', models.DateTimeField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('voice', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=160)),
                ('evidence', models.JSONField(default=dict)),
                ('selection', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='core.editorialassessment')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='core.editorialstory')),
            ],
            options={
                'db_table': 'editorial_editions',
            },
        ),
        migrations.CreateModel(
            name='EditorialHero',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.editorialedition')),
            ],
            options={
                'db_table': 'editorial_heroes',
            },
        ),
        migrations.CreateModel(
            name='EditorialCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=16)),
                ('state', models.CharField(default='sent', max_length=24)),
                ('reserved_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('budget_day', models.DateField()),
                ('response', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='core.editorialassessment')),
            ],
            options={
                'db_table': 'editorial_calls',
                'indexes': [models.Index(fields=['state', 'created_at'], name='idx_editorial_call_state')],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'stage'), name='uq_editorial_call_stage')],
            },
        ),
        migrations.CreateModel(
            name='EditorialPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_kind', models.CharField(max_length=24)),
                ('content_id', models.CharField(max_length=160)),
                ('source_platform', models.CharField(default='x', max_length=24)),
                ('revision_hash', models.CharField(max_length=64)),
                ('provenance', models.JSONField(default=dict)),
                ('treatment', models.TextField(blank=True, default='')),
                ('mode', models.CharField(max_length=16)),
                ('state', models.CharField(default='selected', max_length=24)),
                ('provider_task_id', models.CharField(blank=True, default='', max_length=160)),
                ('poll_count', models.PositiveIntegerField(default=0)),
                ('next_poll_at', models.DateTimeField(null=True)),
                ('poll_lease_until', models.DateTimeField(null=True)),
                ('generated_storage_name', models.TextField(blank=True, default='')),
                ('generated_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.editorialassessment')),
                ('person_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.personmedia')),
                ('source_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staffmediaobject')),
            ],
            options={
                'db_table': 'editorial_pictures',
                'indexes': [models.Index(fields=['state', 'next_poll_at'], name='idx_editorial_picture_poll')],
                'constraints': [models.UniqueConstraint(fields=('content_kind', 'content_id', 'revision_hash'), name='uq_editorial_picture_revision')],
            },
        ),
        migrations.AddIndex(
            model_name='editorialedition',
            index=models.Index(fields=['track', 'locale', '-published_at', '-id'], name='idx_editorial_feed'),
        ),
        migrations.AddConstraint(
            model_name='editorialedition',
            constraint=models.UniqueConstraint(fields=('story', 'track', 'locale', 'revision'), name='uq_editorial_edition_revision'),
        ),
        migrations.AddConstraint(
            model_name='editorialedition',
            constraint=models.UniqueConstraint(fields=('story', 'track', 'locale', 'fingerprint'), name='uq_editorial_edition_evidence'),
        ),
        migrations.AddConstraint(
            model_name='editorialedition',
            constraint=models.UniqueConstraint(condition=models.Q(('track', 'chatter')), fields=('assessment', 'locale'), name='uq_editorial_chatter_interval'),
        ),
        migrations.AddConstraint(
            model_name='editorialedition',
            constraint=models.CheckConstraint(condition=models.Q(('track__in', ['chatter', 'pulse'])), name='ck_editorial_edition_track'),
        ),
        migrations.AddConstraint(
            model_name='editorialedition',
            constraint=models.CheckConstraint(condition=models.Q(('importance__gte', 0), ('importance__lte', 100)), name='ck_editorial_importance'),
        ),
    ]
