# Generated by Django 5.2.16 on 2026-10-06 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_affiliation_text_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialCompanyScan",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cursor", models.TextField(blank=True, default="")),
                ("population", models.PositiveIntegerField(default=0)),
                ("enumerated", models.PositiveIntegerField(default=0)),
                ("complete", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "official_company_scans",
            },
        ),
        migrations.CreateModel(
            name="OfficialCompanyAccountState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_hash", models.CharField(max_length=64)),
                ("evidence", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("decision", models.JSONField(default=dict)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                (
                    "policy_version",
                    models.CharField(blank=True, default="", max_length=96),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claim_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_company_state",
                        to="core.account",
                    ),
                ),
                (
                    "registered_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.brand",
                    ),
                ),
                (
                    "registered_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.company",
                    ),
                ),
                (
                    "initial_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.officialcompanyscan",
                    ),
                ),
            ],
            options={
                "db_table": "official_company_account_states",
            },
        ),
        migrations.CreateModel(
            name="OfficialCompanyBudget",
            fields=[
                (
                    "key",
                    models.CharField(max_length=96, primary_key=True, serialize=False),
                ),
                (
                    "reserved_usd",
                    models.DecimalField(decimal_places=10, default=0, max_digits=16),
                ),
                (
                    "spent_usd",
                    models.DecimalField(decimal_places=10, default=0, max_digits=16),
                ),
            ],
            options={
                "db_table": "official_company_budgets",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reserved_usd__gte", 0), ("spent_usd__gte", 0)
                        ),
                        name="ck_official_co_funding",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficialCompanyAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_hash", models.CharField(max_length=64)),
                ("evidence", models.JSONField(default=dict)),
                ("claim_token", models.CharField(max_length=64, unique=True)),
                ("model", models.CharField(max_length=128)),
                ("policy_version", models.CharField(max_length=96)),
                ("status", models.CharField(default="reserved", max_length=24)),
                ("decision", models.JSONField(default=dict)),
                ("reserved_usd", models.DecimalField(decimal_places=10, max_digits=16)),
                (
                    "actual_usd",
                    models.DecimalField(decimal_places=10, max_digits=16, null=True),
                ),
                ("budget_keys", models.JSONField(default=list)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_records",
                        to="core.officialcompanyaccountstate",
                    ),
                ),
            ],
            options={
                "db_table": "official_company_attempts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reserved_usd__gte", 0),
                            models.Q(
                                ("actual_usd__isnull", True),
                                ("actual_usd__gte", 0),
                                _connector="OR",
                            ),
                        ),
                        name="ck_official_co_attempt_cost",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="officialcompanyaccountstate",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="idx_official_co_due"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialcompanyaccountstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "claimed",
                            "accepted",
                            "rejected",
                            "review_needed",
                            "retry_due",
                            "registered",
                            "no_evidence",
                            "suppressed",
                        ],
                    )
                ),
                name="ck_official_co_status",
            ),
        ),
    ]
