# Generated by Django 5.2.17 on 2026-10-06 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_affiliation_text_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('source_type', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_key', models.CharField(max_length=128, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
                ('group_kind', models.CharField(default='series', max_length=32)),
                ('rule_kind', models.CharField(default='manual', max_length=32)),
                ('rule_version', models.PositiveSmallIntegerField(default=1)),
                ('rule_configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_product', models.ForeignKey(db_column='root_product_key', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', to_field='product_key')),
            ],
            options={
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='MeasurementSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_kind', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_subject', to='core.brand')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_subject', to='core.company')),
                ('product', models.OneToOneField(db_column='product_key', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_subject', to='core.product', to_field='product_key')),
                ('product_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='core.productgroup')),
            ],
            options={
                'db_table': 'measurement_subjects',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_hash', models.CharField(max_length=64, unique=True)),
                ('snapshot', models.JSONField()),
                ('reviewed_by', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'taxonomy_versions',
                'constraints': [models.CheckConstraint(condition=models.Q(('version_hash__regex', '^[0-9a-f]{64}$')), name='ck_taxonomy_hash')],
            },
        ),
        migrations.CreateModel(
            name='SubjectRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_kind', models.CharField(max_length=32)),
                ('effective_from_date', models.DateField(null=True)),
                ('effective_to_date', models.DateField(null=True)),
                ('effective_date_precision', models.CharField(default='unknown', max_length=16)),
                ('evidence', models.JSONField()),
                ('child_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='core.measurementsubject')),
                ('parent_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relationships', to='core.measurementsubject')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion')),
            ],
            options={
                'db_table': 'subject_relationships',
            },
        ),
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=32)),
                ('evidence_method', models.CharField(default='source_reported', max_length=32)),
                ('evidence', models.JSONField()),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.TextField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_product', models.ForeignKey(db_column='child_product_key', on_delete=django.db.models.deletion.PROTECT, related_name='parent_relationships', to='core.product', to_field='product_key')),
                ('parent_product', models.ForeignKey(db_column='parent_product_key', on_delete=django.db.models.deletion.PROTECT, related_name='child_relationships', to='core.product', to_field='product_key')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.datasource')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion')),
            ],
            options={
                'db_table': 'product_relationships',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_status', models.CharField(max_length=16)),
                ('membership_method', models.CharField(max_length=24)),
                ('rule_version', models.PositiveSmallIntegerField(null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productgroup')),
                ('product', models.ForeignKey(db_column='product_key', on_delete=django.db.models.deletion.PROTECT, to='core.product', to_field='product_key')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion')),
            ],
            options={
                'db_table': 'product_group_memberships',
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='rule_taxonomy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion'),
        ),
        migrations.CreateModel(
            name='PostSubjectAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assertion_key', models.CharField(max_length=64)),
                ('attribution_kind', models.CharField(max_length=24)),
                ('observed_name', models.TextField()),
                ('policy_version', models.CharField(max_length=128)),
                ('evidence', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.post')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.measurementsubject')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion')),
            ],
            options={
                'db_table': 'post_subject_attributions',
            },
        ),
        migrations.AddConstraint(
            model_name='measurementsubject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('company__isnull', False), ('product__isnull', True), ('product_group__isnull', True), ('subject_kind', 'company')), models.Q(('brand__isnull', False), ('company__isnull', True), ('product__isnull', True), ('product_group__isnull', True), ('subject_kind', 'brand')), models.Q(('brand__isnull', True), ('company__isnull', True), ('product__isnull', True), ('product_group__isnull', False), ('subject_kind', 'product_group')), models.Q(('brand__isnull', True), ('company__isnull', True), ('product__isnull', False), ('product_group__isnull', True), ('subject_kind', 'product')), _connector='OR'), name='ck_measurement_subject_target'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelationship',
            constraint=models.UniqueConstraint(fields=('taxonomy_version', 'parent_subject', 'child_subject', 'relation_kind'), name='uq_subject_relationship'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('parent_subject', models.F('child_subject')), _negated=True), name='ck_subject_relationship_self'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('relation_kind__in', ['owns', 'offers'])), name='ck_subject_relationship_kind'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('effective_date_precision__in', ['day', 'unknown'])), name='ck_subject_date_precision'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from_date__isnull', True), ('effective_to_date__isnull', True), ('effective_to_date__gt', models.F('effective_from_date')), _connector='OR'), name='ck_subject_date_order'),
        ),
        migrations.AddIndex(
            model_name='productrelationship',
            index=models.Index(fields=['taxonomy_version', 'parent_product', 'relationship_type'], name='product_rel_taxonom_438992_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelationship',
            index=models.Index(fields=['taxonomy_version', 'child_product', 'relationship_type'], name='product_rel_taxonom_b47de7_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrelationship',
            constraint=models.UniqueConstraint(fields=('taxonomy_version', 'parent_product', 'child_product', 'relationship_type'), name='uq_product_relationship'),
        ),
        migrations.AddConstraint(
            model_name='productrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('parent_product', models.F('child_product')), _negated=True), name='ck_product_relationship_self'),
        ),
        migrations.AddConstraint(
            model_name='productrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_type__in', ['new_version', 'finetune', 'adapter', 'quantized', 'merge'])), name='ck_product_relationship_type'),
        ),
        migrations.AddConstraint(
            model_name='productrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_method__in', ['source_reported', 'publisher_declared', 'provider_inferred', 'artifact_verified', 'our_inference'])), name='ck_product_relationship_method'),
        ),
        migrations.AddIndex(
            model_name='productgroupmembership',
            index=models.Index(fields=['taxonomy_version', 'group', 'membership_status'], name='product_gro_taxonom_67bbbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productgroupmembership',
            constraint=models.UniqueConstraint(fields=('taxonomy_version', 'group', 'product'), name='uq_product_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='productgroupmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('membership_method', 'manual_include'), ('membership_status', 'included'), ('rule_version__isnull', True)), models.Q(('membership_method', 'manual_exclude'), ('membership_status', 'excluded'), ('rule_version__isnull', True)), models.Q(('membership_method', 'rule_generated'), ('membership_status', 'included'), ('rule_version__gt', 0)), _connector='OR'), name='ck_product_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.CheckConstraint(condition=models.Q(('group_kind__in', ['series', 'family', 'collection'])), name='ck_product_group_kind'),
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.CheckConstraint(condition=models.Q(('rule_version__gt', 0)), name='ck_product_group_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('root_product__isnull', True), ('rule_kind', 'manual')), models.Q(('root_product__isnull', False), ('rule_kind', 'new_version_chain')), _connector='OR'), name='ck_product_group_rule_root'),
        ),
        migrations.AddIndex(
            model_name='postsubjectattribution',
            index=models.Index(fields=['subject', 'taxonomy_version', 'post'], name='post_subjec_subject_7a4dac_idx'),
        ),
        migrations.AddConstraint(
            model_name='postsubjectattribution',
            constraint=models.UniqueConstraint(fields=('post', 'subject', 'taxonomy_version', 'policy_version', 'assertion_key'), name='uq_post_subject_assertion'),
        ),
        migrations.AddConstraint(
            model_name='postsubjectattribution',
            constraint=models.CheckConstraint(condition=models.Q(('attribution_kind__in', ['direct_mention', 'legacy_brand'])), name='ck_post_subject_kind'),
        ),
        migrations.AddConstraint(
            model_name='postsubjectattribution',
            constraint=models.CheckConstraint(condition=models.Q(('assertion_key__regex', '^[0-9a-f]{64}$')), name='ck_post_subject_assertion_hash'),
        ),
    ]
