# Generated by Django 5.2.16 on 2026-10-06 12:06

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('core', '0065_official_company_discovery'),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name='OfficialCompanyListIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_hash', models.CharField(max_length=64)),
                ('list_id', models.BigIntegerField()),
                ('status', models.CharField(default='pending', max_length=24)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('claim_expires_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=128)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_list_intents', to='core.account')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_intents', to='core.officialcompanyaccountstate')),
            ],
            options={
                'db_table': 'official_company_list_intents',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_official_co_list_due')],
                'constraints': [models.UniqueConstraint(fields=('list_id', 'account'), name='uq_official_co_list_intent'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'retry_due', 'verify_needed', 'blocked_auth', 'confirmed', 'review_needed', 'suppressed'])), name='ck_official_co_list_status')],
            },
        ),
    ]
