# Generated by Django 5.2.17 on 2026-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_editorial_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialassessment',
            name='scope',
            field=models.CharField(default='editorial', max_length=80),
        ),
        migrations.AlterField(
            model_name='editorialassessment',
            name='interval',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='editorialassessment',
            constraint=models.UniqueConstraint(fields=('scope', 'interval'), name='uq_editorial_scope_interval'),
        ),
    ]
