# Generated by Django 5.2.17 on 2026-10-06 11:58

import re
import uuid

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    """Preserve native columns while changing every ORM account link to UUID.

    Backfill checkpoints are the nullable UUID columns; identities are never
    regenerated. A failed transactional migration rolls back the whole cutover.
    Compatibility triggers support existing native-ID SQL writers during rollout.
    """
    from django.db.utils import IntegrityError

    q = schema_editor.quote_name
    links = [
        ("twitter_list_memberships", "author_id", "account_key", False, True),
        ("posts", "author_id", "author_account_key", True, True),
        ("brands_accounts", "accounts_id", "account_key", False, False),
        ("companies_accounts", "author_id", "account_key", False, False),
        (
            "untracked_brand_promotion_evidence",
            "exact_matched_account_id",
            "matched_account_key",
            True,
            True,
        ),
        ("account_post_appearances", "author_id", "account_key", False, True),
        ("product_verification_proposals", "author_id", "account_key", False, True),
        ("people_accounts", "author_id", "account_key", False, False),
        ("account_profile_snapshots", "author_id", "account_key", False, False),
        ("profile_movement_candidates", "author_id", "account_key", False, True),
    ]
    with schema_editor.connection.cursor() as c:
        c.execute("SET LOCAL lock_timeout = '5s'")
        c.execute("SELECT pg_try_advisory_xact_lock(72620666)")
        if not c.fetchone()[0]:
            raise RuntimeError("account migration lock busy")
        c.execute(
            "INSERT INTO data_sources (id,name,source_type,enabled,metadata) VALUES ('x','X','social',false,'{}'),('hf','Hugging Face','model_catalog',false,'{}') ON CONFLICT (id) DO NOTHING"
        )
        c.execute("""ALTER TABLE accounts
          ADD COLUMN account_key uuid,
          ADD COLUMN data_source_id varchar(32),
          ADD COLUMN external_identifier text,
          ADD COLUMN normalized_identifier text COLLATE "C",
          ADD COLUMN identifier_kind varchar(32),
          ADD COLUMN normalized_handle text COLLATE "C",
          ADD COLUMN account_kind varchar(24) NOT NULL DEFAULT 'unknown',
          ADD COLUMN provider_metadata jsonb NOT NULL DEFAULT '{}'""")
        while True:
            c.execute("""UPDATE accounts SET account_key=gen_random_uuid(), data_source_id='x',
                external_identifier=author_id, normalized_identifier=author_id,
                identifier_kind='provider_id', normalized_handle=NULLIF(lower(handle COLLATE "C"),'')
                WHERE author_id IN (SELECT author_id FROM accounts WHERE account_key IS NULL LIMIT 5000)""")
            if c.rowcount == 0:
                break
        c.execute(
            "SELECT data_source_id,normalized_handle FROM accounts WHERE normalized_handle IS NOT NULL GROUP BY 1,2 HAVING count(*)>1 LIMIT 1"
        )
        if c.fetchone():
            raise IntegrityError(
                "duplicate source handles; reconcile explicitly before migration"
            )
        c.execute(
            "SELECT conrelid::regclass::text,conname,pg_get_constraintdef(oid) FROM pg_constraint WHERE contype='f' AND confrelid='accounts'::regclass"
        )
        legacy_fks = c.fetchall()
        for table, name, definition in legacy_fks:
            c.execute(f"ALTER TABLE {q(table)} DROP CONSTRAINT {q(name)}")
        c.execute(
            "SELECT conname FROM pg_constraint WHERE conrelid='accounts'::regclass AND contype='p'"
        )
        c.execute(f"ALTER TABLE accounts DROP CONSTRAINT {q(c.fetchone()[0])}")
        c.execute("DROP INDEX IF EXISTS uniq_accounts_handle_lower")
        c.execute(
            'ALTER TABLE accounts ALTER COLUMN author_id DROP NOT NULL, ALTER COLUMN handle TYPE text COLLATE "C", ALTER COLUMN account_key SET NOT NULL, ALTER COLUMN account_key SET DEFAULT gen_random_uuid(), ALTER COLUMN data_source_id SET NOT NULL, ALTER COLUMN external_identifier SET NOT NULL, ALTER COLUMN normalized_identifier SET NOT NULL, ALTER COLUMN identifier_kind SET NOT NULL'
        )
        c.execute("""ALTER TABLE accounts
            ADD CONSTRAINT accounts_pkey PRIMARY KEY(account_key),
            ADD CONSTRAINT accounts_author_id_key UNIQUE(author_id),
            ADD CONSTRAINT accounts_data_source_fk FOREIGN KEY(data_source_id) REFERENCES data_sources(id) DEFERRABLE INITIALLY DEFERRED,
            ADD CONSTRAINT uq_account_source_identifier UNIQUE(data_source_id,normalized_identifier),
            ADD CONSTRAINT ck_account_identity_nonempty CHECK(external_identifier<>'' AND normalized_identifier<>''),
            ADD CONSTRAINT ck_account_identifier_kind CHECK(identifier_kind IN ('provider_id','namespace')),
            ADD CONSTRAINT ck_account_kind CHECK(account_kind IN ('organization','individual','channel','unknown')),
            ADD CONSTRAINT ck_account_native_x_id CHECK((data_source_id='x' AND author_id IS NOT NULL AND author_id=external_identifier) OR (data_source_id<>'x' AND author_id IS NULL))""")
        c.execute(
            "CREATE UNIQUE INDEX uq_account_source_handle ON accounts(data_source_id,normalized_handle) WHERE normalized_handle IS NOT NULL"
        )
        c.execute("CREATE INDEX accounts_data_source_idx ON accounts(data_source_id)")
        # All defaults below serve explicit legacy native-ID SQL writes only.
        c.execute(r"""
        CREATE FUNCTION benchmark_account_identity_defaults() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.data_source_id IS NULL AND NEW.author_id IS NOT NULL THEN NEW.data_source_id := 'x'; END IF;
          IF NEW.data_source_id='x' THEN
            NEW.external_identifier := COALESCE(NULLIF(NEW.external_identifier,''),NEW.author_id);
            NEW.author_id := COALESCE(NEW.author_id,NEW.external_identifier);
            NEW.identifier_kind := COALESCE(NEW.identifier_kind,'provider_id');
          END IF;
          NEW.normalized_identifier := CASE WHEN NEW.data_source_id='hf' THEN lower(NEW.external_identifier COLLATE "C") ELSE NEW.external_identifier END;
          NEW.normalized_handle := NULLIF(lower(NEW.handle COLLATE "C"),'');
          RETURN NEW;
        END $$;
        CREATE TRIGGER benchmark_account_identity_defaults BEFORE INSERT OR UPDATE ON accounts
        FOR EACH ROW EXECUTE FUNCTION benchmark_account_identity_defaults();
        """)
        c.execute(r"""
        CREATE FUNCTION benchmark_account_link_compatibility() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE native_id text; generic_id uuid; linked_native text; linked_source text; rowdata jsonb;
        BEGIN
          rowdata := to_jsonb(NEW);
          native_id := rowdata->>TG_ARGV[0]; generic_id := (rowdata->>TG_ARGV[1])::uuid;
          IF TG_OP='UPDATE' AND native_id IS DISTINCT FROM (to_jsonb(OLD)->>TG_ARGV[0])
             AND generic_id IS NOT DISTINCT FROM ((to_jsonb(OLD)->>TG_ARGV[1])::uuid) THEN
            generic_id := NULL;
          ELSIF TG_OP='UPDATE' AND generic_id IS DISTINCT FROM ((to_jsonb(OLD)->>TG_ARGV[1])::uuid) THEN
            native_id := NULL;
          END IF;
          IF generic_id IS NULL AND native_id IS NOT NULL THEN
            SELECT account_key INTO generic_id FROM accounts WHERE author_id=native_id AND data_source_id='x';
            IF generic_id IS NULL THEN RAISE EXCEPTION 'unknown native X account' USING ERRCODE='23503'; END IF;
          END IF;
          IF generic_id IS NOT NULL THEN
            SELECT author_id,data_source_id INTO linked_native,linked_source FROM accounts WHERE account_key=generic_id;
            IF linked_source IS NULL THEN RAISE EXCEPTION 'unknown generic account' USING ERRCODE='23503'; END IF;
            IF TG_ARGV[2]='x' AND linked_source<>'x' THEN RAISE EXCEPTION 'X record requires X account' USING ERRCODE='23514'; END IF;
            IF native_id IS NOT NULL AND native_id IS DISTINCT FROM linked_native THEN RAISE EXCEPTION 'account identity mismatch' USING ERRCODE='23514'; END IF;
            native_id := linked_native;
          END IF;
          NEW := jsonb_populate_record(NEW,jsonb_build_object(TG_ARGV[0],native_id,TG_ARGV[1],generic_id));
          RETURN NEW;
        END $$;
        """)
        for table, native, new, nullable, xonly in links:
            c.execute(f"ALTER TABLE {q(table)} ADD COLUMN {q(new)} uuid")
            while True:
                c.execute(f"""WITH batch AS (
                    SELECT ctid FROM {q(table)} WHERE {q(new)} IS NULL
                    AND {q(native)} IS NOT NULL LIMIT 5000
                ) UPDATE {q(table)} t SET {q(new)}=a.account_key FROM accounts a, batch b
                WHERE t.ctid=b.ctid AND t.{q(native)}=a.author_id""")
                if c.rowcount == 0:
                    break
            c.execute(
                f"SELECT count(*) FROM {q(table)} WHERE {q(native)} IS NOT NULL AND {q(new)} IS NULL"
            )
            if c.fetchone()[0]:
                raise IntegrityError(f"unmapped account references: {table}")
            c.execute(
                """SELECT conname,pg_get_constraintdef(oid) FROM pg_constraint
                WHERE conrelid=%s::regclass AND contype IN ('p','u') AND
                (SELECT attnum FROM pg_attribute WHERE attrelid=%s::regclass AND attname=%s)=ANY(conkey)""",
                [table, table, native],
            )
            constraints = c.fetchall()
            for name, definition in constraints:
                c.execute(f"ALTER TABLE {q(table)} DROP CONSTRAINT {q(name)}")
                # pg_get_constraintdef quotes identifiers only when necessary.
                replacement = re.sub(r"\b" + re.escape(native) + r"\b", new, definition)
                c.execute(
                    f"ALTER TABLE {q(table)} ADD CONSTRAINT {q(name)} {replacement}"
                )
                # Old native-ID SQL ON CONFLICT targets remain valid during rollout.
                legacy_unique = definition.replace("PRIMARY KEY", "UNIQUE")
                c.execute(
                    f"ALTER TABLE {q(table)} ADD CONSTRAINT {q('compat_' + name)} {legacy_unique}"
                )
            # Django keeps explicit/implicit index names when a column changes.
            # Repoint those physical indexes too, retaining old unique SQL targets.
            c.execute(
                """SELECT idx.relname,pg_get_indexdef(i.indexrelid),i.indisunique
                FROM pg_index i JOIN pg_class idx ON idx.oid=i.indexrelid
                WHERE i.indrelid=%s::regclass AND NOT EXISTS
                  (SELECT 1 FROM pg_constraint co WHERE co.conindid=i.indexrelid)
                AND (SELECT attnum FROM pg_attribute WHERE attrelid=%s::regclass
                     AND attname=%s)=ANY(i.indkey)""",
                [table, table, native],
            )
            for index_name, definition, is_unique in c.fetchall():
                if (
                    "text_pattern_ops" in definition
                    or "varchar_pattern_ops" in definition
                ):
                    # Prefix indexes only apply to the retained native text column.
                    continue
                c.execute(f"DROP INDEX {q(index_name)}")
                c.execute(re.sub(r"\b" + re.escape(native) + r"\b", new, definition))
                if is_unique:
                    c.execute(
                        definition.replace(q(index_name), q("compat_" + index_name), 1)
                        if q(index_name) in definition
                        else definition.replace(
                            "INDEX " + index_name + " ",
                            "INDEX " + q("compat_" + index_name) + " ",
                            1,
                        )
                    )
            c.execute(f"ALTER TABLE {q(table)} ALTER COLUMN {q(native)} DROP NOT NULL")
            if not nullable:
                c.execute(f"ALTER TABLE {q(table)} ALTER COLUMN {q(new)} SET NOT NULL")
            c.execute(
                f"ALTER TABLE {q(table)} ADD CONSTRAINT {q(table + '_generic_account_fk')} FOREIGN KEY({q(new)}) REFERENCES accounts(account_key) DEFERRABLE INITIALLY DEFERRED"
            )
            c.execute(
                f"CREATE INDEX {q(table + '_generic_account_idx')} ON {q(table)}({q(new)})"
            )
            c.execute(
                f"CREATE TRIGGER benchmark_account_link BEFORE INSERT OR UPDATE ON {q(table)} FOR EACH ROW EXECUTE FUNCTION benchmark_account_link_compatibility('{native}','{new}','{'x' if xonly else 'any'}')"
            )
        # Keep native FKs as compatibility integrity checks; canonical ORM FKs use UUID.
        for table, name, definition in legacy_fks:
            c.execute(f"ALTER TABLE {q(table)} ADD CONSTRAINT {q(name)} {definition}")
        c.execute(
            "ALTER TABLE hf_orgs ADD COLUMN account_key uuid UNIQUE REFERENCES accounts(account_key) DEFERRABLE INITIALLY DEFERRED"
        )


def reverse(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    raise IrreversibleError(
        "Retain account identities and disable new consumers; use reviewed restore/forward-repair procedure, never destructive mixed-source reversal."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_measurement_taxonomy"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(forward, reverse)],
            state_operations=[
                migrations.AddField(
                    model_name="account",
                    name="account_key",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AddField(
                    model_name="account",
                    name="account_kind",
                    field=models.CharField(default="unknown", max_length=24),
                ),
                migrations.AddField(
                    model_name="account",
                    name="data_source",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.datasource",
                    ),
                ),
                migrations.AddField(
                    model_name="account",
                    name="external_identifier",
                    field=models.TextField(default=""),
                ),
                migrations.AddField(
                    model_name="account",
                    name="identifier_kind",
                    field=models.CharField(default="provider_id", max_length=32),
                ),
                migrations.AddField(
                    model_name="account",
                    name="normalized_handle",
                    field=models.TextField(db_collation="C", null=True),
                ),
                migrations.AddField(
                    model_name="account",
                    name="normalized_identifier",
                    field=models.TextField(db_collation="C", default=""),
                ),
                migrations.AddField(
                    model_name="account",
                    name="provider_metadata",
                    field=models.JSONField(default=dict),
                ),
                migrations.AddField(
                    model_name="accountpostappearance",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="accountprofilesnapshot",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="brandaccount",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="accounts_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="companyaccount",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="hforg",
                    name="account",
                    field=models.OneToOneField(
                        db_column="account_key",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_hf_org",
                        to="core.account",
                    ),
                ),
                migrations.AddField(
                    model_name="personaccount",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="post",
                    name="native_author_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="productverificationproposal",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="profilemovementcandidate",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="twitterlistmembership",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="author_id", editable=False, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="untrackedbrandpromotionevidence",
                    name="native_account_id",
                    field=models.TextField(
                        db_column="exact_matched_account_id", editable=False, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="account",
                    name="author_id",
                    field=models.TextField(null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name="account",
                    name="handle",
                    field=models.TextField(blank=True, db_collation="C", null=True),
                ),
                migrations.AlterField(
                    model_name="accountpostappearance",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearances",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="accountprofilesnapshot",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_snapshots",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="brandaccount",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="companyaccount",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="personaccount",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_links",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="post",
                    name="author",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="author_account_key",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="productverificationproposal",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_verification_proposals",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="profilemovementcandidate",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_movement_candidates",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="twitterlistmembership",
                    name="account",
                    field=models.ForeignKey(
                        db_column="account_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_list_memberships",
                        to="core.account",
                    ),
                ),
                migrations.AlterField(
                    model_name="untrackedbrandpromotionevidence",
                    name="exact_matched_account",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="matched_account_key",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="untracked_brand_promotion_evidence",
                        to="core.account",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.UniqueConstraint(
                        fields=("data_source", "normalized_identifier"),
                        name="uq_account_source_identifier",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("normalized_handle__isnull", False)),
                        fields=("data_source", "normalized_handle"),
                        name="uq_account_source_handle",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("external_identifier", ""), _negated=True),
                            models.Q(("normalized_identifier", ""), _negated=True),
                        ),
                        name="ck_account_identity_nonempty",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("identifier_kind__in", ["provider_id", "namespace"])
                        ),
                        name="ck_account_identifier_kind",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "account_kind__in",
                                ["organization", "individual", "channel", "unknown"],
                            )
                        ),
                        name="ck_account_kind",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="account",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("author_id", models.F("external_identifier")),
                                ("author_id__isnull", False),
                                ("data_source", "x"),
                            ),
                            models.Q(
                                models.Q(("data_source", "x"), _negated=True),
                                ("author_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_account_native_x_id",
                    ),
                ),
            ],
        )
    ]
