# Generated by Django 5.2.17 on 2026-10-06 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_account_source_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCollectionContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_hash', models.CharField(max_length=64, unique=True)),
                ('catalog_hash', models.CharField(max_length=64)),
                ('mapping_hash', models.CharField(max_length=64)),
                ('methodology_hash', models.CharField(max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('catalog_snapshot', models.JSONField()),
                ('source_configuration', models.JSONField()),
                ('methodology', models.JSONField()),
                ('reviewed_by', models.TextField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'metric_collection_contracts',
            },
        ),
        migrations.CreateModel(
            name='MetricCollectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('ingestion_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField()),
                ('observed_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('source_as_of', models.DateTimeField(null=True)),
                ('source_url', models.TextField(default='')),
                ('request_params', models.JSONField(default=dict)),
                ('source_metadata', models.JSONField(default=dict)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('payload_sha256', models.CharField(max_length=64, null=True)),
                ('raw_payload', models.JSONField(null=True)),
                ('error_code', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'metric_collection_runs',
            },
        ),
        migrations.CreateModel(
            name='MetricObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identifier', models.CharField(max_length=256)),
                ('source_subject_kind', models.CharField(max_length=32)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimensions', models.JSONField(default=dict)),
                ('source_metadata', models.JSONField(default=dict)),
                ('observation_key', models.CharField(max_length=64)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('published_at', models.DateTimeField(null=True)),
                ('published_date', models.DateField(null=True)),
                ('publication_precision', models.CharField(default='unknown', max_length=16)),
                ('error_code', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'metric_observations',
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'metric_types',
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_value', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('float_value', models.FloatField(null=True)),
                ('temporal_status', models.CharField(default='unknown', max_length=16)),
                ('source_timezone', models.CharField(default='unknown', max_length=64)),
                ('as_of_at', models.DateTimeField(null=True)),
                ('as_of_date', models.DateField(null=True)),
                ('window_start_at', models.DateTimeField(null=True)),
                ('window_end_at', models.DateTimeField(null=True)),
                ('period_label_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'metric_values',
            },
        ),
        migrations.CreateModel(
            name='SourceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('version', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=64)),
                ('value_kind', models.CharField(max_length=16)),
                ('quantity_form', models.CharField(max_length=16)),
                ('value_role', models.CharField(default='value', max_length=32)),
                ('measurement_kind', models.CharField(max_length=24)),
                ('window_mode', models.CharField(default='none', max_length=16)),
                ('window_amount', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('window_unit', models.CharField(max_length=24, null=True)),
                ('window_duration_basis', models.CharField(default='none', max_length=16)),
                ('window_alignment', models.CharField(max_length=32, null=True)),
                ('source_timezone', models.CharField(default='unknown', max_length=64)),
                ('required', models.BooleanField(default=True)),
                ('definition_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'source_metrics',
            },
        ),
        migrations.CreateModel(
            name='SourceSubjectMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_subject_kind', models.CharField(max_length=32)),
                ('identifier_scope', models.CharField(default='', max_length=128)),
                ('external_identifier', models.CharField(max_length=256)),
                ('normalized_identifier', models.CharField(db_collation='C', max_length=256)),
                ('mapping_hash', models.CharField(max_length=64)),
                ('evidence_url', models.URLField(max_length=2048)),
                ('identity_snapshot', models.JSONField(default=dict)),
                ('identifier_metadata', models.JSONField(default=dict)),
                ('reviewed_by', models.TextField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'source_subject_mappings',
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='adapter_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datasource',
            name='identifier_normalizer',
            field=models.CharField(default='exact-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='datasource',
            name='website_url',
            field=models.URLField(default='', max_length=2048),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['source_type'], name='idx_source_type'),
        ),
        migrations.RunSQL("UPDATE data_sources SET source_type='model_adoption' WHERE source_type='model_catalog'", migrations.RunSQL.noop),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['benchmark', 'model_adoption', 'social'])), name='ck_source_type'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.CheckConstraint(condition=models.Q(('enabled', False), models.Q(('adapter_key__isnull', False), models.Q(('adapter_key', ''), _negated=True)), _connector='OR'), name='ck_source_enabled_adapter'),
        ),
        migrations.AddField(
            model_name='metriccollectioncontract',
            name='taxonomy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxonomyversion'),
        ),
        migrations.AddField(
            model_name='metriccollectionrun',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metriccollectioncontract'),
        ),
        migrations.AddField(
            model_name='metriccollectionrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datasource'),
        ),
        migrations.AddField(
            model_name='metricobservation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.metriccollectionrun'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='core.metricobservation'),
        ),
        migrations.AddField(
            model_name='sourcemetric',
            name='metric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.metrictype'),
        ),
        migrations.AddField(
            model_name='sourcemetric',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datasource'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='source_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcemetric'),
        ),
        migrations.AddField(
            model_name='sourcesubjectmapping',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='core.metriccollectioncontract'),
        ),
        migrations.AddField(
            model_name='sourcesubjectmapping',
            name='publisher_account',
            field=models.ForeignKey(db_column='publisher_account_key', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account'),
        ),
        migrations.AddField(
            model_name='sourcesubjectmapping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datasource'),
        ),
        migrations.AddField(
            model_name='sourcesubjectmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.measurementsubject'),
        ),
        migrations.AddField(
            model_name='metricobservation',
            name='mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sourcesubjectmapping'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectioncontract',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='ck_contract_schema_version'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectioncontract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_hash__regex', '^[0-9a-f]{64}$')), name='ck_contract_contract_hash'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectioncontract',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_hash__regex', '^[0-9a-f]{64}$')), name='ck_contract_catalog_hash'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectioncontract',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_hash__regex', '^[0-9a-f]{64}$')), name='ck_contract_mapping_hash'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectioncontract',
            constraint=models.CheckConstraint(condition=models.Q(('methodology_hash__regex', '^[0-9a-f]{64}$')), name='ck_contract_methodology_hash'),
        ),
        migrations.AddIndex(
            model_name='metriccollectionrun',
            index=models.Index(fields=['contract', 'source', 'status', 'completed_at'], name='idx_metric_run_outcome'),
        ),
        migrations.AddIndex(
            model_name='metriccollectionrun',
            index=models.Index(fields=['batch_id'], name='idx_metric_run_batch'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('ingestion_key__regex', '^[0-9a-f]{64}$')), name='ck_metric_ingestion_key'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('payload_sha256__isnull', True), ('payload_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='ck_run_payload_hash'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'running')), models.Q(('completed_at__isnull', False), ('status__in', ['success', 'partial', 'failed', 'aborted'])), _connector='OR'), name='ck_run_terminal'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('success_count__lte', models.F('selected_count'))), name='ck_run_success_count'),
        ),
        migrations.AddIndex(
            model_name='sourcemetric',
            index=models.Index(fields=['metric_type', 'source'], name='idx_metric_type_source'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.UniqueConstraint(fields=('source', 'metric_key', 'version'), name='uq_source_metric_version'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ck_metric_version'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.CheckConstraint(condition=models.Q(('value_kind__in', ['integer', 'float'])), name='ck_metric_value_kind'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_form__in', ['count', 'score', 'rank', 'variance', 'ratio'])), name='ck_metric_quantity'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.CheckConstraint(condition=models.Q(('value_role__in', ['value', 'lower_bound', 'upper_bound'])), name='ck_metric_value_role'),
        ),
        migrations.AddConstraint(
            model_name='sourcemetric',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('measurement_kind', 'state'), ('window_alignment__isnull', True), ('window_amount__isnull', True), ('window_duration_basis', 'none'), ('window_mode', 'none'), ('window_unit__isnull', True)), models.Q(('measurement_kind', 'flow'), ('window_alignment__isnull', True), ('window_amount__isnull', True), ('window_duration_basis', 'none'), ('window_mode', 'since_origin'), ('window_unit__isnull', True)), models.Q(('measurement_kind', 'flow'), ('window_amount__gt', 0), ('window_amount__isnull', False), ('window_amount__lt', 1000000000), ('window_duration_basis__in', ['calendar', 'fixed', 'unknown']), ('window_mode__in', ['rolling', 'calendar', 'fixed']), ('window_unit__in', ['day', 'second']), ('window_unit__isnull', False), models.Q(models.Q(('window_alignment__in', ['source_local_midnight', 'provider_defined']), ('window_alignment__isnull', False), ('window_mode', 'calendar')), models.Q(('window_alignment__isnull', True), models.Q(('window_mode', 'calendar'), _negated=True)), _connector='OR')), _connector='OR'), name='ck_metric_kind_window'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['source_metric', 'observation'], name='idx_value_definition_obs'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['window_end_at'], name='idx_value_window_end'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['as_of_date'], name='idx_value_as_of_date'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.UniqueConstraint(fields=('observation', 'source_metric'), name='uq_metric_value'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('float_value__isnull', True), ('integer_value__isnull', False)), models.Q(('float_value__isnull', False), ('integer_value__isnull', True)), _connector='OR'), name='ck_value_one_number'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('integer_value__isnull', True), models.Q(('integer_value__gt', -1000000000000000000000000000000), ('integer_value__lt', 1000000000000000000000000000000)), _connector='OR'), name='ck_value_integer_finite'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('float_value__isnull', True), models.Q(('float_value__gt', float("-inf")), ('float_value__lt', float("inf"))), _connector='OR'), name='ck_value_float_finite'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('temporal_status__in', ['exact', 'date_only', 'unknown'])), name='ck_value_temporal_status'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('as_of_at__isnull', True), ('as_of_date__isnull', True), _connector='OR'), name='ck_value_state_precision'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('window_start_at__isnull', True), ('window_end_at__isnull', True), ('window_end_at__gt', models.F('window_start_at')), _connector='OR'), name='ck_value_window_order'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('as_of_at__isnull', True), models.Func(models.F('as_of_at'), function='isfinite', output_field=models.BooleanField()), _connector='OR'), name='ck_value_finite_as_of_at'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('as_of_date__isnull', True), models.Func(models.F('as_of_date'), function='isfinite', output_field=models.BooleanField()), _connector='OR'), name='ck_value_finite_as_of_date'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('window_start_at__isnull', True), models.Func(models.F('window_start_at'), function='isfinite', output_field=models.BooleanField()), _connector='OR'), name='ck_value_finite_window_start_at'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('window_end_at__isnull', True), models.Func(models.F('window_end_at'), function='isfinite', output_field=models.BooleanField()), _connector='OR'), name='ck_value_finite_window_end_at'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=models.Q(('period_label_date__isnull', True), models.Func(models.F('period_label_date'), function='isfinite', output_field=models.BooleanField()), _connector='OR'), name='ck_value_finite_period_label_date'),
        ),
        migrations.AddIndex(
            model_name='sourcesubjectmapping',
            index=models.Index(fields=['contract', 'subject'], name='idx_mapping_contract_subject'),
        ),
        migrations.AddIndex(
            model_name='sourcesubjectmapping',
            index=models.Index(fields=['source', 'normalized_identifier'], name='idx_mapping_source_identifier'),
        ),
        migrations.AddConstraint(
            model_name='sourcesubjectmapping',
            constraint=models.UniqueConstraint(fields=('contract', 'source', 'source_subject_kind', 'identifier_scope', 'normalized_identifier'), name='uq_source_subject_mapping'),
        ),
        migrations.AddConstraint(
            model_name='sourcesubjectmapping',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['repository', 'model', 'lab'])), name='ck_mapping_subject_kind'),
        ),
        migrations.AddConstraint(
            model_name='sourcesubjectmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_identifier', ''), _negated=True), models.Q(('normalized_identifier', ''), _negated=True)), name='ck_mapping_identifier'),
        ),
        migrations.AddConstraint(
            model_name='sourcesubjectmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_hash__regex', '^[0-9a-f]{64}$')), name='ck_mapping_hash'),
        ),
        migrations.AddIndex(
            model_name='metricobservation',
            index=models.Index(fields=['mapping', 'observed_at'], name='idx_observation_mapping_time'),
        ),
        migrations.AddIndex(
            model_name='metricobservation',
            index=models.Index(fields=['run', 'published_date'], name='idx_observation_publication'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.UniqueConstraint(fields=('run', 'observation_key'), name='uq_metric_observation'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('observation_key__regex', '^[0-9a-f]{64}$')), name='ck_observation_key'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['model', 'repository', 'lab', 'aggregate'])), name='ck_observation_kind'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['model', 'repository', 'lab']), ('mapping__isnull', True), _connector='OR'), name='ck_observation_aggregate'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error_code__isnull', True), ('status', 'ok')), models.Q(('error_code__isnull', False), ('status', 'error'), models.Q(('error_code', ''), _negated=True)), _connector='OR'), name='ck_observation_status'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_precision', 'instant'), ('published_at__isnull', False), ('published_date__isnull', True)), models.Q(('publication_precision', 'date'), ('published_at__isnull', True), ('published_date__isnull', False)), models.Q(('publication_precision', 'unknown'), ('published_at__isnull', True), ('published_date__isnull', True)), _connector='OR'), name='ck_observation_publication'),
        ),
    ]
