# Generated by Django 5.2.17 on 2026-10-05 07:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_editorial_picture_claim_scopes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='editorialstory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['anchor_ids'], name='idx_editorial_story_anchors'),
        ),
    ]
