# Generated by Django 5.2.16 on 2026-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_official_company_list_intents'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialCompanyOwnerCredential',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('encrypted_tokens', models.BinaryField()),
                ('status', models.CharField(default='ready', max_length=24)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'official_company_owner_credentials',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ready', 'refreshing', 'blocked'])), name='ck_official_co_credential')],
            },
        ),
    ]
