# Generated by Django 5.2.16 on 2026-10-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_shared_metrics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurementsubject',
            name='ck_measurement_subject_target',
        ),
        migrations.RemoveConstraint(
            model_name='metricobservation',
            name='ck_observation_kind',
        ),
        migrations.RemoveConstraint(
            model_name='metricobservation',
            name='ck_observation_aggregate',
        ),
        migrations.RemoveConstraint(
            model_name='sourcesubjectmapping',
            name='ck_mapping_subject_kind',
        ),
        migrations.AddField(
            model_name='measurementsubject',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_subject', to='core.account'),
        ),
        migrations.AddConstraint(
            model_name='measurementsubject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', True), ('brand__isnull', True), ('company__isnull', False), ('product__isnull', True), ('product_group__isnull', True), ('subject_kind', 'company')), models.Q(('account__isnull', True), ('brand__isnull', False), ('company__isnull', True), ('product__isnull', True), ('product_group__isnull', True), ('subject_kind', 'brand')), models.Q(('account__isnull', True), ('brand__isnull', True), ('company__isnull', True), ('product__isnull', True), ('product_group__isnull', False), ('subject_kind', 'product_group')), models.Q(('account__isnull', True), ('brand__isnull', True), ('company__isnull', True), ('product__isnull', False), ('product_group__isnull', True), ('subject_kind', 'product')), models.Q(('account__isnull', False), ('brand__isnull', True), ('company__isnull', True), ('product__isnull', True), ('product_group__isnull', True), ('subject_kind', 'account')), _connector='OR'), name='ck_measurement_subject_target'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['model', 'repository', 'lab', 'account', 'aggregate'])), name='ck_observation_kind'),
        ),
        migrations.AddConstraint(
            model_name='metricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['model', 'repository', 'lab', 'account']), ('mapping__isnull', True), _connector='OR'), name='ck_observation_aggregate'),
        ),
        migrations.AddConstraint(
            model_name='sourcesubjectmapping',
            constraint=models.CheckConstraint(condition=models.Q(('source_subject_kind__in', ['repository', 'model', 'lab', 'account'])), name='ck_mapping_subject_kind'),
        ),
    ]
