# Generated by Django 5.2.16 on 2026-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_official_company_owner_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialCompanyProviderState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('credential_revision', models.CharField(max_length=64)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=96)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'official_company_provider_states',
            },
        ),
    ]
