# Generated by Django 5.2.17 on 2026-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_editorial_anchor_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='editorialcall',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'media')), fields=('stage',), name='uq_editorial_media_stage'),
        ),
    ]
