# Generated by Django 5.2.16 on 2026-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_official_company_provider_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialcompanylistintent',
            name='add_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialcompanylistintent',
            name='add_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
