# Generated by Django 5.2.16 on 2026-10-07 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_account_measurement_subject"),
        ("core", "0068_editorial_media_stage_once"),
    ]

    operations = []
