# Generated by Django 5.2.17 on 2026-10-07 05:20

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0068_editorial_media_stage_once"),
    ]

    operations = [
        # Retain a possibly shared extension when reversing our own index.
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm", migrations.RunSQL.noop
        ),
        AddIndexConcurrently(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("text"), name="gin_trgm_ops"
                ),
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("quoted_text"),
                    name="gin_trgm_ops",
                ),
                name="idx_posts_editorial_context",
            ),
        ),
    ]
