# Generated by Django 5.2.16 on 2026-10-07 01:42

from django.db import migrations, models


def restore_legacy_pending(apps, schema_editor):
    state = apps.get_model("core", "OfficialCompanyAccountState")
    state.objects.using(schema_editor.connection.alias).filter(status="deferred").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_official_company_list_add_audit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='officialcompanyaccountstate',
            name='ck_official_co_status',
        ),
        migrations.AddField(
            model_name='officialcompanyaccountstate',
            name='candidate_policy_version',
            field=models.CharField(blank=True, default='', max_length=96),
        ),
        migrations.AddField(
            model_name='officialcompanyaccountstate',
            name='candidate_priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='officialcompanyaccountstate',
            index=models.Index(fields=['status', 'candidate_priority'], name='idx_official_co_priority'),
        ),
        migrations.AddConstraint(
            model_name='officialcompanyaccountstate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'claimed', 'accepted', 'rejected', 'review_needed', 'retry_due', 'registered', 'no_evidence', 'deferred', 'suppressed'])), name='ck_official_co_status'),
        ),
        migrations.RunPython(migrations.RunPython.noop, restore_legacy_pending),
    ]
