# Generated by Django 5.2.17 on 2026-10-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_editorial_context_search'),
        ('core', '0070_official_company_candidate_priority'),
    ]

    operations = [
    ]
