"""Rename Django state while retaining every deployed physical table name."""
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0074_official_company_generic_accounts")]

    operations = [
        migrations.RenameModel("TrendNarrativeRun", "OriginalContentRun"),
        migrations.RenameModel("TrendNarrativeProviderCall", "OriginalContentCall"),
        migrations.RenameModel("BrandTrendNarrative", "OriginalContent"),
        migrations.RenameModel("BrandTrendNarrativeText", "OriginalContentText"),
        migrations.RenameModel("TrendNarrativeVisibleRun", "OriginalContentSelection"),
        migrations.RenameModel("EditorialPicture", "ContentPicture"),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(
                sql="""
                SET LOCAL lock_timeout = '5s';
                ALTER TABLE trend_narrative_visible_runs ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
                UPDATE trend_narrative_visible_runs SET id = window_days;
                SET CONSTRAINTS ALL IMMEDIATE;
                ALTER TABLE trend_narrative_visible_runs DROP CONSTRAINT trend_narrative_visible_runs_pkey;
                ALTER TABLE trend_narrative_visible_runs ALTER COLUMN window_days DROP NOT NULL;
                ALTER TABLE trend_narrative_visible_runs ADD CONSTRAINT oc_selection_window_unique UNIQUE(window_days);
                ALTER TABLE trend_narrative_visible_runs ADD PRIMARY KEY(id);
                SELECT setval(pg_get_serial_sequence('trend_narrative_visible_runs', 'id'),
                    GREATEST(1000, COALESCE((SELECT MAX(id) FROM trend_narrative_visible_runs), 0)));
                """,
                reverse_sql="""
                SET LOCAL lock_timeout = '5s';
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM trend_narrative_visible_runs WHERE window_days IS NULL) THEN
                        RAISE EXCEPTION 'Cannot reverse selection expansion after featured cutover';
                    END IF;
                END $$;
                ALTER TABLE trend_narrative_visible_runs DROP COLUMN id;
                ALTER TABLE trend_narrative_visible_runs DROP CONSTRAINT oc_selection_window_unique;
                ALTER TABLE trend_narrative_visible_runs ALTER COLUMN window_days SET NOT NULL;
                ALTER TABLE trend_narrative_visible_runs ADD PRIMARY KEY(window_days);
                """,
            )],
            state_operations=[
                migrations.AlterField("originalcontentselection", "window_days", models.PositiveSmallIntegerField(null=True, blank=True, unique=True)),
                migrations.AddField("originalcontentselection", "id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
