# Generated by Django 5.2.17 on 2026-10-08 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_original_content_names'),
    ]

    operations = [
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='OriginalContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('url_snapshot', models.CharField(max_length=4096)),
                ('author_label_snapshot', models.TextField(blank=True, default='')),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_basis', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'original_content_sources',
                'ordering': ['position'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='originalcontent',
            name='uq_btn_run_brand',
        ),
        migrations.RemoveConstraint(
            model_name='originalcontent',
            name='ck_btn_output_shape',
        ),
        migrations.RemoveConstraint(
            model_name='originalcontentcall',
            name='ck_tnpc_stage',
        ),
        migrations.RemoveConstraint(
            model_name='originalcontentcall',
            name='ck_tnpc_sent_shape',
        ),
        migrations.RemoveConstraint(
            model_name='originalcontentcall',
            name='ck_tnpc_completed_shape',
        ),
        migrations.AddField(
            model_name='contentpicture',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='core.originalcontentrun'),
        ),
        migrations.AddField(
            model_name='contentpicture',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='core.originalcontenttext'),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='importance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='output_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='provenance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='selection',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='story_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='subject_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='originalcontent',
            name='workflow_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='actual_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='budget_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='budget_scope',
            field=models.CharField(default='headlines', max_length=80),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='kind',
            field=models.CharField(default='text', max_length=16),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='legacy_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='model',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='provenance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='reserved_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='workflow_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentcall',
            name='workflow_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='claim_owner',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='config_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='decisions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='execution_state',
            field=models.CharField(default='preparing', max_length=16),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='fence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='interval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='outcome',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='scope_key',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='workflow_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='originalcontentrun',
            name='workflow_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originalcontentselection',
            name='scope_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='originalcontentselection',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_by', to='core.originalcontenttext'),
        ),
        migrations.AddField(
            model_name='originalcontenttext',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='originalcontenttext',
            name='producing_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_texts', to='core.originalcontentcall'),
        ),
        migrations.AddField(
            model_name='originalcontenttext',
            name='provenance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='originalcontenttext',
            name='public_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='originalcontentcall',
            name='batch_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='originalcontentcall',
            name='request_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='originalcontentcall',
            name='stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='originalcontentrun',
            name='window_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originalcontentselection',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visible_pointers', to='core.originalcontentrun'),
        ),
        migrations.AddIndex(
            model_name='originalcontent',
            index=models.Index(fields=['subject_key', 'workflow_key', '-published_at', 'id'], name='idx_oc_subject_history'),
        ),
        migrations.AddIndex(
            model_name='originalcontent',
            index=models.Index(fields=['workflow_key', '-published_at'], name='idx_oc_workflow_feed'),
        ),
        migrations.AddIndex(
            model_name='originalcontentcall',
            index=models.Index(fields=['budget_scope', 'budget_day'], name='idx_oc_call_budget'),
        ),
        migrations.AddConstraint(
            model_name='originalcontent',
            constraint=models.UniqueConstraint(fields=('run', 'workflow_key', 'output_key'), name='uq_oc_run_output'),
        ),
        migrations.AddConstraint(
            model_name='originalcontent',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_key__isnull', True), ('workflow_key', 'brand-window'), _connector='OR'), fields=('run', 'brand_key_snapshot'), name='uq_oc_trend_brand'),
        ),
        migrations.AddConstraint(
            model_name='originalcontent',
            constraint=models.CheckConstraint(condition=models.Q(('importance__isnull', True), models.Q(('importance__gte', 0), ('importance__lte', 100)), _connector='OR'), name='ck_oc_importance'),
        ),
        migrations.AddConstraint(
            model_name='originalcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'prepared'), ('verified_at__isnull', True)), models.Q(('status', 'approved'), ('verified_at__isnull', False), models.Q(models.Q(models.Q(('workflow_key__isnull', True), ('workflow_key', 'brand-window'), _connector='OR'), ('headline_en__gt', ''), ('headline_zh_cn__gt', ''), ('secondary_en__gt', ''), ('secondary_zh_cn__gt', '')), ('workflow_key__in', ['social-brief', 'development-report']), _connector='OR')), ('status__in', ['held', 'unavailable', 'no_content', 'data_quality_unavailable']), _connector='OR'), name='ck_btn_output_shape'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('stage__gt', '')), name='ck_oc_call_stage'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_usd__gte', 0)), name='ck_oc_reservation'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['text', 'media'])), name='ck_oc_call_kind'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'media')), fields=('stage',), name='uq_oc_media_stage'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_import', True), models.Q(('request_hash__gt', ''), ('request_hash__isnull', False)), _connector='OR'), name='ck_oc_request_hash'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_import', True), models.Q(('sent_at__isnull', True), ('state', 'reserved')), models.Q(('error_code__startswith', 'pre_send:'), ('sent_at__isnull', True), ('state', 'failed')), models.Q(('sent_at__isnull', False), ('state__in', ['sent', 'completed', 'ambiguous', 'failed'])), _connector='OR'), name='ck_tnpc_sent_shape'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentcall',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_import', True), models.Q(('completed_at__isnull', True), ('state__in', ['reserved', 'sent', 'ambiguous', 'failed'])), models.Q(('completed_at__isnull', False), ('response_hash__gt', ''), ('state', 'completed')), _connector='OR'), name='ck_tnpc_completed_shape'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentrun',
            constraint=models.UniqueConstraint(fields=('source_cycle_id', 'scope_key', 'workflow_key'), name='uq_oc_run_cycle_scope'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('interval__isnull', False)), fields=('scope_key', 'interval'), name='uq_oc_run_interval'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_key', 'reservation-carryforward')), fields=('scope_key', 'workflow_key'), name='uq_oc_carryforward'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('run__isnull', False), ('text__isnull', True), ('window_days__isnull', False)), models.Q(('run__isnull', True), ('text__isnull', False), ('window_days__isnull', True)), _connector='OR'), name='ck_oc_selection_shape'),
        ),
        migrations.AddField(
            model_name='originalcontentsource',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_content_citations', to='core.post'),
        ),
        migrations.AddField(
            model_name='originalcontentsource',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.originalcontenttext'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentsource',
            constraint=models.UniqueConstraint(fields=('text', 'post'), name='uq_oc_source_post'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentsource',
            constraint=models.UniqueConstraint(fields=('text', 'position'), name='uq_oc_source_position'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentsource',
            constraint=models.CheckConstraint(condition=models.Q(('url_snapshot', ''), _negated=True), name='ck_oc_source_url'),
        ),
        migrations.AddConstraint(
            model_name='originalcontentsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hash_basis', 'legacy_unavailable'), ('source_hash__isnull', True)), models.Q(('hash_basis__in', ['writing_packet', 'legacy_packet']), ('source_hash__gt', ''), ('source_hash__isnull', False)), _connector='OR'), name='ck_oc_source_hash'),
        ),
    ]
