# Generated by Django 5.2.17 on 2026-10-08 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_original_content_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalcontent',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_narratives', to='core.originalcontentrun'),
        ),
        migrations.AlterField(
            model_name='originalcontentcall',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_calls', to='core.originalcontentrun'),
        ),
    ]
