# Generated by Django 5.2.17 on 2026-10-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_original_content_protection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='originalcontent',
            name='ck_btn_output_shape',
        ),
        migrations.AddConstraint(
            model_name='originalcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'prepared'), ('verified_at__isnull', True)), models.Q(('status', 'approved'), ('verified_at__isnull', False), models.Q(models.Q(models.Q(('workflow_key__isnull', True), ('workflow_key', 'brand-window'), _connector='OR'), ('headline_en__gt', ''), ('headline_zh_cn__gt', ''), ('secondary_en__gt', ''), ('secondary_zh_cn__gt', '')), models.Q(('workflow_key__gt', ''), ('workflow_key__isnull', False), models.Q(('workflow_key', 'brand-window'), _negated=True)), _connector='OR')), ('status__in', ['held', 'unavailable', 'no_content', 'data_quality_unavailable']), _connector='OR'), name='ck_btn_output_shape'),
        ),
    ]
