# Generated by Django 5.2.17 on 2026-10-08 08:06

from typing import ClassVar

from django.db import migrations

DDL_TIMEOUTS = "SET LOCAL lock_timeout = '5s'; SET LOCAL statement_timeout = '30s';"


class Migration(migrations.Migration):
    # Running services keep using the old names until their process is replaced.
    # All renames and writable aliases must therefore become visible together.
    atomic = True

    dependencies: ClassVar[list] = [
        ("core", "0078_original_content_workflow_shape"),
    ]

    operations: ClassVar[list] = [
        migrations.RunSQL(DDL_TIMEOUTS, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterModelTable(
            name="contentpicture",
            table="content_pictures",
        ),
        migrations.AlterModelTable(
            name="originalcontent",
            table="original_content",
        ),
        migrations.AlterModelTable(
            name="originalcontentcall",
            table="original_content_calls",
        ),
        migrations.AlterModelTable(
            name="originalcontentrun",
            table="original_content_runs",
        ),
        migrations.AlterModelTable(
            name="originalcontentselection",
            table="original_content_selections",
        ),
        migrations.AlterModelTable(
            name="originalcontenttext",
            table="original_content_texts",
        ),
        migrations.RunSQL(
            "CREATE VIEW editorial_pictures AS SELECT * FROM content_pictures",
            reverse_sql="DROP VIEW editorial_pictures",
        ),
        migrations.RunSQL(
            "CREATE VIEW brand_trend_narratives AS SELECT * FROM original_content",
            reverse_sql="DROP VIEW brand_trend_narratives",
        ),
        migrations.RunSQL(
            "CREATE VIEW trend_narrative_provider_calls AS SELECT * FROM original_content_calls",
            reverse_sql="DROP VIEW trend_narrative_provider_calls",
        ),
        migrations.RunSQL(
            "CREATE VIEW trend_narrative_runs AS SELECT * FROM original_content_runs",
            reverse_sql="DROP VIEW trend_narrative_runs",
        ),
        migrations.RunSQL(
            "CREATE VIEW trend_narrative_visible_runs AS SELECT * FROM original_content_selections",
            reverse_sql="DROP VIEW trend_narrative_visible_runs",
        ),
        migrations.RunSQL(
            "CREATE VIEW brand_trend_narrative_texts AS SELECT * FROM original_content_texts",
            reverse_sql="DROP VIEW brand_trend_narrative_texts",
        ),
        # Reverse execution starts here: bound its locks before dropping aliases.
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql=DDL_TIMEOUTS),
    ]
