# Generated by Django 5.2.16 on 2026-10-09 04:20

from typing import ClassVar

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("core", "0079_original_content_physical_names"),
    ]

    operations: ClassVar[list] = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '5s'; SET LOCAL statement_timeout = '120s'; "
            "LOCK TABLE metric_values IN ACCESS EXCLUSIVE MODE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION measurement_window_v1(start_at timestamptz, end_at timestamptz)
            RETURNS tstzrange LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
            BEGIN
                IF (start_at IS NOT NULL AND NOT isfinite(start_at))
                   OR (end_at IS NOT NULL AND NOT isfinite(end_at)) THEN
                    RAISE EXCEPTION 'Measurement window endpoints must be finite'
                        USING ERRCODE = '23514';
                END IF;
                IF start_at IS NULL OR end_at IS NULL THEN
                    RETURN NULL;
                END IF;
                IF end_at <= start_at THEN
                    RAISE EXCEPTION 'Measurement window end must follow start'
                        USING ERRCODE = '23514';
                END IF;
                RETURN tstzrange(start_at, end_at, '[)');
            END;
            $$;
            COMMENT ON FUNCTION measurement_window_v1(timestamptz, timestamptz)
            IS 'Immutable v1: finite [start,end), NULL if either endpoint is unknown. Never replace semantics in place; migrate to a new function version.';
            """,
            reverse_sql="DROP FUNCTION measurement_window_v1(timestamptz, timestamptz)",
        ),
        migrations.AlterField(
            model_name="metricvalue",
            name="window_end_at",
            field=models.DateTimeField(
                db_comment="Exclusive measurement-window end; NULL means unknown, never infinity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metricvalue",
            name="window_start_at",
            field=models.DateTimeField(
                db_comment="Inclusive measurement-window start; NULL means unknown, never infinity.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metricvalue",
            name="window_range",
            field=models.GeneratedField(
                db_comment="Finite [start,end) measurement window: inclusive start, exclusive end. Generated from endpoints; NULL if either endpoint is unknown, never unbounded.",
                db_persist=True,
                expression=models.Func(
                    models.F("window_start_at"),
                    models.F("window_end_at"),
                    function="measurement_window_v1",
                    output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                null=True,
                output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
            ),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql="SET LOCAL lock_timeout = '5s'; SET LOCAL statement_timeout = '120s'; "
            "LOCK TABLE metric_values IN ACCESS EXCLUSIVE MODE",
        ),
    ]
