"""Generated country identity data. Do not edit by hand."""

from __future__ import annotations

COUNTRY_FLAGS: dict[str, dict[str, str]] = {
    'AD': {'name_en': 'Andorra', 'name_zh_cn': '安道尔'},
    'AE': {'name_en': 'United Arab Emirates', 'name_zh_cn': '阿拉伯联合酋长国'},
    'AF': {'name_en': 'Afghanistan', 'name_zh_cn': '阿富汗'},
    'AG': {'name_en': 'Antigua & Barbuda', 'name_zh_cn': '安提瓜和巴布达'},
    'AL': {'name_en': 'Albania', 'name_zh_cn': '阿尔巴尼亚'},
    'AM': {'name_en': 'Armenia', 'name_zh_cn': '亚美尼亚'},
    'AO': {'name_en': 'Angola', 'name_zh_cn': '安哥拉'},
    'AR': {'name_en': 'Argentina', 'name_zh_cn': '阿根廷'},
    'AT': {'name_en': 'Austria', 'name_zh_cn': '奥地利'},
    'AU': {'name_en': 'Australia', 'name_zh_cn': '澳大利亚'},
    'AZ': {'name_en': 'Azerbaijan', 'name_zh_cn': '阿塞拜疆'},
    'BA': {'name_en': 'Bosnia & Herzegovina', 'name_zh_cn': '波斯尼亚和黑塞哥维那'},
    'BB': {'name_en': 'Barbados', 'name_zh_cn': '巴巴多斯'},
    'BD': {'name_en': 'Bangladesh', 'name_zh_cn': '孟加拉国'},
    'BE': {'name_en': 'Belgium', 'name_zh_cn': '比利时'},
    'BF': {'name_en': 'Burkina Faso', 'name_zh_cn': '布基纳法索'},
    'BG': {'name_en': 'Bulgaria', 'name_zh_cn': '保加利亚'},
    'BH': {'name_en': 'Bahrain', 'name_zh_cn': '巴林'},
    'BI': {'name_en': 'Burundi', 'name_zh_cn': '布隆迪'},
    'BJ': {'name_en': 'Benin', 'name_zh_cn': '贝宁'},
    'BN': {'name_en': 'Brunei', 'name_zh_cn': '文莱'},
    'BO': {'name_en': 'Bolivia', 'name_zh_cn': '玻利维亚'},
    'BR': {'name_en': 'Brazil', 'name_zh_cn': '巴西'},
    'BS': {'name_en': 'Bahamas', 'name_zh_cn': '巴哈马'},
    'BT': {'name_en': 'Bhutan', 'name_zh_cn': '不丹'},
    'BW': {'name_en': 'Botswana', 'name_zh_cn': '博茨瓦纳'},
    'BY': {'name_en': 'Belarus', 'name_zh_cn': '白俄罗斯'},
    'BZ': {'name_en': 'Belize', 'name_zh_cn': '伯利兹'},
    'CA': {'name_en': 'Canada', 'name_zh_cn': '加拿大'},
    'CD': {'name_en': 'Congo - Kinshasa', 'name_zh_cn': '刚果（金）'},
    'CF': {'name_en': 'Central African Republic', 'name_zh_cn': '中非共和国'},
    'CG': {'name_en': 'Congo - Brazzaville', 'name_zh_cn': '刚果（布）'},
    'CH': {'name_en': 'Switzerland', 'name_zh_cn': '瑞士'},
    'CI': {'name_en': 'Côte d’Ivoire', 'name_zh_cn': '科特迪瓦'},
    'CL': {'name_en': 'Chile', 'name_zh_cn': '智利'},
    'CM': {'name_en': 'Cameroon', 'name_zh_cn': '喀麦隆'},
    'CN': {'name_en': 'China', 'name_zh_cn': '中国'},
    'CO': {'name_en': 'Colombia', 'name_zh_cn': '哥伦比亚'},
    'CR': {'name_en': 'Costa Rica', 'name_zh_cn': '哥斯达黎加'},
    'CU': {'name_en': 'Cuba', 'name_zh_cn': '古巴'},
    'CV': {'name_en': 'Cape Verde', 'name_zh_cn': '佛得角'},
    'CY': {'name_en': 'Cyprus', 'name_zh_cn': '塞浦路斯'},
    'CZ': {'name_en': 'Czechia', 'name_zh_cn': '捷克'},
    'DE': {'name_en': 'Germany', 'name_zh_cn': '德国'},
    'DJ': {'name_en': 'Djibouti', 'name_zh_cn': '吉布提'},
    'DK': {'name_en': 'Denmark', 'name_zh_cn': '丹麦'},
    'DM': {'name_en': 'Dominica', 'name_zh_cn': '多米尼克'},
    'DO': {'name_en': 'Dominican Republic', 'name_zh_cn': '多米尼加共和国'},
    'DZ': {'name_en': 'Algeria', 'name_zh_cn': '阿尔及利亚'},
    'EC': {'name_en': 'Ecuador', 'name_zh_cn': '厄瓜多尔'},
    'EE': {'name_en': 'Estonia', 'name_zh_cn': '爱沙尼亚'},
    'EG': {'name_en': 'Egypt', 'name_zh_cn': '埃及'},
    'ER': {'name_en': 'Eritrea', 'name_zh_cn': '厄立特里亚'},
    'ES': {'name_en': 'Spain', 'name_zh_cn': '西班牙'},
    'ET': {'name_en': 'Ethiopia', 'name_zh_cn': '埃塞俄比亚'},
    'FI': {'name_en': 'Finland', 'name_zh_cn': '芬兰'},
    'FJ': {'name_en': 'Fiji', 'name_zh_cn': '斐济'},
    'FM': {'name_en': 'Micronesia', 'name_zh_cn': '密克罗尼西亚'},
    'FR': {'name_en': 'France', 'name_zh_cn': '法国'},
    'GA': {'name_en': 'Gabon', 'name_zh_cn': '加蓬'},
    'GB': {'name_en': 'United Kingdom', 'name_zh_cn': '英国'},
    'GD': {'name_en': 'Grenada', 'name_zh_cn': '格林纳达'},
    'GE': {'name_en': 'Georgia', 'name_zh_cn': '格鲁吉亚'},
    'GH': {'name_en': 'Ghana', 'name_zh_cn': '加纳'},
    'GM': {'name_en': 'Gambia', 'name_zh_cn': '冈比亚'},
    'GN': {'name_en': 'Guinea', 'name_zh_cn': '几内亚'},
    'GQ': {'name_en': 'Equatorial Guinea', 'name_zh_cn': '赤道几内亚'},
    'GR': {'name_en': 'Greece', 'name_zh_cn': '希腊'},
    'GT': {'name_en': 'Guatemala', 'name_zh_cn': '危地马拉'},
    'GW': {'name_en': 'Guinea-Bissau', 'name_zh_cn': '几内亚比绍'},
    'GY': {'name_en': 'Guyana', 'name_zh_cn': '圭亚那'},
    'HN': {'name_en': 'Honduras', 'name_zh_cn': '洪都拉斯'},
    'HR': {'name_en': 'Croatia', 'name_zh_cn': '克罗地亚'},
    'HT': {'name_en': 'Haiti', 'name_zh_cn': '海地'},
    'HU': {'name_en': 'Hungary', 'name_zh_cn': '匈牙利'},
    'ID': {'name_en': 'Indonesia', 'name_zh_cn': '印度尼西亚'},
    'IE': {'name_en': 'Ireland', 'name_zh_cn': '爱尔兰'},
    'IL': {'name_en': 'Israel', 'name_zh_cn': '以色列'},
    'IN': {'name_en': 'India', 'name_zh_cn': '印度'},
    'IQ': {'name_en': 'Iraq', 'name_zh_cn': '伊拉克'},
    'IR': {'name_en': 'Iran', 'name_zh_cn': '伊朗'},
    'IS': {'name_en': 'Iceland', 'name_zh_cn': '冰岛'},
    'IT': {'name_en': 'Italy', 'name_zh_cn': '意大利'},
    'JM': {'name_en': 'Jamaica', 'name_zh_cn': '牙买加'},
    'JO': {'name_en': 'Jordan', 'name_zh_cn': '约旦'},
    'JP': {'name_en': 'Japan', 'name_zh_cn': '日本'},
    'KE': {'name_en': 'Kenya', 'name_zh_cn': '肯尼亚'},
    'KG': {'name_en': 'Kyrgyzstan', 'name_zh_cn': '吉尔吉斯斯坦'},
    'KH': {'name_en': 'Cambodia', 'name_zh_cn': '柬埔寨'},
    'KI': {'name_en': 'Kiribati', 'name_zh_cn': '基里巴斯'},
    'KM': {'name_en': 'Comoros', 'name_zh_cn': '科摩罗'},
    'KN': {'name_en': 'St. Kitts & Nevis', 'name_zh_cn': '圣基茨和尼维斯'},
    'KP': {'name_en': 'North Korea', 'name_zh_cn': '朝鲜'},
    'KR': {'name_en': 'South Korea', 'name_zh_cn': '韩国'},
    'KW': {'name_en': 'Kuwait', 'name_zh_cn': '科威特'},
    'KZ': {'name_en': 'Kazakhstan', 'name_zh_cn': '哈萨克斯坦'},
    'LA': {'name_en': 'Laos', 'name_zh_cn': '老挝'},
    'LB': {'name_en': 'Lebanon', 'name_zh_cn': '黎巴嫩'},
    'LC': {'name_en': 'St. Lucia', 'name_zh_cn': '圣卢西亚'},
    'LI': {'name_en': 'Liechtenstein', 'name_zh_cn': '列支敦士登'},
    'LK': {'name_en': 'Sri Lanka', 'name_zh_cn': '斯里兰卡'},
    'LR': {'name_en': 'Liberia', 'name_zh_cn': '利比里亚'},
    'LS': {'name_en': 'Lesotho', 'name_zh_cn': '莱索托'},
    'LT': {'name_en': 'Lithuania', 'name_zh_cn': '立陶宛'},
    'LU': {'name_en': 'Luxembourg', 'name_zh_cn': '卢森堡'},
    'LV': {'name_en': 'Latvia', 'name_zh_cn': '拉脱维亚'},
    'LY': {'name_en': 'Libya', 'name_zh_cn': '利比亚'},
    'MA': {'name_en': 'Morocco', 'name_zh_cn': '摩洛哥'},
    'MC': {'name_en': 'Monaco', 'name_zh_cn': '摩纳哥'},
    'MD': {'name_en': 'Moldova', 'name_zh_cn': '摩尔多瓦'},
    'ME': {'name_en': 'Montenegro', 'name_zh_cn': '黑山'},
    'MG': {'name_en': 'Madagascar', 'name_zh_cn': '马达加斯加'},
    'MH': {'name_en': 'Marshall Islands', 'name_zh_cn': '马绍尔群岛'},
    'MK': {'name_en': 'North Macedonia', 'name_zh_cn': '北马其顿'},
    'ML': {'name_en': 'Mali', 'name_zh_cn': '马里'},
    'MM': {'name_en': 'Myanmar (Burma)', 'name_zh_cn': '缅甸'},
    'MN': {'name_en': 'Mongolia', 'name_zh_cn': '蒙古'},
    'MR': {'name_en': 'Mauritania', 'name_zh_cn': '毛里塔尼亚'},
    'MT': {'name_en': 'Malta', 'name_zh_cn': '马耳他'},
    'MU': {'name_en': 'Mauritius', 'name_zh_cn': '毛里求斯'},
    'MV': {'name_en': 'Maldives', 'name_zh_cn': '马尔代夫'},
    'MW': {'name_en': 'Malawi', 'name_zh_cn': '马拉维'},
    'MX': {'name_en': 'Mexico', 'name_zh_cn': '墨西哥'},
    'MY': {'name_en': 'Malaysia', 'name_zh_cn': '马来西亚'},
    'MZ': {'name_en': 'Mozambique', 'name_zh_cn': '莫桑比克'},
    'NA': {'name_en': 'Namibia', 'name_zh_cn': '纳米比亚'},
    'NE': {'name_en': 'Niger', 'name_zh_cn': '尼日尔'},
    'NG': {'name_en': 'Nigeria', 'name_zh_cn': '尼日利亚'},
    'NI': {'name_en': 'Nicaragua', 'name_zh_cn': '尼加拉瓜'},
    'NL': {'name_en': 'Netherlands', 'name_zh_cn': '荷兰'},
    'NO': {'name_en': 'Norway', 'name_zh_cn': '挪威'},
    'NP': {'name_en': 'Nepal', 'name_zh_cn': '尼泊尔'},
    'NR': {'name_en': 'Nauru', 'name_zh_cn': '瑙鲁'},
    'NZ': {'name_en': 'New Zealand', 'name_zh_cn': '新西兰'},
    'OM': {'name_en': 'Oman', 'name_zh_cn': '阿曼'},
    'PA': {'name_en': 'Panama', 'name_zh_cn': '巴拿马'},
    'PE': {'name_en': 'Peru', 'name_zh_cn': '秘鲁'},
    'PG': {'name_en': 'Papua New Guinea', 'name_zh_cn': '巴布亚新几内亚'},
    'PH': {'name_en': 'Philippines', 'name_zh_cn': '菲律宾'},
    'PK': {'name_en': 'Pakistan', 'name_zh_cn': '巴基斯坦'},
    'PL': {'name_en': 'Poland', 'name_zh_cn': '波兰'},
    'PS': {'name_en': 'Palestinian Territories', 'name_zh_cn': '巴勒斯坦领土'},
    'PT': {'name_en': 'Portugal', 'name_zh_cn': '葡萄牙'},
    'PW': {'name_en': 'Palau', 'name_zh_cn': '帕劳'},
    'PY': {'name_en': 'Paraguay', 'name_zh_cn': '巴拉圭'},
    'QA': {'name_en': 'Qatar', 'name_zh_cn': '卡塔尔'},
    'RO': {'name_en': 'Romania', 'name_zh_cn': '罗马尼亚'},
    'RS': {'name_en': 'Serbia', 'name_zh_cn': '塞尔维亚'},
    'RU': {'name_en': 'Russia', 'name_zh_cn': '俄罗斯'},
    'RW': {'name_en': 'Rwanda', 'name_zh_cn': '卢旺达'},
    'SA': {'name_en': 'Saudi Arabia', 'name_zh_cn': '沙特阿拉伯'},
    'SB': {'name_en': 'Solomon Islands', 'name_zh_cn': '所罗门群岛'},
    'SC': {'name_en': 'Seychelles', 'name_zh_cn': '塞舌尔'},
    'SD': {'name_en': 'Sudan', 'name_zh_cn': '苏丹'},
    'SE': {'name_en': 'Sweden', 'name_zh_cn': '瑞典'},
    'SG': {'name_en': 'Singapore', 'name_zh_cn': '新加坡'},
    'SI': {'name_en': 'Slovenia', 'name_zh_cn': '斯洛文尼亚'},
    'SK': {'name_en': 'Slovakia', 'name_zh_cn': '斯洛伐克'},
    'SL': {'name_en': 'Sierra Leone', 'name_zh_cn': '塞拉利昂'},
    'SM': {'name_en': 'San Marino', 'name_zh_cn': '圣马力诺'},
    'SN': {'name_en': 'Senegal', 'name_zh_cn': '塞内加尔'},
    'SO': {'name_en': 'Somalia', 'name_zh_cn': '索马里'},
    'SR': {'name_en': 'Suriname', 'name_zh_cn': '苏里南'},
    'SS': {'name_en': 'South Sudan', 'name_zh_cn': '南苏丹'},
    'ST': {'name_en': 'São Tomé & Príncipe', 'name_zh_cn': '圣多美和普林西比'},
    'SV': {'name_en': 'El Salvador', 'name_zh_cn': '萨尔瓦多'},
    'SY': {'name_en': 'Syria', 'name_zh_cn': '叙利亚'},
    'SZ': {'name_en': 'Eswatini', 'name_zh_cn': '斯威士兰'},
    'TD': {'name_en': 'Chad', 'name_zh_cn': '乍得'},
    'TG': {'name_en': 'Togo', 'name_zh_cn': '多哥'},
    'TH': {'name_en': 'Thailand', 'name_zh_cn': '泰国'},
    'TJ': {'name_en': 'Tajikistan', 'name_zh_cn': '塔吉克斯坦'},
    'TL': {'name_en': 'Timor-Leste', 'name_zh_cn': '东帝汶'},
    'TM': {'name_en': 'Turkmenistan', 'name_zh_cn': '土库曼斯坦'},
    'TN': {'name_en': 'Tunisia', 'name_zh_cn': '突尼斯'},
    'TO': {'name_en': 'Tonga', 'name_zh_cn': '汤加'},
    'TR': {'name_en': 'Türkiye', 'name_zh_cn': '土耳其'},
    'TT': {'name_en': 'Trinidad & Tobago', 'name_zh_cn': '特立尼达和多巴哥'},
    'TV': {'name_en': 'Tuvalu', 'name_zh_cn': '图瓦卢'},
    'TW': {'name_en': 'Taiwan', 'name_zh_cn': '台湾'},
    'TZ': {'name_en': 'Tanzania', 'name_zh_cn': '坦桑尼亚'},
    'UA': {'name_en': 'Ukraine', 'name_zh_cn': '乌克兰'},
    'UG': {'name_en': 'Uganda', 'name_zh_cn': '乌干达'},
    'US': {'name_en': 'United States', 'name_zh_cn': '美国'},
    'UY': {'name_en': 'Uruguay', 'name_zh_cn': '乌拉圭'},
    'UZ': {'name_en': 'Uzbekistan', 'name_zh_cn': '乌兹别克斯坦'},
    'VA': {'name_en': 'Vatican City', 'name_zh_cn': '梵蒂冈'},
    'VC': {'name_en': 'St. Vincent & Grenadines', 'name_zh_cn': '圣文森特和格林纳丁斯'},
    'VE': {'name_en': 'Venezuela', 'name_zh_cn': '委内瑞拉'},
    'VN': {'name_en': 'Vietnam', 'name_zh_cn': '越南'},
    'VU': {'name_en': 'Vanuatu', 'name_zh_cn': '瓦努阿图'},
    'WS': {'name_en': 'Samoa', 'name_zh_cn': '萨摩亚'},
    'XK': {'name_en': 'Kosovo', 'name_zh_cn': '科索沃'},
    'YE': {'name_en': 'Yemen', 'name_zh_cn': '也门'},
    'ZA': {'name_en': 'South Africa', 'name_zh_cn': '南非'},
    'ZM': {'name_en': 'Zambia', 'name_zh_cn': '赞比亚'},
    'ZW': {'name_en': 'Zimbabwe', 'name_zh_cn': '津巴布韦'},
}

_NAME_TO_CODE: dict[str, str] = {
    'afghanistan': 'AF',
    'albania': 'AL',
    'algeria': 'DZ',
    'andorra': 'AD',
    'angola': 'AO',
    'antigua & barbuda': 'AG',
    'argentina': 'AR',
    'armenia': 'AM',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'benin': 'BJ',
    'bhutan': 'BT',
    'bolivia': 'BO',
    'bosnia & herzegovina': 'BA',
    'botswana': 'BW',
    'brazil': 'BR',
    'brunei': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cape verde': 'CV',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'colombia': 'CO',
    'comoros': 'KM',
    'congo - brazzaville': 'CG',
    'congo - kinshasa': 'CD',
    'costa rica': 'CR',
    'croatia': 'HR',
    'cuba': 'CU',
    'cyprus': 'CY',
    'czechia': 'CZ',
    'côte d’ivoire': 'CI',
    'denmark': 'DK',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'ecuador': 'EC',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'fiji': 'FJ',
    'finland': 'FI',
    'france': 'FR',
    'gabon': 'GA',
    'gambia': 'GM',
    'georgia': 'GE',
    'germany': 'DE',
    'ghana': 'GH',
    'greece': 'GR',
    'grenada': 'GD',
    'guatemala': 'GT',
    'guinea': 'GN',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'haiti': 'HT',
    'honduras': 'HN',
    'hungary': 'HU',
    'iceland': 'IS',
    'india': 'IN',
    'indonesia': 'ID',
    'iran': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'israel': 'IL',
    'italy': 'IT',
    'jamaica': 'JM',
    'japan': 'JP',
    'jordan': 'JO',
    'kazakhstan': 'KZ',
    'kenya': 'KE',
    'kiribati': 'KI',
    'kosovo': 'XK',
    'kuwait': 'KW',
    'kyrgyzstan': 'KG',
    'laos': 'LA',
    'latvia': 'LV',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marshall islands': 'MH',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mexico': 'MX',
    'micronesia': 'FM',
    'moldova': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'morocco': 'MA',
    'mozambique': 'MZ',
    'myanmar (burma)': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'netherlands': 'NL',
    'new zealand': 'NZ',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'north korea': 'KP',
    'north macedonia': 'MK',
    'norway': 'NO',
    'oman': 'OM',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestinian territories': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    'peru': 'PE',
    'philippines': 'PH',
    'poland': 'PL',
    'portugal': 'PT',
    'qatar': 'QA',
    'romania': 'RO',
    'russia': 'RU',
    'rwanda': 'RW',
    'samoa': 'WS',
    'san marino': 'SM',
    'saudi arabia': 'SA',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'south africa': 'ZA',
    'south korea': 'KR',
    'south sudan': 'SS',
    'spain': 'ES',
    'sri lanka': 'LK',
    'st. kitts & nevis': 'KN',
    'st. lucia': 'LC',
    'st. vincent & grenadines': 'VC',
    'sudan': 'SD',
    'suriname': 'SR',
    'sweden': 'SE',
    'switzerland': 'CH',
    'syria': 'SY',
    'são tomé & príncipe': 'ST',
    'taiwan': 'TW',
    'tajikistan': 'TJ',
    'tanzania': 'TZ',
    'thailand': 'TH',
    'timor-leste': 'TL',
    'togo': 'TG',
    'tonga': 'TO',
    'trinidad & tobago': 'TT',
    'tunisia': 'TN',
    'turkmenistan': 'TM',
    'tuvalu': 'TV',
    'türkiye': 'TR',
    'uganda': 'UG',
    'ukraine': 'UA',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united states': 'US',
    'uruguay': 'UY',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'vatican city': 'VA',
    'venezuela': 'VE',
    'vietnam': 'VN',
    'yemen': 'YE',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    '不丹': 'BT',
    '东帝汶': 'TL',
    '中国': 'CN',
    '中非共和国': 'CF',
    '丹麦': 'DK',
    '乌克兰': 'UA',
    '乌兹别克斯坦': 'UZ',
    '乌干达': 'UG',
    '乌拉圭': 'UY',
    '乍得': 'TD',
    '也门': 'YE',
    '亚美尼亚': 'AM',
    '以色列': 'IL',
    '伊拉克': 'IQ',
    '伊朗': 'IR',
    '伯利兹': 'BZ',
    '佛得角': 'CV',
    '俄罗斯': 'RU',
    '保加利亚': 'BG',
    '克罗地亚': 'HR',
    '冈比亚': 'GM',
    '冰岛': 'IS',
    '几内亚': 'GN',
    '几内亚比绍': 'GW',
    '列支敦士登': 'LI',
    '刚果（布）': 'CG',
    '刚果（金）': 'CD',
    '利比亚': 'LY',
    '利比里亚': 'LR',
    '加拿大': 'CA',
    '加纳': 'GH',
    '加蓬': 'GA',
    '匈牙利': 'HU',
    '北马其顿': 'MK',
    '南苏丹': 'SS',
    '南非': 'ZA',
    '博茨瓦纳': 'BW',
    '卡塔尔': 'QA',
    '卢旺达': 'RW',
    '卢森堡': 'LU',
    '印度': 'IN',
    '印度尼西亚': 'ID',
    '危地马拉': 'GT',
    '厄瓜多尔': 'EC',
    '厄立特里亚': 'ER',
    '叙利亚': 'SY',
    '古巴': 'CU',
    '台湾': 'TW',
    '吉尔吉斯斯坦': 'KG',
    '吉布提': 'DJ',
    '哈萨克斯坦': 'KZ',
    '哥伦比亚': 'CO',
    '哥斯达黎加': 'CR',
    '喀麦隆': 'CM',
    '图瓦卢': 'TV',
    '土库曼斯坦': 'TM',
    '土耳其': 'TR',
    '圣卢西亚': 'LC',
    '圣基茨和尼维斯': 'KN',
    '圣多美和普林西比': 'ST',
    '圣文森特和格林纳丁斯': 'VC',
    '圣马力诺': 'SM',
    '圭亚那': 'GY',
    '坦桑尼亚': 'TZ',
    '埃及': 'EG',
    '埃塞俄比亚': 'ET',
    '基里巴斯': 'KI',
    '塔吉克斯坦': 'TJ',
    '塞内加尔': 'SN',
    '塞尔维亚': 'RS',
    '塞拉利昂': 'SL',
    '塞浦路斯': 'CY',
    '塞舌尔': 'SC',
    '墨西哥': 'MX',
    '多哥': 'TG',
    '多米尼克': 'DM',
    '多米尼加共和国': 'DO',
    '奥地利': 'AT',
    '委内瑞拉': 'VE',
    '孟加拉国': 'BD',
    '安哥拉': 'AO',
    '安提瓜和巴布达': 'AG',
    '安道尔': 'AD',
    '密克罗尼西亚': 'FM',
    '尼加拉瓜': 'NI',
    '尼日利亚': 'NG',
    '尼日尔': 'NE',
    '尼泊尔': 'NP',
    '巴勒斯坦领土': 'PS',
    '巴哈马': 'BS',
    '巴基斯坦': 'PK',
    '巴巴多斯': 'BB',
    '巴布亚新几内亚': 'PG',
    '巴拉圭': 'PY',
    '巴拿马': 'PA',
    '巴林': 'BH',
    '巴西': 'BR',
    '布基纳法索': 'BF',
    '布隆迪': 'BI',
    '希腊': 'GR',
    '帕劳': 'PW',
    '德国': 'DE',
    '意大利': 'IT',
    '所罗门群岛': 'SB',
    '拉脱维亚': 'LV',
    '挪威': 'NO',
    '捷克': 'CZ',
    '摩尔多瓦': 'MD',
    '摩洛哥': 'MA',
    '摩纳哥': 'MC',
    '文莱': 'BN',
    '斐济': 'FJ',
    '斯威士兰': 'SZ',
    '斯洛伐克': 'SK',
    '斯洛文尼亚': 'SI',
    '斯里兰卡': 'LK',
    '新加坡': 'SG',
    '新西兰': 'NZ',
    '日本': 'JP',
    '智利': 'CL',
    '朝鲜': 'KP',
    '柬埔寨': 'KH',
    '格林纳达': 'GD',
    '格鲁吉亚': 'GE',
    '梵蒂冈': 'VA',
    '比利时': 'BE',
    '毛里塔尼亚': 'MR',
    '毛里求斯': 'MU',
    '汤加': 'TO',
    '沙特阿拉伯': 'SA',
    '法国': 'FR',
    '波兰': 'PL',
    '波斯尼亚和黑塞哥维那': 'BA',
    '泰国': 'TH',
    '津巴布韦': 'ZW',
    '洪都拉斯': 'HN',
    '海地': 'HT',
    '澳大利亚': 'AU',
    '爱尔兰': 'IE',
    '爱沙尼亚': 'EE',
    '牙买加': 'JM',
    '特立尼达和多巴哥': 'TT',
    '玻利维亚': 'BO',
    '瑙鲁': 'NR',
    '瑞典': 'SE',
    '瑞士': 'CH',
    '瓦努阿图': 'VU',
    '白俄罗斯': 'BY',
    '科威特': 'KW',
    '科摩罗': 'KM',
    '科特迪瓦': 'CI',
    '科索沃': 'XK',
    '秘鲁': 'PE',
    '突尼斯': 'TN',
    '立陶宛': 'LT',
    '索马里': 'SO',
    '约旦': 'JO',
    '纳米比亚': 'NA',
    '缅甸': 'MM',
    '罗马尼亚': 'RO',
    '美国': 'US',
    '老挝': 'LA',
    '肯尼亚': 'KE',
    '芬兰': 'FI',
    '苏丹': 'SD',
    '苏里南': 'SR',
    '英国': 'GB',
    '荷兰': 'NL',
    '莫桑比克': 'MZ',
    '莱索托': 'LS',
    '菲律宾': 'PH',
    '萨尔瓦多': 'SV',
    '萨摩亚': 'WS',
    '葡萄牙': 'PT',
    '蒙古': 'MN',
    '西班牙': 'ES',
    '贝宁': 'BJ',
    '赞比亚': 'ZM',
    '赤道几内亚': 'GQ',
    '越南': 'VN',
    '阿塞拜疆': 'AZ',
    '阿富汗': 'AF',
    '阿尔及利亚': 'DZ',
    '阿尔巴尼亚': 'AL',
    '阿拉伯联合酋长国': 'AE',
    '阿曼': 'OM',
    '阿根廷': 'AR',
    '韩国': 'KR',
    '马尔代夫': 'MV',
    '马拉维': 'MW',
    '马来西亚': 'MY',
    '马绍尔群岛': 'MH',
    '马耳他': 'MT',
    '马达加斯加': 'MG',
    '马里': 'ML',
    '黎巴嫩': 'LB',
    '黑山': 'ME',
}


def normalize_country_code(value: str | None) -> str | None:
    """Return a supported code for an exact code or canonical name."""

    if not isinstance(value, str):
        return None
    normalized = value.strip()
    if not normalized:
        return None
    code = normalized.upper()
    if len(code) == 2 and code in COUNTRY_FLAGS:
        return code
    return _NAME_TO_CODE.get(normalized.casefold())


def country_identity(value: str | None, locale: str) -> dict[str, str] | None:
    """Return the normalized code and locale-selected display name."""

    code = normalize_country_code(value)
    if code is None:
        return None
    locale_key = (locale or '').replace('-', '_').casefold()
    name_key = 'name_zh_cn' if locale_key.startswith('zh') else 'name_en'
    return {'code': code, 'name': COUNTRY_FLAGS[code][name_key]}
