"""Generate docs/reference/twitterapi-live-queries-by-model.md from live policy.

Plan: docs/plans/2026-08-05-001-refactor-harvest-policy-3of5-plan.md
Unit U5 (R15) — M11: current state only, no remnant dual-authoring prose.

4/5 will auto-regen this file from preview output. For 3/5, this script
is the authoritative regenerator — it can be re-run after any policy
edit and the resulting file is byte-current.
"""

import sys
from pathlib import Path

# Ensure repo importable
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from x_monitor.harvest_policy import load_policy
from x_monitor.query_plan import plan_calls
from x_monitor.specs_from_policy import (
    primary_keywords_from_policy,
    specs_from_policy,
)


REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "reference" / "twitterapi-live-queries-by-model.md"
POLICY = REPO / "config" / "harvest_policy.yaml"
CONFIG = REPO / "config.yaml"


def _load_yaml(path: Path) -> dict:
    import yaml
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _enabled_models() -> list[str]:
    cfg = _load_yaml(CONFIG)
    return list(cfg.get("enabled_models") or [])


def _list_id() -> str:
    cfg = _load_yaml(CONFIG)
    return str(cfg.get("x_monitor_list_id") or "")


def main() -> None:
    policy = load_policy(POLICY)
    enabled = _enabled_models()
    specs = specs_from_policy(policy)
    pkws = primary_keywords_from_policy(policy)
    list_id = _list_id()
    calls = plan_calls(list_id, specs, primary_keywords=pkws)

    by_id = {c.call_id: c for c in calls}

    lines: list[str] = []
    lines.append("# TwitterAPI live queries by model")
    lines.append("")
    lines.append(
        "**Authoritative source:** this file is generated by "
        "`scripts/build_reference_doc.py` from `config/harvest_policy.yaml` "
        "+ `config.yaml`. Re-run that script after any policy edit. "
        "Live strings at runtime come from `harvest_preview` (offline) and "
        "the cycle planner (`monitor/cycle.py:plan_calls_for_cycle`). "
        "Do not hand-edit — git history is the archive (M11)."
    )
    lines.append("")
    lines.append(f"**Enabled models ({len(enabled)}):** "
                 + ", ".join(enabled))
    lines.append("")
    lines.append(f"**Call A list id:** `{list_id}`")
    lines.append("")
    lines.append("## Calls")
    lines.append("")
    lines.append("| call_id | kind | length | headroom | shape |")
    lines.append("|---|---|---:|---:|---|")
    for cid in ("A", "B1", "B2", "B3", "C1", "C2", "C3"):
        if cid not in by_id:
            continue
        c = by_id[cid]
        if c.call_kind == "account":
            shape = "list-based fan-in"
        elif c.call_kind == "brand_wide" and not c.query_string.startswith("(@"):
            shape = "paren-grouped OR of brand tokens"
        elif c.query_string.startswith("(@"):
            shape = "handle-only OR of @-handles"
        else:
            shape = "mixed"
        lines.append(f"| {cid} | {c.call_kind} | {c.query_length} | "
                     f"{512 - c.query_length} | {shape} |")
    lines.append("")
    lines.append("## Brand → call_ids coverage")
    lines.append("")
    lines.append("| brand | call_ids | paths | handle_tier |")
    lines.append("|---|---|---|---|")
    for nick in enabled:
        b = policy.brands.get(nick)
        if b is None:
            lines.append(f"| {nick} | — | (not in policy) | — |")
            continue
        # Reverse-derive which call_ids this brand appears on
        cids: set[str] = set()
        for s in specs:
            if s.call_id == "B1" and "bare" in b.paths and nick in s.wide_net_brands:
                cids.add("B1")
            elif s.call_id == "B2" and "handle" in b.paths and any(h in s.handles for h in b.handles):
                if b.handle_tier == "top-presence":
                    cids.add("B2")
            elif s.call_id == "B3" and "handle" in b.paths and any(h in s.handles for h in b.handles):
                if b.handle_tier == "other":
                    cids.add("B3")
            elif s.call_id.startswith("C") and "co" in b.paths and nick in s.brands:
                cids.add(s.call_id)
        paths_str = ",".join(sorted(b.paths))
        tier = b.handle_tier if "handle" in b.paths else "—"
        lines.append(f"| {nick} | {', '.join(sorted(cids)) if cids else '—'} "
                     f"| {paths_str} | {tier} |")
    lines.append("")
    lines.append("## Co packs (3/5)")
    lines.append("")
    lines.append("| pack | brands | co_occurrence | not_include |")
    lines.append("|---|---|---|---|")
    for i, pack in enumerate(policy.co_packs, start=1):
        cid = f"C{i}"
        spec = next((s for s in specs if s.call_id == cid), None)
        if spec is None:
            continue
        co_terms = ", ".join(spec.co_occurrence)
        ni_terms = ", ".join(spec.not_include) if spec.not_include else "—"
        lines.append(f"| {cid} | {', '.join(pack.brand_nicknames)} | "
                     f"{co_terms} | {ni_terms} |")
    lines.append("")
    lines.append("## Hand-written queries (verbatim, from preview)")
    lines.append("")
    for cid in ("A", "B1", "B2", "B3", "C1", "C2", "C3"):
        if cid not in by_id:
            continue
        c = by_id[cid]
        lines.append(f"### {cid}")
        lines.append("")
        lines.append("```")
        lines.append(c.query_string)
        lines.append("```")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()